import type { TekkenMoveEntry, TekkenMoveDef, TekkenCommandInput } from "../state/TekkenState";
import { TekkenAttackHeight, TekkenLimb } from "../../types";

function move(
  id: string,
  name: string,
  height: TekkenAttackHeight,
  limb: TekkenLimb,
  opts: Partial<TekkenMoveDef> = {},
): TekkenMoveDef {
  return {
    id,
    name,
    type: "normal",
    height,
    limb,
    startup: 12,
    active: 3,
    recovery: 12,
    onHit: 0,
    onBlock: -4,
    onCounterHit: 4,
    damage: 15,
    chipDamage: 2,
    isLauncher: false,
    launchHeight: 0,
    isScrew: false,
    isBound: false,
    isHoming: false,
    isPowerCrush: false,
    hasHighCrush: false,
    hasLowCrush: false,
    knockback: 0.3,
    wallSplat: false,
    hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    advanceDistance: 0.1,
    ...opts,
  };
}

function cmd(direction: string, buttons: string[]): TekkenCommandInput[] {
  return [{ direction, buttons }];
}

export const UNIVERSAL_MOVES: TekkenMoveEntry[] = [
  // ── HIGH attacks ──────────────────────────────────────────────────────
  {
    input: cmd("n", ["lp"]),
    move: move("1", "Jab", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 10,
      active: 2,
      recovery: 8,
      onHit: 1,
      onBlock: 1,
      onCounterHit: 3,
      damage: 7,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["rp"]),
    move: move("2", "Straight", TekkenAttackHeight.HIGH, TekkenLimb.RIGHT_PUNCH, {
      startup: 12,
      active: 3,
      recovery: 10,
      onHit: 3,
      onBlock: -1,
      onCounterHit: 5,
      damage: 12,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["rk"]),
    move: move("4", "Roundhouse", TekkenAttackHeight.HIGH, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 4,
      recovery: 14,
      onHit: 7,
      onBlock: -6,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 3,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["lp", "lk"]),
    move: move("1+3", "Throw", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      type: "throw",
      startup: 12,
      active: 2,
      recovery: 30,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 35,
      chipDamage: 0,
      knockback: 0.6,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },

  // ── MID attacks ───────────────────────────────────────────────────────
  {
    input: cmd("d", ["lp"]),
    move: move("d+1", "Mid Jab", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 12,
      active: 2,
      recovery: 10,
      onHit: 2,
      onBlock: -2,
      onCounterHit: 4,
      damage: 10,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d", ["rp"]),
    move: move("d+2", "Uppercut", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 15,
      active: 3,
      recovery: 22,
      onHit: 0,
      onBlock: -13,
      onCounterHit: 0,
      damage: 18,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.22,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["lk"]),
    move: move("3", "Front Kick", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 14,
      active: 3,
      recovery: 12,
      onHit: 5,
      onBlock: -4,
      onCounterHit: 8,
      damage: 17,
      chipDamage: 2,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/f", ["lp"]),
    move: move("d/f+1", "Mid Poke", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 13,
      active: 2,
      recovery: 10,
      onHit: 5,
      onBlock: -3,
      onCounterHit: 7,
      damage: 13,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/f", ["rp"]),
    move: move("d/f+2", "Mid Launcher", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 15,
      active: 3,
      recovery: 22,
      onHit: 0,
      onBlock: -12,
      onCounterHit: 0,
      damage: 17,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.2,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/f", ["lk"]),
    move: move("d/f+3", "Knee", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 4,
      recovery: 14,
      onHit: 6,
      onBlock: -7,
      onCounterHit: 9,
      damage: 20,
      chipDamage: 2,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("u/f", ["lk"]),
    move: move("u/f+3", "Hopkick", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 18,
      active: 4,
      recovery: 24,
      onHit: 0,
      onBlock: -13,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.24,
      hasLowCrush: true,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("f", ["lp", "rp"]),
    move: move("f+1+2", "Power Crush", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      type: "special",
      startup: 20,
      active: 5,
      recovery: 20,
      onHit: 4,
      onBlock: -14,
      onCounterHit: 8,
      damage: 28,
      chipDamage: 4,
      isPowerCrush: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/f", ["rk"]),
    move: move("d/f+4", "Screw Kick", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 4,
      recovery: 16,
      onHit: 4,
      onBlock: -9,
      onCounterHit: 7,
      damage: 15,
      chipDamage: 2,
      isScrew: true,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },

  // ── LOW attacks ───────────────────────────────────────────────────────
  {
    input: cmd("d", ["lk"]),
    move: move("d+3", "Low Kick", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 3,
      recovery: 18,
      onHit: 2,
      onBlock: -13,
      onCounterHit: 5,
      damage: 12,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d", ["rk"]),
    move: move("d+4", "Ankle Kick", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 12,
      active: 2,
      recovery: 16,
      onHit: 0,
      onBlock: -11,
      onCounterHit: 3,
      damage: 10,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/b", ["lk"]),
    move: move("d/b+3", "Sweep", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      type: "command",
      startup: 20,
      active: 4,
      recovery: 24,
      onHit: 0,
      onBlock: -16,
      onCounterHit: 0,
      damage: 18,
      chipDamage: 2,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/b", ["rk"]),
    move: move("d/b+4", "Low Poke", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      startup: 14,
      active: 3,
      recovery: 14,
      onHit: 2,
      onBlock: -12,
      onCounterHit: 5,
      damage: 11,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// Character-specific signature moves
// ═══════════════════════════════════════════════════════════════════════════

// ── Knight (balanced) ─ Sir Aldric ─────────────────────────────────────────
const knightSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("f", ["rp"]),
    move: move("knight_sword_thrust", "Sword Thrust", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 12,
      onHit: 5,
      onBlock: -5,
      onCounterHit: 8,
      damage: 18,
      chipDamage: 2,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.3, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },
  {
    input: cmd("b", ["lp", "rp"]),
    move: move("knight_shield_bash", "Shield Bash", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 18,
      active: 4,
      recovery: 18,
      onHit: 6,
      onBlock: -10,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 3,
      isPowerCrush: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.4, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["lp"]),
    move: move("knight_cross_slash_1", "Cross Slash", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 12,
      active: 3,
      recovery: 10,
      onHit: 4,
      onBlock: 0,
      onCounterHit: 6,
      damage: 10,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/f", ["rp"]),
    move: move("knight_rising_blade", "Rising Blade", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 15,
      active: 3,
      recovery: 20,
      onHit: 0,
      onBlock: -11,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.25,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/b", ["rk"]),
    move: move("knight_sword_sweep", "Sword Sweep", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      type: "command",
      startup: 18,
      active: 4,
      recovery: 22,
      onHit: 0,
      onBlock: -15,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.65, h: 0.3, d: 0.4 },
    }),
  },
];

// ── Berserker (rushdown) ─ Bjorn Ironfist ──────────────────────────────────
const berserkerSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("f", ["rp"]),
    move: move("berserker_hammerfist", "Hammerfist", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 12,
      active: 3,
      recovery: 10,
      onHit: 5,
      onBlock: -3,
      onCounterHit: 8,
      damage: 16,
      chipDamage: 2,
      knockback: 0.25,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d", ["rp"]),
    move: move("berserker_skull_crusher", "Skull Crusher", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 13,
      active: 3,
      recovery: 12,
      onHit: 6,
      onBlock: -5,
      onCounterHit: 9,
      damage: 18,
      chipDamage: 2,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("f", ["lp"]),
    move: move("berserker_chain_1", "Berserker Chain", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 10,
      active: 2,
      recovery: 8,
      onHit: 4,
      onBlock: 1,
      onCounterHit: 6,
      damage: 8,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("f,f", ["lp", "rp"]),
    move: move("berserker_charging_bull", "Charging Bull", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 14,
      active: 5,
      recovery: 16,
      onHit: 7,
      onBlock: -8,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 3,
      knockback: 0.55,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.4, d: 0.4 },
      advanceDistance: 0.4,
    }),
  },
  {
    input: cmd("d/f", ["lp"]),
    move: move("berserker_gut_punch", "Gut Punch", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 11,
      active: 2,
      recovery: 10,
      onHit: 5,
      onBlock: -2,
      onCounterHit: 8,
      damage: 12,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
];

// ── Monk (mixup) ─ Brother Cedric ──────────────────────────────────────────
const monkSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("f", ["lp"]),
    move: move("monk_palm_strike", "Palm Strike", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 11,
      active: 2,
      recovery: 9,
      onHit: 4,
      onBlock: 0,
      onCounterHit: 7,
      damage: 12,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["rk"]),
    move: move("monk_crane_kick", "Crane Kick", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 4,
      recovery: 14,
      onHit: 5,
      onBlock: -6,
      onCounterHit: 9,
      damage: 18,
      chipDamage: 2,
      hasHighCrush: true,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.05,
    }),
  },
  {
    input: cmd("d/b", ["lk"]),
    move: move("monk_mantis_sweep", "Mantis Sweep", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 14,
      active: 3,
      recovery: 16,
      onHit: 3,
      onBlock: -13,
      onCounterHit: 6,
      damage: 14,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("u/f", ["rp"]),
    move: move("monk_sky_fist", "Sky Fist", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 17,
      active: 3,
      recovery: 22,
      onHit: 0,
      onBlock: -12,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.23,
      hasLowCrush: true,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["lp", "rp"]),
    move: move("monk_flowing_palm", "Flowing Palm", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 15,
      active: 4,
      recovery: 16,
      onHit: 6,
      onBlock: -7,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 3,
      wallSplat: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.4, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },
];

// ── Paladin (defensive) ─ Lady Isolde ──────────────────────────────────────
const paladinSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("b", ["lp", "rp"]),
    move: move("paladin_shield_wall", "Shield Wall", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 18,
      active: 4,
      recovery: 14,
      onHit: 4,
      onBlock: -4,
      onCounterHit: 8,
      damage: 20,
      chipDamage: 3,
      isPowerCrush: true,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.4, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("d/f", ["rp"]),
    move: move("paladin_divine_smite", "Divine Smite", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 16,
      active: 3,
      recovery: 20,
      onHit: 0,
      onBlock: -10,
      onCounterHit: 0,
      damage: 22,
      chipDamage: 3,
      isLauncher: true,
      launchHeight: 0.24,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["rp"]),
    move: move("paladin_holy_strike", "Holy Strike", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 12,
      onHit: 4,
      onBlock: -3,
      onCounterHit: 7,
      damage: 17,
      chipDamage: 2,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/b", ["lk"]),
    move: move("paladin_blessed_sweep", "Blessed Sweep", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 18,
      active: 3,
      recovery: 18,
      onHit: 2,
      onBlock: -14,
      onCounterHit: 5,
      damage: 14,
      chipDamage: 3,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.6, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("b", ["rp"]),
    move: move("paladin_radiant_counter", "Radiant Counter", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 14,
      onHit: 3,
      onBlock: -6,
      onCounterHit: 0,
      damage: 18,
      chipDamage: 2,
      isLauncher: false,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.05,
    }),
  },
];

// ── Assassin (evasive) ─ Shade ─────────────────────────────────────────────
const assassinSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("f", ["lp"]),
    move: move("assassin_shadow_stab", "Shadow Stab", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 10,
      active: 2,
      recovery: 8,
      onHit: 3,
      onBlock: 0,
      onCounterHit: 6,
      damage: 10,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/f", ["rk"]),
    move: move("assassin_venom_strike", "Venom Strike", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 3,
      recovery: 18,
      onHit: 3,
      onBlock: -14,
      onCounterHit: 0,
      damage: 16,
      chipDamage: 2,
      isLauncher: false,
      knockback: 0.25,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("b", ["rp"]),
    move: move("assassin_phantom_slash", "Phantom Slash", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 14,
      onHit: 5,
      onBlock: -5,
      onCounterHit: 9,
      damage: 17,
      chipDamage: 2,
      hasHighCrush: true,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["lk"]),
    move: move("assassin_smoke_bomb", "Smoke Bomb", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 15,
      active: 3,
      recovery: 12,
      onHit: 4,
      onBlock: -4,
      onCounterHit: 7,
      damage: 14,
      chipDamage: 1,
      hasHighCrush: true,
      knockback: 0.25,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: -0.1,
    }),
  },
  {
    input: cmd("u/f", ["rp"]),
    move: move("assassin_death_from_above", "Death From Above", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 16,
      active: 4,
      recovery: 22,
      onHit: 0,
      onBlock: -13,
      onCounterHit: 0,
      damage: 22,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.24,
      hasLowCrush: true,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },
];

// ── Warlord (power) ─ Gorm the Red ────────────────────────────────────────
const warlordSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("f", ["rp"]),
    move: move("warlord_axe_cleave", "Axe Cleave", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 18,
      active: 5,
      recovery: 18,
      onHit: 8,
      onBlock: -10,
      onCounterHit: 12,
      damage: 30,
      chipDamage: 4,
      knockback: 0.55,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d", ["lp", "rp"]),
    move: move("warlord_ground_pound", "Ground Pound", TekkenAttackHeight.LOW, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 22,
      active: 6,
      recovery: 24,
      onHit: 4,
      onBlock: -18,
      onCounterHit: 8,
      damage: 28,
      chipDamage: 4,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.7, h: 0.4, d: 0.5 },
    }),
  },
  {
    input: cmd("b", ["lp", "rp"]),
    move: move("warlord_war_cry", "War Cry", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 20,
      active: 5,
      recovery: 20,
      onHit: 6,
      onBlock: -12,
      onCounterHit: 10,
      damage: 28,
      chipDamage: 4,
      isPowerCrush: true,
      wallSplat: true,
      knockback: 0.6,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.5 },
      advanceDistance: 0.2,
    }),
  },
  {
    input: cmd("d/f", ["rp"]),
    move: move("warlord_execution_chop", "Execution Chop", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 20,
      active: 4,
      recovery: 24,
      onHit: 0,
      onBlock: -14,
      onCounterHit: 0,
      damage: 25,
      chipDamage: 3,
      isLauncher: true,
      launchHeight: 0.26,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/b", ["rk"]),
    move: move("warlord_leg_breaker", "Leg Breaker", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      type: "command",
      startup: 18,
      active: 4,
      recovery: 20,
      onHit: 3,
      onBlock: -15,
      onCounterHit: 6,
      damage: 25,
      chipDamage: 3,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.6, h: 0.3, d: 0.4 },
    }),
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// Combined move lists per character (universal + signature)
// ═══════════════════════════════════════════════════════════════════════════
export const KNIGHT_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...knightSignatureMoves];
export const BERSERKER_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...berserkerSignatureMoves];
export const MONK_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...monkSignatureMoves];
export const PALADIN_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...paladinSignatureMoves];
export const ASSASSIN_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...assassinSignatureMoves];
export const WARLORD_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...warlordSignatureMoves];
