export const TB = {
  // Sim
  TPS: 60,
  SIM_DT: 1 / 60,

  // Health
  MAX_HP: 170,
  RAGE_THRESHOLD: 0.25,
  RAGE_DAMAGE_BOOST: 1.15,

  // Movement
  WALK_SPEED: 0.035,
  BACK_WALK_SPEED: 0.028,
  DASH_SPEED: 0.08,
  DASH_DURATION: 12,
  BACKDASH_DIST: 0.6,
  BACKDASH_DURATION: 18,
  BACKDASH_INVULN: 6,
  CROUCH_TRANSITION: 4,
  SIDESTEP_SPEED: 0.04,
  SIDESTEP_DURATION: 16,

  // Gravity / Juggle
  GRAVITY: 0.012,
  JUGGLE_GRAVITY_SCALE_PER_HIT: 0.08,
  MAX_JUGGLE_HITS: 12,
  LAUNCH_VELOCITY: 0.22,
  SCREW_BONUS_HANG: 8,
  BOUND_BOUNCE_VEL: 0.12,
  WALL_SPLAT_DURATION: 30,
  WALL_SPLAT_SLIDE: 0.01,

  // Combo
  COMBO_DAMAGE_SCALING: 0.85,
  MIN_DAMAGE_SCALING: 0.2,
  COMBO_DROP_THRESHOLD: 3,

  // Blocking
  BLOCK_PUSHBACK: 0.02,
  CHIP_DAMAGE_MULT: 0.1,
  THROW_BREAK_WINDOW: 20,

  // Hitstun / Blockstun (base values, moves add to these)
  BASE_HITSTUN: 16,
  BASE_BLOCKSTUN: 12,
  COUNTER_HIT_BONUS: 6,
  COUNTER_HIT_WINDOW: 8,

  // Knockdown
  KNOCKDOWN_DURATION: 40,
  GET_UP_DURATION: 20,
  TECH_ROLL_SPEED: 0.04,
  TECH_ROLL_DURATION: 18,

  // Stage
  STAGE_HALF_WIDTH: 3.5,
  STAGE_HALF_DEPTH: 1.0,
  FLOOR_Y: 0,

  // Round
  ROUND_TIME: 60,
  ROUNDS_TO_WIN: 2,
  ROUND_START_DELAY: 90,
  ROUND_END_DELAY: 120,
  KO_SLOWDOWN_FRAMES: 60,
  KO_SLOWDOWN_SCALE: 0.3,

  // Camera
  CAMERA_BASE_Z: 5.5,
  CAMERA_Y: 1.4,
  CAMERA_LOOK_Y: 0.9,
  CAMERA_ZOOM_CLOSE: 4.0,
  CAMERA_ZOOM_FAR: 7.0,
  CAMERA_LERP: 0.06,
  CAMERA_SHAKE_LIGHT: 0.03,
  CAMERA_SHAKE_MEDIUM: 0.08,
  CAMERA_SHAKE_HEAVY: 0.15,
  CAMERA_SHAKE_DECAY: 0.88,

  // VFX
  HIT_FREEZE_LIGHT: 4,
  HIT_FREEZE_MEDIUM: 6,
  HIT_FREEZE_HEAVY: 8,
  HIT_FREEZE_LAUNCHER: 6,
  HIT_FREEZE_COUNTER: 10,
  SPARK_COUNT_LIGHT: 12,
  SPARK_COUNT_HEAVY: 25,

  // Rage Art Cinematic
  RAGE_ART_ZOOM_Z: 3.0,
  RAGE_ART_ZOOM_Y: 1.6,
  RAGE_ART_SLOWDOWN_SCALE: 0.2,
  RAGE_ART_ZOOM_IN_FRAMES: 15,
  RAGE_ART_IMPACT_FRAMES: 10,
  RAGE_ART_ZOOM_OUT_FRAMES: 20,

  // Intro Camera
  INTRO_ORBIT_FRAMES: 40,
  INTRO_EASE_FRAMES: 50,
  INTRO_ORBIT_RADIUS_START: 4,
  INTRO_ORBIT_RADIUS_END: 5.5,
  INTRO_ORBIT_Y_START: 1.8,
  INTRO_ORBIT_Y_END: 1.4,

  // KO Replay
  KO_ZOOM_AMOUNT: 0.4,
  KO_CAMERA_SHIFT: 0.6,

  // Combo Blend
  COMBO_BLEND_FAST_SPEED: 0.35,
  COMBO_BLEND_FAST_FRAMES: 4,

  // Dynamic Lighting
  TORCH_BASE_INTENSITY: 1.5,
  TORCH_COMBO_BOOST: 2.0,
  TORCH_BASE_DISTANCE: 8,
  TORCH_COMBO_DISTANCE_BOOST: 4,
  KEY_LIGHT_BASE_INTENSITY: 2.8,
  KEY_LIGHT_COMBO_BOOST: 0.5,
  COMBO_INTENSITY_DIVISOR: 8,
} as const;
