import type { TekkenMoveEntry, TekkenMoveDef, TekkenCommandInput } from "../state/TekkenState";
import { TekkenAttackHeight, TekkenLimb } from "../../types";

function move(
  id: string,
  name: string,
  height: TekkenAttackHeight,
  limb: TekkenLimb,
  opts: Partial<TekkenMoveDef> = {},
): TekkenMoveDef {
  return {
    id,
    name,
    type: "normal",
    height,
    limb,
    startup: 12,
    active: 3,
    recovery: 12,
    onHit: 0,
    onBlock: -4,
    onCounterHit: 4,
    damage: 15,
    chipDamage: 2,
    isLauncher: false,
    launchHeight: 0,
    isScrew: false,
    isBound: false,
    isHoming: false,
    isPowerCrush: false,
    hasHighCrush: false,
    hasLowCrush: false,
    knockback: 0.3,
    wallSplat: false,
    hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    advanceDistance: 0.1,
    ...opts,
  };
}

function cmd(direction: string, buttons: string[]): TekkenCommandInput[] {
  return [{ direction, buttons }];
}

export const UNIVERSAL_MOVES: TekkenMoveEntry[] = [
  // ── HIGH attacks ──────────────────────────────────────────────────────
  {
    input: cmd("n", ["lp"]),
    move: move("1", "Jab", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 10,
      active: 2,
      recovery: 8,
      onHit: 1,
      onBlock: 1,
      onCounterHit: 3,
      damage: 7,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["rp"]),
    move: move("2", "Straight", TekkenAttackHeight.HIGH, TekkenLimb.RIGHT_PUNCH, {
      startup: 12,
      active: 3,
      recovery: 10,
      onHit: 3,
      onBlock: -1,
      onCounterHit: 5,
      damage: 12,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["rk"]),
    move: move("4", "Roundhouse", TekkenAttackHeight.HIGH, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 4,
      recovery: 14,
      onHit: 7,
      onBlock: -6,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 3,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.75, h: 0.3, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },
  {
    input: cmd("n", ["lp", "lk"]),
    move: move("1+3", "Throw", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      type: "throw",
      startup: 12,
      active: 2,
      recovery: 30,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 35,
      chipDamage: 0,
      knockback: 0.6,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },

  // ── MID attacks ───────────────────────────────────────────────────────
  {
    input: cmd("d", ["lp"]),
    move: move("d+1", "Mid Jab", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 12,
      active: 2,
      recovery: 10,
      onHit: 2,
      onBlock: -2,
      onCounterHit: 4,
      damage: 10,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d", ["rp"]),
    move: move("d+2", "Uppercut", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 15,
      active: 3,
      recovery: 22,
      onHit: 0,
      onBlock: -13,
      onCounterHit: 0,
      damage: 18,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.22,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["lk"]),
    move: move("3", "Front Kick", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 14,
      active: 3,
      recovery: 12,
      onHit: 5,
      onBlock: -4,
      onCounterHit: 8,
      damage: 17,
      chipDamage: 2,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.3, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },
  {
    input: cmd("d/f", ["lp"]),
    move: move("d/f+1", "Mid Poke", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 13,
      active: 2,
      recovery: 10,
      onHit: 5,
      onBlock: -3,
      onCounterHit: 7,
      damage: 13,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/f", ["rp"]),
    move: move("d/f+2", "Mid Launcher", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 15,
      active: 3,
      recovery: 22,
      onHit: 0,
      onBlock: -12,
      onCounterHit: 0,
      damage: 17,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.2,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/f", ["lk"]),
    move: move("d/f+3", "Knee", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 4,
      recovery: 14,
      onHit: 6,
      onBlock: -7,
      onCounterHit: 9,
      damage: 20,
      chipDamage: 2,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("u/f", ["lk"]),
    move: move("u/f+3", "Hopkick", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 18,
      active: 4,
      recovery: 24,
      onHit: 0,
      onBlock: -13,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.24,
      hasLowCrush: true,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.3, d: 0.4 },
      advanceDistance: 0.25,
    }),
  },
  {
    input: cmd("f", ["lp", "rp"]),
    move: move("f+1+2", "Power Crush", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      type: "special",
      startup: 20,
      active: 5,
      recovery: 20,
      onHit: 4,
      onBlock: -14,
      onCounterHit: 8,
      damage: 28,
      chipDamage: 4,
      isPowerCrush: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.25,
    }),
  },
  {
    input: cmd("d/f", ["rk"]),
    move: move("d/f+4", "Screw Kick", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 4,
      recovery: 16,
      onHit: 4,
      onBlock: -9,
      onCounterHit: 7,
      damage: 15,
      chipDamage: 2,
      isScrew: true,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },

  // ── LOW attacks ───────────────────────────────────────────────────────
  {
    input: cmd("d", ["lk"]),
    move: move("d+3", "Low Kick", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 3,
      recovery: 18,
      onHit: 2,
      onBlock: -13,
      onCounterHit: 5,
      damage: 12,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.65, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d", ["rk"]),
    move: move("d+4", "Ankle Kick", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 12,
      active: 2,
      recovery: 16,
      onHit: 0,
      onBlock: -11,
      onCounterHit: 3,
      damage: 10,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/b", ["lk"]),
    move: move("d/b+3", "Sweep", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      type: "command",
      startup: 20,
      active: 4,
      recovery: 24,
      onHit: 0,
      onBlock: -16,
      onCounterHit: 0,
      damage: 18,
      chipDamage: 2,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.75, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/b", ["rk"]),
    move: move("d/b+4", "Low Poke", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      startup: 14,
      active: 3,
      recovery: 14,
      onHit: 2,
      onBlock: -12,
      onCounterHit: 5,
      damage: 11,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },

  // ── ADDITIONAL UNIVERSAL ATTACKS ────────────────────────────────────────

  // 1. Mid Kick (f+3) – advancing mid kick, good poke range
  {
    input: cmd("f", ["lk"]),
    move: move("f+3", "Advancing Mid Kick", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 15,
      active: 4,
      recovery: 14,
      onHit: 5,
      onBlock: -5,
      onCounterHit: 8,
      damage: 19,
      chipDamage: 2,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.3, d: 0.4 },
      advanceDistance: 0.25,
    }),
  },

  // 2. Spinning Back Kick (b+4) – high-crush spinning attack
  {
    input: cmd("b", ["rk"]),
    move: move("b+4", "Spinning Back Kick", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 17,
      active: 4,
      recovery: 16,
      onHit: 6,
      onBlock: -7,
      onCounterHit: 10,
      damage: 21,
      chipDamage: 2,
      isHoming: true,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.3, d: 0.5 },
      advanceDistance: 0.1,
    }),
  },

  // 3. Elbow Strike (f+2) – fast mid elbow, safe poke
  {
    input: cmd("f", ["rp"]),
    move: move("f+2", "Elbow Strike", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 13,
      active: 3,
      recovery: 11,
      onHit: 4,
      onBlock: -3,
      onCounterHit: 7,
      damage: 16,
      chipDamage: 2,
      knockback: 0.25,
      hitbox: { x: 0.3, y: 1.1, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },

  // 4. Jumping Elbow (u/f+2) – airborne elbow drop, low-crushes
  {
    input: cmd("u/f", ["rp"]),
    move: move("u/f+2", "Jumping Elbow Drop", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 20,
      active: 5,
      recovery: 22,
      onHit: 7,
      onBlock: -12,
      onCounterHit: 11,
      damage: 24,
      chipDamage: 3,
      hasLowCrush: true,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.4, d: 0.4 },
      advanceDistance: 0.3,
    }),
  },

  // 5. Knee Strike (f+4) – advancing knee, good wallsplat potential
  {
    input: cmd("f", ["rk"]),
    move: move("f+4", "Knee Strike", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 3,
      recovery: 14,
      onHit: 5,
      onBlock: -6,
      onCounterHit: 9,
      damage: 20,
      chipDamage: 2,
      knockback: 0.35,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.55, h: 0.35, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },

  // 6. Hellsweep (d/b+3,4) – sweeping low kick that launches on counter hit
  {
    input: cmd("d/b", ["lk", "rk"]),
    move: move("d/b+3+4", "Hellsweep", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      type: "command",
      startup: 22,
      active: 5,
      recovery: 26,
      onHit: 0,
      onBlock: -18,
      onCounterHit: 0,
      damage: 22,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.18,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.85, h: 0.3, d: 0.5 },
      advanceDistance: 0.15,
    }),
  },

  // 7. Grab Slam (f+1+3) – forward throw with knockdown
  {
    input: cmd("f", ["lp", "lk"]),
    move: move("f+1+3", "Grab Slam", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      type: "throw",
      startup: 14,
      active: 3,
      recovery: 32,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 38,
      chipDamage: 0,
      knockback: 0.55,
      wallSplat: true,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },

  // 8. Jumping Spinning Kick (u/f+4) – airborne spinning roundhouse
  {
    input: cmd("u/f", ["rk"]),
    move: move("u/f+4", "Jumping Spin Kick", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 19,
      active: 5,
      recovery: 24,
      onHit: 0,
      onBlock: -14,
      onCounterHit: 0,
      damage: 23,
      chipDamage: 3,
      isLauncher: true,
      launchHeight: 0.22,
      hasLowCrush: true,
      isHoming: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.75, h: 0.35, d: 0.5 },
      advanceDistance: 0.25,
    }),
  },

  // ── ADDITIONAL UNIVERSAL ATTACKS (SET 2) ──────────────────────────────────

  // 9. Back Fist (b+1) – retreating high punch, safe on block
  {
    input: cmd("b", ["lp"]),
    move: move("b+1", "Back Fist", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 10,
      onHit: 5,
      onBlock: -2,
      onCounterHit: 8,
      damage: 14,
      chipDamage: 1,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.55, h: 0.3, d: 0.4 },
      advanceDistance: -0.1,
    }),
  },

  // 10. Rising Uppercut (d/b+2) – crouching launcher, high risk high reward
  {
    input: cmd("d/b", ["rp"]),
    move: move("d/b+2", "Rising Uppercut", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 18,
      active: 4,
      recovery: 26,
      onHit: 0,
      onBlock: -16,
      onCounterHit: 0,
      damage: 22,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.26,
      hasHighCrush: true,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.4, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },

  // 11. Spinning Heel (b+3) – retreating mid kick with wallsplat
  {
    input: cmd("b", ["lk"]),
    move: move("b+3", "Spinning Heel", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 17,
      active: 4,
      recovery: 15,
      onHit: 6,
      onBlock: -8,
      onCounterHit: 10,
      damage: 19,
      chipDamage: 2,
      knockback: 0.4,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.3, d: 0.4 },
      advanceDistance: -0.05,
    }),
  },

  // 12. Gut Punch (d/f+1+2) – slow mid double-fist strike, big damage
  {
    input: cmd("d/f", ["lp", "rp"]),
    move: move("d/f+1+2", "Gut Punch", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      type: "command",
      startup: 22,
      active: 4,
      recovery: 20,
      onHit: 8,
      onBlock: -12,
      onCounterHit: 12,
      damage: 28,
      chipDamage: 4,
      knockback: 0.5,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.55, h: 0.35, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },

  // 13. Slide Kick (d/f+3+4) – low sliding tackle, knockdown on hit
  {
    input: cmd("d/f", ["lk", "rk"]),
    move: move("d/f+3+4", "Slide Kick", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      type: "command",
      startup: 24,
      active: 6,
      recovery: 28,
      onHit: 0,
      onBlock: -20,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      knockback: 0.55,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.9, h: 0.3, d: 0.5 },
      advanceDistance: 0.4,
    }),
  },

  // 14. Palm Strike (f+1) – fast advancing mid palm, good pressure tool
  {
    input: cmd("f", ["lp"]),
    move: move("f+1", "Palm Strike", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 13,
      active: 3,
      recovery: 11,
      onHit: 4,
      onBlock: -3,
      onCounterHit: 7,
      damage: 14,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 1.0, z: 0, w: 0.55, h: 0.3, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },

  // 15. Axe Kick (u/f+3+4) – jumping overhead stomp, ground bounce on hit
  {
    input: cmd("u/f", ["lk", "rk"]),
    move: move("u/f+3+4", "Axe Kick", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 24,
      active: 5,
      recovery: 26,
      onHit: 0,
      onBlock: -15,
      onCounterHit: 0,
      damage: 26,
      chipDamage: 3,
      isBound: true,
      hasLowCrush: true,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.4, d: 0.4 },
      advanceDistance: 0.3,
    }),
  },

  // 16. Backhand Slap (b+2) – high evasive counter poke, high crushes
  {
    input: cmd("b", ["rp"]),
    move: move("b+2", "Backhand Slap", TekkenAttackHeight.HIGH, TekkenLimb.RIGHT_PUNCH, {
      startup: 15,
      active: 3,
      recovery: 12,
      onHit: 6,
      onBlock: -4,
      onCounterHit: 11,
      damage: 16,
      chipDamage: 2,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.6, h: 0.3, d: 0.4 },
      advanceDistance: -0.05,
    }),
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// Character-specific signature moves
// ═══════════════════════════════════════════════════════════════════════════

// ── Knight (balanced) ─ Sir Aldric ─────────────────────────────────────────
const knightSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("f", ["rp"]),
    move: move("knight_sword_thrust", "Sword Thrust", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 12,
      onHit: 5,
      onBlock: -5,
      onCounterHit: 8,
      damage: 18,
      chipDamage: 2,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.9, h: 0.3, d: 0.4 },
      advanceDistance: 0.3,
    }),
  },
  {
    input: cmd("b", ["lp", "rp"]),
    move: move("knight_shield_bash", "Shield Bash", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 18,
      active: 4,
      recovery: 18,
      onHit: 6,
      onBlock: -10,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 3,
      isPowerCrush: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.4, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["lp"]),
    move: move("knight_cross_slash_1", "Cross Slash", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 12,
      active: 3,
      recovery: 10,
      onHit: 4,
      onBlock: 0,
      onCounterHit: 6,
      damage: 10,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/f", ["rp"]),
    move: move("knight_rising_blade", "Rising Blade", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 15,
      active: 3,
      recovery: 20,
      onHit: 0,
      onBlock: -11,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.25,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/b", ["rk"]),
    move: move("knight_sword_sweep", "Sword Sweep", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      type: "command",
      startup: 18,
      active: 4,
      recovery: 22,
      onHit: 0,
      onBlock: -15,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.85, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  // ── New Knight moves ──
  {
    input: cmd("u/f", ["rp"]),
    move: move("knight_sky_cleave", "Sky Cleave", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 20,
      active: 4,
      recovery: 26,
      onHit: 0,
      onBlock: -15,
      onCounterHit: 0,
      damage: 24,
      chipDamage: 3,
      isLauncher: true,
      launchHeight: 0.28,
      hasLowCrush: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.4 },
      advanceDistance: 0.25,
    }),
  },
  {
    input: cmd("f,f", ["rp"]),
    move: move("knight_power_thrust", "Power Thrust", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 22,
      active: 5,
      recovery: 20,
      onHit: 8,
      onBlock: -12,
      onCounterHit: 12,
      damage: 32,
      chipDamage: 4,
      knockback: 0.55,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.95, h: 0.35, d: 0.4 },
      advanceDistance: 0.5,
    }),
  },
  {
    input: cmd("f,f", ["lk"]),
    move: move("knight_running_slash", "Running Slash", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 4,
      recovery: 14,
      onHit: 6,
      onBlock: -6,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 2,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.85, h: 0.3, d: 0.4 },
      advanceDistance: 0.5,
    }),
  },
  {
    input: cmd("b", ["rk"]),
    move: move("knight_evasive_backslash", "Evasive Backslash", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 17,
      active: 3,
      recovery: 16,
      onHit: 5,
      onBlock: -7,
      onCounterHit: 9,
      damage: 19,
      chipDamage: 2,
      hasHighCrush: true,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.3, d: 0.4 },
      advanceDistance: -0.15,
    }),
  },
  {
    input: cmd("d/b", ["lp", "rp"]),
    move: move("knight_shield_grab", "Shield Grab", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      type: "throw",
      startup: 14,
      active: 3,
      recovery: 32,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 40,
      chipDamage: 0,
      knockback: 0.5,
      wallSplat: true,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("d", ["rk"]),
    move: move("knight_low_pommel", "Low Pommel Strike", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      startup: 14,
      active: 2,
      recovery: 14,
      onHit: 2,
      onBlock: -12,
      onCounterHit: 5,
      damage: 12,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.55, h: 0.3, d: 0.4 },
      advanceDistance: 0.05,
    }),
  },
  {
    input: cmd("d/b", ["lk"]),
    move: move("knight_hellsweep_blade", "Hellsweep Blade", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      type: "command",
      startup: 22,
      active: 4,
      recovery: 26,
      onHit: 0,
      onBlock: -18,
      onCounterHit: 0,
      damage: 22,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.18,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.8, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["rk"]),
    move: move("knight_counter_slash", "Counter Slash", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 14,
      active: 3,
      recovery: 12,
      onHit: 3,
      onBlock: -3,
      onCounterHit: 0,
      damage: 16,
      chipDamage: 2,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["lk"]),
    move: move("knight_double_slash_1", "Double Slash", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_KICK, {
      startup: 12,
      active: 2,
      recovery: 8,
      onHit: 5,
      onBlock: 1,
      onCounterHit: 7,
      damage: 8,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.6, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["lp"]),
    move: move("knight_unblockable_impale", "Unblockable Impale", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 40,
      active: 5,
      recovery: 30,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 55,
      chipDamage: 55,
      knockback: 0.7,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.9, h: 0.4, d: 0.4 },
      advanceDistance: 0.3,
    }),
  },
];

// ── Berserker (rushdown) ─ Bjorn Ironfist ──────────────────────────────────
const berserkerSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("f", ["rp"]),
    move: move("berserker_hammerfist", "Hammerfist", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 12,
      active: 3,
      recovery: 10,
      onHit: 5,
      onBlock: -3,
      onCounterHit: 8,
      damage: 16,
      chipDamage: 2,
      knockback: 0.25,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d", ["rp"]),
    move: move("berserker_skull_crusher", "Skull Crusher", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 13,
      active: 3,
      recovery: 12,
      onHit: 6,
      onBlock: -5,
      onCounterHit: 9,
      damage: 18,
      chipDamage: 2,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("f", ["lp"]),
    move: move("berserker_chain_1", "Berserker Chain", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 10,
      active: 2,
      recovery: 8,
      onHit: 4,
      onBlock: 1,
      onCounterHit: 6,
      damage: 8,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("f,f", ["lp", "rp"]),
    move: move("berserker_charging_bull", "Charging Bull", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 14,
      active: 5,
      recovery: 16,
      onHit: 7,
      onBlock: -8,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 3,
      knockback: 0.55,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.4 },
      advanceDistance: 0.55,
    }),
  },
  {
    input: cmd("d/f", ["lp"]),
    move: move("berserker_gut_punch", "Gut Punch", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 11,
      active: 2,
      recovery: 10,
      onHit: 5,
      onBlock: -2,
      onCounterHit: 8,
      damage: 12,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  // ── New Berserker moves ──
  {
    input: cmd("u/f", ["rp"]),
    move: move("berserker_leaping_smash", "Leaping Smash", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 19,
      active: 5,
      recovery: 24,
      onHit: 0,
      onBlock: -14,
      onCounterHit: 0,
      damage: 26,
      chipDamage: 3,
      isLauncher: true,
      launchHeight: 0.26,
      hasLowCrush: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.4, d: 0.4 },
      advanceDistance: 0.35,
    }),
  },
  {
    input: cmd("f", ["lp", "rp"]),
    move: move("berserker_power_haymaker", "Power Haymaker", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 24,
      active: 5,
      recovery: 22,
      onHit: 10,
      onBlock: -14,
      onCounterHit: 14,
      damage: 35,
      chipDamage: 5,
      knockback: 0.6,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.4 },
      advanceDistance: 0.25,
    }),
  },
  {
    input: cmd("f,f", ["rk"]),
    move: move("berserker_running_tackle", "Running Tackle", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 15,
      active: 5,
      recovery: 16,
      onHit: 7,
      onBlock: -8,
      onCounterHit: 11,
      damage: 24,
      chipDamage: 3,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.5 },
      advanceDistance: 0.6,
    }),
  },
  {
    input: cmd("b", ["lk"]),
    move: move("berserker_sidestep_elbow", "Sidestep Elbow", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 3,
      recovery: 14,
      onHit: 5,
      onBlock: -5,
      onCounterHit: 9,
      damage: 18,
      chipDamage: 2,
      hasHighCrush: true,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.55, h: 0.3, d: 0.4 },
      advanceDistance: -0.1,
    }),
  },
  {
    input: cmd("d/b", ["lp", "rp"]),
    move: move("berserker_bear_grab", "Bear Grab", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      type: "throw",
      startup: 13,
      active: 3,
      recovery: 34,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 42,
      chipDamage: 0,
      knockback: 0.55,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("d", ["lk"]),
    move: move("berserker_shin_kick", "Shin Kick", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 13,
      active: 2,
      recovery: 14,
      onHit: 2,
      onBlock: -11,
      onCounterHit: 5,
      damage: 11,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.05,
    }),
  },
  {
    input: cmd("d/b", ["lk"]),
    move: move("berserker_hellsweep_axe", "Hellsweep Axe", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      type: "command",
      startup: 20,
      active: 4,
      recovery: 26,
      onHit: 0,
      onBlock: -18,
      onCounterHit: 0,
      damage: 24,
      chipDamage: 3,
      isLauncher: true,
      launchHeight: 0.2,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.75, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["rk"]),
    move: move("berserker_headbutt", "Headbutt", TekkenAttackHeight.HIGH, TekkenLimb.RIGHT_KICK, {
      startup: 13,
      active: 3,
      recovery: 12,
      onHit: 4,
      onBlock: -2,
      onCounterHit: 0,
      damage: 18,
      chipDamage: 2,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.35, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("b", ["rp"]),
    move: move("berserker_wild_swing_1", "Wild Swing", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 4,
      recovery: 10,
      onHit: 6,
      onBlock: 0,
      onCounterHit: 9,
      damage: 12,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("b", ["lp"]),
    move: move("berserker_unblockable_rage", "Unblockable Rage Slam", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 42,
      active: 6,
      recovery: 30,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 60,
      chipDamage: 60,
      knockback: 0.8,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.8, h: 0.5, d: 0.5 },
      advanceDistance: 0.2,
    }),
  },
];

// ── Monk (mixup) ─ Brother Cedric ──────────────────────────────────────────
const monkSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("f", ["lp"]),
    move: move("monk_palm_strike", "Palm Strike", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 11,
      active: 2,
      recovery: 9,
      onHit: 4,
      onBlock: 0,
      onCounterHit: 7,
      damage: 12,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["rk"]),
    move: move("monk_crane_kick", "Crane Kick", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 4,
      recovery: 14,
      onHit: 5,
      onBlock: -6,
      onCounterHit: 9,
      damage: 18,
      chipDamage: 2,
      hasHighCrush: true,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/b", ["lk"]),
    move: move("monk_mantis_sweep", "Mantis Sweep", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 14,
      active: 3,
      recovery: 16,
      onHit: 3,
      onBlock: -13,
      onCounterHit: 6,
      damage: 14,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.7, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("u/f", ["rp"]),
    move: move("monk_sky_fist", "Sky Fist", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 17,
      active: 3,
      recovery: 22,
      onHit: 0,
      onBlock: -12,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.23,
      hasLowCrush: true,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["lp", "rp"]),
    move: move("monk_flowing_palm", "Flowing Palm", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 15,
      active: 4,
      recovery: 16,
      onHit: 6,
      onBlock: -7,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 3,
      wallSplat: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.4, d: 0.4 },
      advanceDistance: 0.3,
    }),
  },
  // ── New Monk moves ──
  {
    input: cmd("d/f", ["rp"]),
    move: move("monk_dragon_uppercut", "Dragon Uppercut", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 16,
      active: 3,
      recovery: 24,
      onHit: 0,
      onBlock: -14,
      onCounterHit: 0,
      damage: 22,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.26,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.55, h: 0.35, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("b", ["lp", "rp"]),
    move: move("monk_iron_palm", "Iron Palm", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 22,
      active: 4,
      recovery: 18,
      onHit: 8,
      onBlock: -10,
      onCounterHit: 12,
      damage: 30,
      chipDamage: 4,
      knockback: 0.5,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.4, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },
  {
    input: cmd("f,f", ["lk"]),
    move: move("monk_flying_kick", "Flying Kick", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 15,
      active: 4,
      recovery: 16,
      onHit: 6,
      onBlock: -7,
      onCounterHit: 10,
      damage: 20,
      chipDamage: 2,
      hasLowCrush: true,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.75, h: 0.3, d: 0.4 },
      advanceDistance: 0.55,
    }),
  },
  {
    input: cmd("b", ["lk"]),
    move: move("monk_spinning_dodge", "Spinning Dodge Strike", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 3,
      recovery: 14,
      onHit: 4,
      onBlock: -4,
      onCounterHit: 8,
      damage: 16,
      chipDamage: 2,
      hasHighCrush: true,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.3, d: 0.4 },
      advanceDistance: -0.1,
    }),
  },
  {
    input: cmd("d/b", ["lp", "rp"]),
    move: move("monk_joint_lock", "Joint Lock", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      type: "throw",
      startup: 14,
      active: 2,
      recovery: 30,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 38,
      chipDamage: 0,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.05,
    }),
  },
  {
    input: cmd("d", ["lk"]),
    move: move("monk_ankle_snap", "Ankle Snap", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 13,
      active: 2,
      recovery: 14,
      onHit: 3,
      onBlock: -12,
      onCounterHit: 6,
      damage: 11,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.55, h: 0.3, d: 0.4 },
      advanceDistance: 0.05,
    }),
  },
  {
    input: cmd("d/b", ["rk"]),
    move: move("monk_hellsweep_spin", "Hellsweep Spin Kick", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      type: "command",
      startup: 21,
      active: 4,
      recovery: 26,
      onHit: 0,
      onBlock: -17,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.18,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.75, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("f", ["rp"]),
    move: move("monk_tiger_palm", "Tiger Palm", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 12,
      onHit: 4,
      onBlock: -2,
      onCounterHit: 0,
      damage: 17,
      chipDamage: 2,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.55, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["rk"]),
    move: move("monk_stance_combo_1", "Rapid Fist Combo", TekkenAttackHeight.HIGH, TekkenLimb.RIGHT_KICK, {
      startup: 11,
      active: 2,
      recovery: 8,
      onHit: 5,
      onBlock: 1,
      onCounterHit: 7,
      damage: 7,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["lp"]),
    move: move("monk_unblockable_spirit", "Unblockable Spirit Blast", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 38,
      active: 5,
      recovery: 28,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 50,
      chipDamage: 50,
      knockback: 0.7,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.5 },
      advanceDistance: 0.25,
    }),
  },
];

// ── Paladin (defensive) ─ Lady Isolde ──────────────────────────────────────
const paladinSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("b", ["lp", "rp"]),
    move: move("paladin_shield_wall", "Shield Wall", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 18,
      active: 4,
      recovery: 14,
      onHit: 4,
      onBlock: -4,
      onCounterHit: 8,
      damage: 20,
      chipDamage: 3,
      isPowerCrush: true,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.4, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("d/f", ["rp"]),
    move: move("paladin_divine_smite", "Divine Smite", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 16,
      active: 3,
      recovery: 20,
      onHit: 0,
      onBlock: -10,
      onCounterHit: 0,
      damage: 22,
      chipDamage: 3,
      isLauncher: true,
      launchHeight: 0.24,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["rp"]),
    move: move("paladin_holy_strike", "Holy Strike", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 12,
      onHit: 4,
      onBlock: -3,
      onCounterHit: 7,
      damage: 17,
      chipDamage: 2,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/b", ["lk"]),
    move: move("paladin_blessed_sweep", "Blessed Sweep", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 18,
      active: 3,
      recovery: 18,
      onHit: 2,
      onBlock: -14,
      onCounterHit: 5,
      damage: 14,
      chipDamage: 3,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.8, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["rp"]),
    move: move("paladin_radiant_counter", "Radiant Counter", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 14,
      onHit: 3,
      onBlock: -6,
      onCounterHit: 0,
      damage: 18,
      chipDamage: 2,
      isLauncher: false,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.05,
    }),
  },
  // ── New Paladin moves ──
  {
    input: cmd("u/f", ["rp"]),
    move: move("paladin_heavens_strike", "Heaven's Strike", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 19,
      active: 4,
      recovery: 24,
      onHit: 0,
      onBlock: -14,
      onCounterHit: 0,
      damage: 24,
      chipDamage: 3,
      isLauncher: true,
      launchHeight: 0.27,
      hasLowCrush: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.4, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },
  {
    input: cmd("f", ["lp", "rp"]),
    move: move("paladin_sanctified_slam", "Sanctified Slam", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 24,
      active: 5,
      recovery: 22,
      onHit: 10,
      onBlock: -14,
      onCounterHit: 14,
      damage: 34,
      chipDamage: 5,
      isPowerCrush: true,
      knockback: 0.6,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.45, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },
  {
    input: cmd("f,f", ["rp"]),
    move: move("paladin_charging_shield", "Charging Shield Ram", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 16,
      active: 4,
      recovery: 14,
      onHit: 6,
      onBlock: -6,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 3,
      isPowerCrush: true,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.4 },
      advanceDistance: 0.5,
    }),
  },
  {
    input: cmd("b", ["lk"]),
    move: move("paladin_evasive_shield", "Evasive Shield Swipe", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 3,
      recovery: 14,
      onHit: 4,
      onBlock: -4,
      onCounterHit: 8,
      damage: 16,
      chipDamage: 2,
      hasHighCrush: true,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.3, d: 0.4 },
      advanceDistance: -0.15,
    }),
  },
  {
    input: cmd("d/b", ["lp", "rp"]),
    move: move("paladin_holy_bind", "Holy Bind", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      type: "throw",
      startup: 14,
      active: 3,
      recovery: 32,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 38,
      chipDamage: 0,
      knockback: 0.45,
      wallSplat: true,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("d", ["rk"]),
    move: move("paladin_low_shield_poke", "Low Shield Poke", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      startup: 14,
      active: 2,
      recovery: 14,
      onHit: 2,
      onBlock: -12,
      onCounterHit: 5,
      damage: 11,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.55, h: 0.3, d: 0.4 },
      advanceDistance: 0.05,
    }),
  },
  {
    input: cmd("d/b", ["rk"]),
    move: move("paladin_hellsweep_light", "Hellsweep of Light", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      type: "command",
      startup: 22,
      active: 4,
      recovery: 26,
      onHit: 0,
      onBlock: -18,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.18,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.8, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["lp"]),
    move: move("paladin_counter_thrust", "Counter Thrust", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 13,
      active: 3,
      recovery: 12,
      onHit: 3,
      onBlock: -2,
      onCounterHit: 0,
      damage: 16,
      chipDamage: 2,
      knockback: 0.3,
      isScrew: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["rk"]),
    move: move("paladin_judgment_combo_1", "Judgment Combo", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 12,
      active: 3,
      recovery: 10,
      onHit: 5,
      onBlock: 0,
      onCounterHit: 8,
      damage: 10,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["lp"]),
    move: move("paladin_unblockable_smite", "Unblockable Divine Smite", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 40,
      active: 5,
      recovery: 30,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 52,
      chipDamage: 52,
      knockback: 0.7,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.75, h: 0.4, d: 0.5 },
      advanceDistance: 0.25,
    }),
  },
];

// ── Assassin (evasive) ─ Shade ─────────────────────────────────────────────
const assassinSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("f", ["lp"]),
    move: move("assassin_shadow_stab", "Shadow Stab", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 10,
      active: 2,
      recovery: 8,
      onHit: 3,
      onBlock: 0,
      onCounterHit: 6,
      damage: 10,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/f", ["rk"]),
    move: move("assassin_venom_strike", "Venom Strike", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 3,
      recovery: 18,
      onHit: 3,
      onBlock: -14,
      onCounterHit: 0,
      damage: 16,
      chipDamage: 2,
      isLauncher: false,
      knockback: 0.25,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["rp"]),
    move: move("assassin_phantom_slash", "Phantom Slash", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 14,
      onHit: 5,
      onBlock: -5,
      onCounterHit: 9,
      damage: 17,
      chipDamage: 2,
      hasHighCrush: true,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["lk"]),
    move: move("assassin_smoke_bomb", "Smoke Bomb", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 15,
      active: 3,
      recovery: 12,
      onHit: 4,
      onBlock: -4,
      onCounterHit: 7,
      damage: 14,
      chipDamage: 1,
      hasHighCrush: true,
      knockback: 0.25,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: -0.1,
    }),
  },
  {
    input: cmd("u/f", ["rp"]),
    move: move("assassin_death_from_above", "Death From Above", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 16,
      active: 4,
      recovery: 22,
      onHit: 0,
      onBlock: -13,
      onCounterHit: 0,
      damage: 22,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.24,
      hasLowCrush: true,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: 0.3,
    }),
  },
  // ── New Assassin moves ──
  {
    input: cmd("d/f", ["rp"]),
    move: move("assassin_rising_dagger", "Rising Dagger", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 14,
      active: 3,
      recovery: 22,
      onHit: 0,
      onBlock: -12,
      onCounterHit: 0,
      damage: 19,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.22,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["lp", "rp"]),
    move: move("assassin_poison_impale", "Poison Impale", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 20,
      active: 4,
      recovery: 18,
      onHit: 8,
      onBlock: -10,
      onCounterHit: 12,
      damage: 28,
      chipDamage: 4,
      knockback: 0.4,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.55, h: 0.3, d: 0.4 },
      advanceDistance: 0.2,
    }),
  },
  {
    input: cmd("f,f", ["lk"]),
    move: move("assassin_running_slide", "Running Slide", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 14,
      active: 4,
      recovery: 18,
      onHit: 4,
      onBlock: -14,
      onCounterHit: 8,
      damage: 18,
      chipDamage: 2,
      hasHighCrush: true,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.8, h: 0.3, d: 0.4 },
      advanceDistance: 0.55,
    }),
  },
  {
    input: cmd("b", ["rk"]),
    move: move("assassin_backstep_flip", "Backstep Flip Kick", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 17,
      active: 4,
      recovery: 16,
      onHit: 5,
      onBlock: -6,
      onCounterHit: 9,
      damage: 20,
      chipDamage: 2,
      hasHighCrush: true,
      hasLowCrush: true,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.3, d: 0.4 },
      advanceDistance: -0.2,
    }),
  },
  {
    input: cmd("d/b", ["lp", "rp"]),
    move: move("assassin_chokehold", "Chokehold", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      type: "throw",
      startup: 12,
      active: 2,
      recovery: 28,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 40,
      chipDamage: 0,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("d", ["lk"]),
    move: move("assassin_low_stab", "Low Stab", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 12,
      active: 2,
      recovery: 12,
      onHit: 3,
      onBlock: -10,
      onCounterHit: 6,
      damage: 10,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("d/b", ["rk"]),
    move: move("assassin_hellsweep_blade", "Hellsweep Blade", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      type: "command",
      startup: 18,
      active: 3,
      recovery: 24,
      onHit: 0,
      onBlock: -16,
      onCounterHit: 0,
      damage: 18,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.18,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.7, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["rp"]),
    move: move("assassin_counter_elbow", "Counter Elbow", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 13,
      active: 3,
      recovery: 11,
      onHit: 4,
      onBlock: -1,
      onCounterHit: 0,
      damage: 15,
      chipDamage: 2,
      isScrew: true,
      knockback: 0.25,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["rk"]),
    move: move("assassin_triple_slash_1", "Triple Slash", TekkenAttackHeight.HIGH, TekkenLimb.RIGHT_KICK, {
      startup: 10,
      active: 2,
      recovery: 7,
      onHit: 5,
      onBlock: 2,
      onCounterHit: 7,
      damage: 6,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["lp"]),
    move: move("assassin_unblockable_execute", "Unblockable Execution", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 36,
      active: 4,
      recovery: 28,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 48,
      chipDamage: 48,
      knockback: 0.6,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.6, h: 0.3, d: 0.4 },
      advanceDistance: 0.3,
    }),
  },
];

// ── Warlord (power) ─ Gorm the Red ────────────────────────────────────────
const warlordSignatureMoves: TekkenMoveEntry[] = [
  {
    input: cmd("f", ["rp"]),
    move: move("warlord_axe_cleave", "Axe Cleave", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 18,
      active: 5,
      recovery: 18,
      onHit: 8,
      onBlock: -10,
      onCounterHit: 12,
      damage: 30,
      chipDamage: 4,
      knockback: 0.55,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d", ["lp", "rp"]),
    move: move("warlord_ground_pound", "Ground Pound", TekkenAttackHeight.LOW, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 22,
      active: 6,
      recovery: 24,
      onHit: 4,
      onBlock: -18,
      onCounterHit: 8,
      damage: 28,
      chipDamage: 4,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.85, h: 0.4, d: 0.5 },
    }),
  },
  {
    input: cmd("b", ["lp", "rp"]),
    move: move("warlord_war_cry", "War Cry", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 20,
      active: 5,
      recovery: 20,
      onHit: 6,
      onBlock: -12,
      onCounterHit: 10,
      damage: 28,
      chipDamage: 4,
      isPowerCrush: true,
      wallSplat: true,
      knockback: 0.6,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.5 },
      advanceDistance: 0.2,
    }),
  },
  {
    input: cmd("d/f", ["rp"]),
    move: move("warlord_execution_chop", "Execution Chop", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 20,
      active: 4,
      recovery: 24,
      onHit: 0,
      onBlock: -14,
      onCounterHit: 0,
      damage: 25,
      chipDamage: 3,
      isLauncher: true,
      launchHeight: 0.26,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("d/b", ["rk"]),
    move: move("warlord_leg_breaker", "Leg Breaker", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      type: "command",
      startup: 18,
      active: 4,
      recovery: 20,
      onHit: 3,
      onBlock: -15,
      onCounterHit: 6,
      damage: 25,
      chipDamage: 3,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.75, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  // ── New Warlord moves ──
  {
    input: cmd("u/f", ["rp"]),
    move: move("warlord_meteor_drop", "Meteor Drop", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 22,
      active: 6,
      recovery: 28,
      onHit: 0,
      onBlock: -16,
      onCounterHit: 0,
      damage: 30,
      chipDamage: 4,
      isLauncher: true,
      launchHeight: 0.3,
      hasLowCrush: true,
      knockback: 0.6,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.8, h: 0.5, d: 0.5 },
      advanceDistance: 0.3,
    }),
  },
  {
    input: cmd("f", ["lp", "rp"]),
    move: move("warlord_devastator", "Devastator", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 26,
      active: 6,
      recovery: 24,
      onHit: 12,
      onBlock: -16,
      onCounterHit: 16,
      damage: 40,
      chipDamage: 6,
      isPowerCrush: true,
      knockback: 0.7,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.85, h: 0.5, d: 0.5 },
      advanceDistance: 0.25,
    }),
  },
  {
    input: cmd("f,f", ["rk"]),
    move: move("warlord_charging_stomp", "Charging Stomp", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 18,
      active: 5,
      recovery: 18,
      onHit: 8,
      onBlock: -10,
      onCounterHit: 12,
      damage: 26,
      chipDamage: 3,
      isBound: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.75, h: 0.4, d: 0.5 },
      advanceDistance: 0.55,
    }),
  },
  {
    input: cmd("b", ["lk"]),
    move: move("warlord_sidestep_slam", "Sidestep Slam", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 18,
      active: 4,
      recovery: 16,
      onHit: 6,
      onBlock: -8,
      onCounterHit: 10,
      damage: 24,
      chipDamage: 3,
      hasHighCrush: true,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.7, h: 0.4, d: 0.4 },
      advanceDistance: -0.1,
    }),
  },
  {
    input: cmd("d/b", ["lp", "rp"]),
    move: move("warlord_spine_breaker", "Spine Breaker", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      type: "throw",
      startup: 14,
      active: 3,
      recovery: 36,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 45,
      chipDamage: 0,
      knockback: 0.6,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("d", ["lk"]),
    move: move("warlord_boot_stomp", "Boot Stomp", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 3,
      recovery: 16,
      onHit: 3,
      onBlock: -13,
      onCounterHit: 6,
      damage: 16,
      chipDamage: 2,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.6, h: 0.35, d: 0.4 },
      advanceDistance: 0.05,
    }),
  },
  {
    input: cmd("d/b", ["lk"]),
    move: move("warlord_hellsweep_quake", "Hellsweep Quake", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      type: "command",
      startup: 24,
      active: 5,
      recovery: 28,
      onHit: 0,
      onBlock: -20,
      onCounterHit: 0,
      damage: 28,
      chipDamage: 4,
      isLauncher: true,
      launchHeight: 0.22,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.9, h: 0.4, d: 0.5 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["lp"]),
    move: move("warlord_armor_check", "Armor Check", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 15,
      active: 4,
      recovery: 14,
      onHit: 4,
      onBlock: -3,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 3,
      isPowerCrush: true,
      knockback: 0.35,
      isScrew: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.4, d: 0.4 },
      advanceDistance: 0.15,
    }),
  },
  {
    input: cmd("f", ["rk"]),
    move: move("warlord_double_axe_1", "Double Axe Handle", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 14,
      active: 4,
      recovery: 12,
      onHit: 6,
      onBlock: -1,
      onCounterHit: 10,
      damage: 14,
      chipDamage: 2,
      knockback: 0.25,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.65, h: 0.35, d: 0.4 },
      advanceDistance: 0.1,
    }),
  },
  {
    input: cmd("b", ["lp"]),
    move: move("warlord_unblockable_megaton", "Unblockable Megaton Punch", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      type: "special",
      startup: 45,
      active: 6,
      recovery: 32,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 65,
      chipDamage: 65,
      knockback: 0.9,
      wallSplat: true,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.9, h: 0.5, d: 0.5 },
      advanceDistance: 0.3,
    }),
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// Combined move lists per character (universal + signature)
// ═══════════════════════════════════════════════════════════════════════════
export const KNIGHT_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...knightSignatureMoves];
export const BERSERKER_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...berserkerSignatureMoves];
export const MONK_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...monkSignatureMoves];
export const PALADIN_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...paladinSignatureMoves];
export const ASSASSIN_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...assassinSignatureMoves];
export const WARLORD_MOVES: TekkenMoveEntry[] = [...UNIVERSAL_MOVES, ...warlordSignatureMoves];
