import type { TekkenMoveEntry, TekkenMoveDef, TekkenCommandInput } from "../state/TekkenState";
import { TekkenAttackHeight, TekkenLimb } from "../../types";

function move(
  id: string,
  name: string,
  height: TekkenAttackHeight,
  limb: TekkenLimb,
  opts: Partial<TekkenMoveDef> = {},
): TekkenMoveDef {
  return {
    id,
    name,
    type: "normal",
    height,
    limb,
    startup: 12,
    active: 3,
    recovery: 12,
    onHit: 0,
    onBlock: -4,
    onCounterHit: 4,
    damage: 15,
    chipDamage: 2,
    isLauncher: false,
    launchHeight: 0,
    isScrew: false,
    isBound: false,
    isHoming: false,
    isPowerCrush: false,
    hasHighCrush: false,
    hasLowCrush: false,
    knockback: 0.3,
    wallSplat: false,
    hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    advanceDistance: 0.1,
    ...opts,
  };
}

function cmd(direction: string, buttons: string[]): TekkenCommandInput[] {
  return [{ direction, buttons }];
}

export const UNIVERSAL_MOVES: TekkenMoveEntry[] = [
  // ── HIGH attacks ──────────────────────────────────────────────────────
  {
    input: cmd("n", ["lp"]),
    move: move("1", "Jab", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      startup: 10,
      active: 2,
      recovery: 8,
      onHit: 1,
      onBlock: 1,
      onCounterHit: 3,
      damage: 7,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["rp"]),
    move: move("2", "Straight", TekkenAttackHeight.HIGH, TekkenLimb.RIGHT_PUNCH, {
      startup: 12,
      active: 3,
      recovery: 10,
      onHit: 3,
      onBlock: -1,
      onCounterHit: 5,
      damage: 12,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["rk"]),
    move: move("4", "Roundhouse", TekkenAttackHeight.HIGH, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 4,
      recovery: 14,
      onHit: 7,
      onBlock: -6,
      onCounterHit: 10,
      damage: 22,
      chipDamage: 3,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["lp", "lk"]),
    move: move("1+3", "Throw", TekkenAttackHeight.HIGH, TekkenLimb.LEFT_PUNCH, {
      type: "throw",
      startup: 12,
      active: 2,
      recovery: 30,
      onHit: 0,
      onBlock: 0,
      onCounterHit: 0,
      damage: 35,
      chipDamage: 0,
      knockback: 0.6,
      hitbox: { x: 0.3, y: 1.5, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },

  // ── MID attacks ───────────────────────────────────────────────────────
  {
    input: cmd("d", ["lp"]),
    move: move("d+1", "Mid Jab", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 12,
      active: 2,
      recovery: 10,
      onHit: 2,
      onBlock: -2,
      onCounterHit: 4,
      damage: 10,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d", ["rp"]),
    move: move("d+2", "Uppercut", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 15,
      active: 3,
      recovery: 22,
      onHit: 0,
      onBlock: -13,
      onCounterHit: 0,
      damage: 18,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.22,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("n", ["lk"]),
    move: move("3", "Front Kick", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 14,
      active: 3,
      recovery: 12,
      onHit: 5,
      onBlock: -4,
      onCounterHit: 8,
      damage: 17,
      chipDamage: 2,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/f", ["lp"]),
    move: move("d/f+1", "Mid Poke", TekkenAttackHeight.MID, TekkenLimb.LEFT_PUNCH, {
      startup: 13,
      active: 2,
      recovery: 10,
      onHit: 5,
      onBlock: -3,
      onCounterHit: 7,
      damage: 13,
      chipDamage: 1,
      knockback: 0.2,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/f", ["rp"]),
    move: move("d/f+2", "Mid Launcher", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      startup: 15,
      active: 3,
      recovery: 22,
      onHit: 0,
      onBlock: -12,
      onCounterHit: 0,
      damage: 17,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.2,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/f", ["lk"]),
    move: move("d/f+3", "Knee", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 4,
      recovery: 14,
      onHit: 6,
      onBlock: -7,
      onCounterHit: 9,
      damage: 20,
      chipDamage: 2,
      knockback: 0.35,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("u/f", ["lk"]),
    move: move("u/f+3", "Hopkick", TekkenAttackHeight.MID, TekkenLimb.LEFT_KICK, {
      startup: 18,
      active: 4,
      recovery: 24,
      onHit: 0,
      onBlock: -13,
      onCounterHit: 0,
      damage: 20,
      chipDamage: 2,
      isLauncher: true,
      launchHeight: 0.24,
      hasLowCrush: true,
      knockback: 0.45,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("f", ["lp", "rp"]),
    move: move("f+1+2", "Power Crush", TekkenAttackHeight.MID, TekkenLimb.RIGHT_PUNCH, {
      type: "special",
      startup: 20,
      active: 5,
      recovery: 20,
      onHit: 4,
      onBlock: -14,
      onCounterHit: 8,
      damage: 28,
      chipDamage: 4,
      isPowerCrush: true,
      knockback: 0.5,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/f", ["rk"]),
    move: move("d/f+4", "Screw Kick", TekkenAttackHeight.MID, TekkenLimb.RIGHT_KICK, {
      startup: 16,
      active: 4,
      recovery: 16,
      onHit: 4,
      onBlock: -9,
      onCounterHit: 7,
      damage: 15,
      chipDamage: 2,
      isScrew: true,
      knockback: 0.3,
      hitbox: { x: 0.3, y: 0.9, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },

  // ── LOW attacks ───────────────────────────────────────────────────────
  {
    input: cmd("d", ["lk"]),
    move: move("d+3", "Low Kick", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 16,
      active: 3,
      recovery: 18,
      onHit: 2,
      onBlock: -13,
      onCounterHit: 5,
      damage: 12,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d", ["rk"]),
    move: move("d+4", "Ankle Kick", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      startup: 12,
      active: 2,
      recovery: 16,
      onHit: 0,
      onBlock: -11,
      onCounterHit: 3,
      damage: 10,
      chipDamage: 1,
      knockback: 0.1,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/b", ["lk"]),
    move: move("d/b+3", "Sweep", TekkenAttackHeight.LOW, TekkenLimb.LEFT_KICK, {
      type: "command",
      startup: 20,
      active: 4,
      recovery: 24,
      onHit: 0,
      onBlock: -16,
      onCounterHit: 0,
      damage: 18,
      chipDamage: 2,
      knockback: 0.4,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
  {
    input: cmd("d/b", ["rk"]),
    move: move("d/b+4", "Low Poke", TekkenAttackHeight.LOW, TekkenLimb.RIGHT_KICK, {
      startup: 14,
      active: 3,
      recovery: 14,
      onHit: 2,
      onBlock: -12,
      onCounterHit: 5,
      damage: 11,
      chipDamage: 1,
      knockback: 0.15,
      hitbox: { x: 0.3, y: 0.2, z: 0, w: 0.5, h: 0.3, d: 0.4 },
    }),
  },
];
