import {
  DiabloMapConfig,
  DiabloMapId,
  ItemRarity,
  MapCompletionReward,
  EnemyType,
} from './DiabloTypes';

// ---------------------------------------------------------------------------
//  2. MAP CONFIGURATIONS
// ---------------------------------------------------------------------------

export const MAP_CONFIGS: Record<DiabloMapId, DiabloMapConfig> = {
  [DiabloMapId.FOREST]: {
    id: DiabloMapId.FOREST,
    name: 'Darkwood Forest',
    description: 'A dark and foreboding forest filled with dangerous creatures.',
    width: 120,
    depth: 120,
    enemyTypes: [
      EnemyType.WOLF,
      EnemyType.BANDIT,
      EnemyType.BEAR,
      EnemyType.FOREST_SPIDER,
      EnemyType.TREANT,
      EnemyType.MOSSY_LURKER,
      EnemyType.DIRE_STAG,
      EnemyType.WOODLAND_WISP,
    ],
    maxEnemies: 25,
    spawnInterval: 5,
    treasureCount: 3,
    ambientColor: '#224422',
    groundColor: '#335533',
    fogDensity: 0.015,
    fogColor: '#88aa88',
    backgroundMusic: 'forest_ambient',
  },
  [DiabloMapId.ELVEN_VILLAGE]: {
    id: DiabloMapId.ELVEN_VILLAGE,
    name: 'Aelindor - Elven Village',
    description: 'A corrupted elven village overrun by dark forces.',
    width: 100,
    depth: 100,
    enemyTypes: [
      EnemyType.CORRUPTED_ELF,
      EnemyType.DARK_RANGER,
      EnemyType.SHADOW_BEAST,
      EnemyType.CORRUPTED_SENTINEL,
      EnemyType.GLOOM_ARCHER,
      EnemyType.FEY_ABOMINATION,
    ],
    maxEnemies: 20,
    spawnInterval: 6,
    treasureCount: 4,
    ambientColor: '#225544',
    groundColor: '#336655',
    fogDensity: 0.025,
    fogColor: '#77bbaa',
    backgroundMusic: 'elven_ruins',
  },
  [DiabloMapId.NECROPOLIS_DUNGEON]: {
    id: DiabloMapId.NECROPOLIS_DUNGEON,
    name: 'Necropolis Depths',
    description: 'The deep dungeon of the Necropolis, crawling with undead horrors.',
    width: 80,
    depth: 80,
    enemyTypes: [
      EnemyType.SKELETON_WARRIOR,
      EnemyType.ZOMBIE,
      EnemyType.NECROMANCER,
      EnemyType.BONE_GOLEM,
      EnemyType.WRAITH,
      EnemyType.CRYPT_SHADE,
      EnemyType.BONE_ARCHER,
      EnemyType.LICH_ACOLYTE,
    ],
    maxEnemies: 30,
    spawnInterval: 4,
    treasureCount: 5,
    ambientColor: '#221133',
    groundColor: '#333344',
    fogDensity: 0.04,
    fogColor: '#443355',
    backgroundMusic: 'dungeon_depths',
  },
  [DiabloMapId.VOLCANIC_WASTES]: {
    id: DiabloMapId.VOLCANIC_WASTES,
    name: 'Volcanic Wastes',
    description: 'A scorched hellscape of molten rivers and ash storms. Demons forged in flame patrol the burning ruins.',
    width: 110,
    depth: 110,
    enemyTypes: [
      EnemyType.FIRE_IMP,
      EnemyType.LAVA_ELEMENTAL,
      EnemyType.INFERNAL_KNIGHT,
      EnemyType.MAGMA_SERPENT,
      EnemyType.MOLTEN_COLOSSUS,
      EnemyType.EMBER_FIEND,
      EnemyType.VOLCANIC_SCORPION,
      EnemyType.ASH_WRAITH,
    ],
    maxEnemies: 30,
    spawnInterval: 4,
    treasureCount: 4,
    ambientColor: '#442211',
    groundColor: '#332211',
    fogDensity: 0.02,
    fogColor: '#663322',
    backgroundMusic: 'volcanic_wastes',
  },
  [DiabloMapId.ABYSSAL_RIFT]: {
    id: DiabloMapId.ABYSSAL_RIFT,
    name: 'Abyssal Rift',
    description: 'A tear in reality where the void bleeds through. Eldritch horrors drift between shattered islands of stone.',
    width: 90,
    depth: 90,
    enemyTypes: [
      EnemyType.VOID_STALKER,
      EnemyType.SHADOW_WEAVER,
      EnemyType.ABYSSAL_HORROR,
      EnemyType.RIFT_WALKER,
      EnemyType.ENTROPY_LORD,
      EnemyType.VOID_TENDRIL,
      EnemyType.RIFT_SCREAMER,
      EnemyType.DIMENSIONAL_STALKER,
    ],
    maxEnemies: 35,
    spawnInterval: 3.5,
    treasureCount: 5,
    ambientColor: '#110022',
    groundColor: '#1a0a2e',
    fogDensity: 0.035,
    fogColor: '#220044',
    backgroundMusic: 'abyssal_rift',
  },
  [DiabloMapId.DRAGONS_SANCTUM]: {
    id: DiabloMapId.DRAGONS_SANCTUM,
    name: "Dragon's Sanctum",
    description: 'The ancient lair of the Elder Dragons. Gold-encrusted caverns echo with primordial fury.',
    width: 130,
    depth: 130,
    enemyTypes: [
      EnemyType.DRAGONKIN_WARRIOR,
      EnemyType.WYRM_PRIEST,
      EnemyType.DRAKE_GUARDIAN,
      EnemyType.DRAGON_WHELP,
      EnemyType.ELDER_DRAGON,
      EnemyType.SCALED_SORCERER,
      EnemyType.DRAGONSPAWN_BERSERKER,
      EnemyType.FLAME_HERALD,
    ],
    maxEnemies: 28,
    spawnInterval: 4.5,
    treasureCount: 6,
    ambientColor: '#332200',
    groundColor: '#443311',
    fogDensity: 0.015,
    fogColor: '#554422',
    backgroundMusic: 'dragons_sanctum',
  },
  [DiabloMapId.SUNSCORCH_DESERT]: {
    id: DiabloMapId.SUNSCORCH_DESERT,
    name: 'Sunscorch Desert',
    description: 'A vast expanse of sun-blasted dunes and ancient ruins half-buried in sand.',
    width: 140,
    depth: 140,
    enemyTypes: [
      EnemyType.SAND_SCORPION,
      EnemyType.DESERT_BANDIT,
      EnemyType.SAND_WURM,
      EnemyType.DUST_WRAITH,
      EnemyType.SAND_GOLEM,
      EnemyType.DUNE_REAVER,
      EnemyType.SANDSTORM_ELEMENTAL,
      EnemyType.OASIS_SERPENT,
    ],
    maxEnemies: 22,
    spawnInterval: 5,
    treasureCount: 4,
    ambientColor: '#665533',
    groundColor: '#ccaa66',
    fogDensity: 0.008,
    fogColor: '#ddcc99',
    backgroundMusic: 'desert_winds',
  },
  [DiabloMapId.EMERALD_GRASSLANDS]: {
    id: DiabloMapId.EMERALD_GRASSLANDS,
    name: 'Emerald Grasslands',
    description: 'Rolling green hills dotted with wildflowers. Raiders and wild beasts roam the open plains.',
    width: 150,
    depth: 150,
    enemyTypes: [
      EnemyType.WILD_BOAR,
      EnemyType.PLAINS_RAIDER,
      EnemyType.GIANT_HAWK,
      EnemyType.BISON_BEAST,
      EnemyType.CENTAUR_WARCHIEF,
      EnemyType.STEPPE_STALKER,
      EnemyType.THUNDER_RAM,
      EnemyType.PRAIRIE_WITCH,
    ],
    maxEnemies: 20,
    spawnInterval: 6,
    treasureCount: 3,
    ambientColor: '#336622',
    groundColor: '#55aa33',
    fogDensity: 0.006,
    fogColor: '#aaccaa',
    backgroundMusic: 'grassland_breeze',
  },
  [DiabloMapId.RIVERSIDE_VILLAGE]: {
    id: DiabloMapId.RIVERSIDE_VILLAGE,
    name: 'Riverside Village',
    description: 'A once-peaceful hamlet along the Silverrun River. Bandits and river creatures now menace the abandoned cottages.',
    width: 120,
    depth: 120,
    enemyTypes: [
      EnemyType.BANDIT,
      EnemyType.WOLF,
      EnemyType.WILD_BOAR,
      EnemyType.PLAINS_RAIDER,
      EnemyType.FOREST_SPIDER,
      EnemyType.BOG_LURKER,
      EnemyType.STEPPE_STALKER,
      EnemyType.MOSSY_LURKER,
    ],
    maxEnemies: 18,
    spawnInterval: 6,
    treasureCount: 3,
    ambientColor: '#2a5522',
    groundColor: '#449933',
    fogDensity: 0.007,
    fogColor: '#99bbaa',
    backgroundMusic: 'grassland_breeze',
  },
  [DiabloMapId.WHISPERING_MARSH]: {
    id: DiabloMapId.WHISPERING_MARSH,
    name: 'Whispering Marsh',
    description: 'A fog-choked swampland where poisonous gases rise from stagnant pools. Ancient horrors lurk beneath the murk.',
    width: 130, depth: 130,
    enemyTypes: [EnemyType.BOG_LURKER, EnemyType.MARSH_HAG, EnemyType.TOXIC_TOAD, EnemyType.SWAMP_VINE, EnemyType.HYDRA_MATRIARCH, EnemyType.FEN_CRAWLER, EnemyType.MIRE_SPECTER, EnemyType.LEECH_SWARM],
    maxEnemies: 22, spawnInterval: 5, treasureCount: 3,
    ambientColor: '#2a3a22', groundColor: '#3b4a2b', fogDensity: 0.025, fogColor: '#556644',
    backgroundMusic: 'marsh_ambient',
  },
  [DiabloMapId.CRYSTAL_CAVERNS]: {
    id: DiabloMapId.CRYSTAL_CAVERNS,
    name: 'Crystal Caverns',
    description: 'Vast underground chambers lined with luminous crystals. The refracted light reveals dangers hidden in every shadow.',
    width: 100, depth: 100,
    enemyTypes: [EnemyType.CRYSTAL_SPIDER, EnemyType.GEM_GOLEM, EnemyType.CAVE_BAT_SWARM, EnemyType.QUARTZ_ELEMENTAL, EnemyType.PRISMATIC_WYRM, EnemyType.SHARD_SENTINEL, EnemyType.GEODE_BEETLE, EnemyType.CRYSTAL_SHADE],
    maxEnemies: 24, spawnInterval: 5, treasureCount: 5,
    ambientColor: '#223355', groundColor: '#334466', fogDensity: 0.02, fogColor: '#445577',
    backgroundMusic: 'cavern_echoes',
  },
  [DiabloMapId.FROZEN_TUNDRA]: {
    id: DiabloMapId.FROZEN_TUNDRA,
    name: 'Frozen Tundra',
    description: 'An endless expanse of ice and snow battered by howling blizzards. Frostbitten beasts prowl the whiteout.',
    width: 140, depth: 140,
    enemyTypes: [EnemyType.FROST_WOLF, EnemyType.ICE_WRAITH, EnemyType.YETI, EnemyType.FROZEN_REVENANT, EnemyType.GLACIAL_TITAN, EnemyType.PERMAFROST_SPIDER, EnemyType.BLIZZARD_PHANTOM, EnemyType.FROST_TROLL],
    maxEnemies: 26, spawnInterval: 4.5, treasureCount: 4,
    ambientColor: '#334455', groundColor: '#aabbcc', fogDensity: 0.018, fogColor: '#bbccdd',
    backgroundMusic: 'tundra_wind',
  },
  [DiabloMapId.HAUNTED_CATHEDRAL]: {
    id: DiabloMapId.HAUNTED_CATHEDRAL,
    name: 'Haunted Cathedral',
    description: 'A once-holy cathedral now desecrated by dark rituals. Spectral choirs echo through shattered stained glass.',
    width: 90, depth: 90,
    enemyTypes: [EnemyType.PHANTOM_KNIGHT, EnemyType.GARGOYLE, EnemyType.CURSED_PRIEST, EnemyType.SHADOW_ACOLYTE, EnemyType.CATHEDRAL_DEMON, EnemyType.BELL_WRAITH, EnemyType.DESECRATED_MONK, EnemyType.STAINED_GLASS_GOLEM],
    maxEnemies: 28, spawnInterval: 4, treasureCount: 4,
    ambientColor: '#2a2233', groundColor: '#3a3344', fogDensity: 0.03, fogColor: '#443355',
    backgroundMusic: 'cathedral_requiem',
  },
  [DiabloMapId.THORNWOOD_THICKET]: {
    id: DiabloMapId.THORNWOOD_THICKET,
    name: 'Thornwood Thicket',
    description: 'A twisted maze of thorny brambles and blighted trees. The corruption here runs deeper than root and soil.',
    width: 110, depth: 110,
    enemyTypes: [EnemyType.THORN_CRAWLER, EnemyType.BLIGHT_SPRITE, EnemyType.FUNGAL_BRUTE, EnemyType.ROTWOOD_LICH, EnemyType.THORNMOTHER, EnemyType.BRIAR_WOLF, EnemyType.SPORE_MOTH, EnemyType.NETTLE_ELEMENTAL],
    maxEnemies: 28, spawnInterval: 4.5, treasureCount: 4,
    ambientColor: '#2a3322', groundColor: '#3a2a22', fogDensity: 0.022, fogColor: '#554433',
    backgroundMusic: 'thornwood_whispers',
  },
  [DiabloMapId.CLOCKWORK_FOUNDRY]: {
    id: DiabloMapId.CLOCKWORK_FOUNDRY,
    name: 'Clockwork Foundry',
    description: 'An ancient dwarven forge overrun by malfunctioning automatons. Steam hisses from cracked pipes as gears grind endlessly.',
    width: 100, depth: 100,
    enemyTypes: [EnemyType.CLOCKWORK_SOLDIER, EnemyType.STEAM_GOLEM, EnemyType.GEAR_SPIDER, EnemyType.FORGE_MASTER, EnemyType.IRON_COLOSSUS, EnemyType.BRASS_BEETLE, EnemyType.PISTON_GOLEM, EnemyType.ARC_DRONE],
    maxEnemies: 32, spawnInterval: 3.5, treasureCount: 5,
    ambientColor: '#3a3322', groundColor: '#4a4433', fogDensity: 0.015, fogColor: '#665544',
    backgroundMusic: 'foundry_machinery',
  },
  [DiabloMapId.CRIMSON_CITADEL]: {
    id: DiabloMapId.CRIMSON_CITADEL,
    name: 'Crimson Citadel',
    description: 'A blood-soaked fortress where vampiric lords feast on the living. The walls weep crimson and the air tastes of iron.',
    width: 110, depth: 110,
    enemyTypes: [EnemyType.BLOOD_KNIGHT, EnemyType.CRIMSON_MAGE, EnemyType.GARGOYLE_SENTINEL, EnemyType.BLOOD_FIEND, EnemyType.VAMPIRE_LORD, EnemyType.BLOODTHORN_BAT, EnemyType.SCARLET_ASSASSIN, EnemyType.CRIMSON_SHADE],
    maxEnemies: 30, spawnInterval: 4, treasureCount: 5,
    ambientColor: '#3a1122', groundColor: '#4a2233', fogDensity: 0.02, fogColor: '#552233',
    backgroundMusic: 'citadel_dirge',
  },
  [DiabloMapId.STORMSPIRE_PEAK]: {
    id: DiabloMapId.STORMSPIRE_PEAK,
    name: 'Stormspire Peak',
    description: 'The highest summit in the realm, perpetually wracked by lightning storms. Wind elementals guard the peak with fury.',
    width: 120, depth: 120,
    enemyTypes: [EnemyType.STORM_HARPY, EnemyType.THUNDER_ELEMENTAL, EnemyType.LIGHTNING_DRAKE, EnemyType.WIND_SHAMAN, EnemyType.TEMPEST_TITAN, EnemyType.GALE_FALCON, EnemyType.STATIC_GOLEM, EnemyType.STORM_CALLER],
    maxEnemies: 30, spawnInterval: 4, treasureCount: 5,
    ambientColor: '#334455', groundColor: '#556677', fogDensity: 0.012, fogColor: '#778899',
    backgroundMusic: 'stormspire_thunder',
  },
  [DiabloMapId.SHADOW_REALM]: {
    id: DiabloMapId.SHADOW_REALM,
    name: 'Shadow Realm',
    description: 'A nightmare dimension where reality fractures and terror takes form. Your deepest fears hunt you here.',
    width: 100, depth: 100,
    enemyTypes: [EnemyType.NIGHTMARE_STALKER, EnemyType.DREAD_PHANTOM, EnemyType.SOUL_DEVOURER, EnemyType.SHADOW_COLOSSUS, EnemyType.NIGHTMARE_KING, EnemyType.FEAR_CRAWLER, EnemyType.UMBRAL_ASSASSIN, EnemyType.VOID_ECHO],
    maxEnemies: 35, spawnInterval: 3, treasureCount: 6,
    ambientColor: '#110011', groundColor: '#1a0a1a', fogDensity: 0.035, fogColor: '#220022',
    backgroundMusic: 'shadow_realm_dread',
  },
  [DiabloMapId.PRIMORDIAL_ABYSS]: {
    id: DiabloMapId.PRIMORDIAL_ABYSS,
    name: 'Primordial Abyss',
    description: 'The deepest pit of existence where ancient entities slumber. Time and space have no meaning in this void.',
    width: 90, depth: 90,
    enemyTypes: [EnemyType.ABYSSAL_LEVIATHAN, EnemyType.VOID_REAPER, EnemyType.CHAOS_SPAWN, EnemyType.ELDER_VOID_FIEND, EnemyType.PRIMORDIAL_ONE, EnemyType.ENTROPY_WORM, EnemyType.GENESIS_SHADE, EnemyType.NULL_SENTINEL],
    maxEnemies: 38, spawnInterval: 3, treasureCount: 7,
    ambientColor: '#0a0011', groundColor: '#110a1a', fogDensity: 0.04, fogColor: '#1a0022',
    backgroundMusic: 'primordial_void',
  },
  [DiabloMapId.MOONLIT_GROVE]: {
    id: DiabloMapId.MOONLIT_GROVE,
    name: 'Moonlit Grove',
    description: 'A mystical clearing bathed in eternal moonlight where fey creatures dance among silver-leafed trees. Wisps of luminous pollen drift through the enchanted air.',
    width: 130, depth: 130,
    enemyTypes: [EnemyType.MOONLIT_SPRITE, EnemyType.FAE_DANCER, EnemyType.SHADOW_STAG, EnemyType.LUNAR_MOTH, EnemyType.MOONBEAST_ALPHA, EnemyType.THORN_FAIRY, EnemyType.NOCTURNAL_PREDATOR, EnemyType.LUNAR_WISP],
    maxEnemies: 20, spawnInterval: 6, treasureCount: 3,
    ambientColor: '#1a2244', groundColor: '#2a3355', fogDensity: 0.012, fogColor: '#334477',
    backgroundMusic: 'moonlit_grove',
  },
  [DiabloMapId.CORAL_DEPTHS]: {
    id: DiabloMapId.CORAL_DEPTHS,
    name: 'Coral Depths',
    description: 'Sunken ruins encrusted with bioluminescent coral. Predatory sea creatures patrol the flooded chambers where ancient treasures lie forgotten.',
    width: 110, depth: 110,
    enemyTypes: [EnemyType.REEF_CRAWLER, EnemyType.SIREN_WITCH, EnemyType.ABYSSAL_ANGLER, EnemyType.BARNACLE_GOLEM, EnemyType.LEVIATHAN_HATCHLING, EnemyType.TIDE_LURKER, EnemyType.PEARL_GOLEM, EnemyType.DEEP_SEA_PHANTOM],
    maxEnemies: 24, spawnInterval: 5, treasureCount: 4,
    ambientColor: '#112233', groundColor: '#1a3344', fogDensity: 0.022, fogColor: '#224455',
    backgroundMusic: 'coral_depths',
  },
  [DiabloMapId.ANCIENT_LIBRARY]: {
    id: DiabloMapId.ANCIENT_LIBRARY,
    name: 'Ancient Library',
    description: 'An impossibly vast library where forbidden knowledge has animated its guardians. Towering shelves creak with sentient tomes and ink-born horrors.',
    width: 100, depth: 100,
    enemyTypes: [EnemyType.ANIMATED_TOME, EnemyType.INK_WRAITH, EnemyType.SCROLL_GOLEM, EnemyType.ARCANE_CURATOR, EnemyType.FORBIDDEN_GRIMOIRE, EnemyType.QUILL_FIEND, EnemyType.PAPER_GOLEM, EnemyType.RUNE_SPIRIT],
    maxEnemies: 24, spawnInterval: 5, treasureCount: 5,
    ambientColor: '#2a2233', groundColor: '#3a3344', fogDensity: 0.018, fogColor: '#443355',
    backgroundMusic: 'ancient_library',
  },
  [DiabloMapId.JADE_TEMPLE]: {
    id: DiabloMapId.JADE_TEMPLE,
    name: 'Jade Temple',
    description: 'A crumbling temple swallowed by jungle vines where jade constructs still guard forgotten rituals. Tribal shamans have awakened the old gods within.',
    width: 120, depth: 120,
    enemyTypes: [EnemyType.TEMPLE_GUARDIAN, EnemyType.VINE_SERPENT, EnemyType.JADE_CONSTRUCT, EnemyType.JUNGLE_SHAMAN, EnemyType.ANCIENT_IDOL, EnemyType.JADE_VIPER, EnemyType.TEMPLE_MONK, EnemyType.STONE_IDOL_FRAGMENT],
    maxEnemies: 26, spawnInterval: 4.5, treasureCount: 4,
    ambientColor: '#224422', groundColor: '#336633', fogDensity: 0.02, fogColor: '#447744',
    backgroundMusic: 'jade_temple',
  },
  [DiabloMapId.ASHEN_BATTLEFIELD]: {
    id: DiabloMapId.ASHEN_BATTLEFIELD,
    name: 'Ashen Battlefield',
    description: 'The scarred remnants of a cataclysmic war. Ghostly soldiers still fight an endless battle among shattered siege engines and fields of rusted swords.',
    width: 140, depth: 140,
    enemyTypes: [EnemyType.FALLEN_SOLDIER, EnemyType.WAR_SPECTER, EnemyType.SIEGE_WRAITH, EnemyType.ASHEN_COMMANDER, EnemyType.DREAD_GENERAL, EnemyType.EMBER_KNIGHT, EnemyType.WAR_DRUMMER, EnemyType.CARRION_SWARM],
    maxEnemies: 28, spawnInterval: 4, treasureCount: 4,
    ambientColor: '#2a2222', groundColor: '#3a3333', fogDensity: 0.02, fogColor: '#554444',
    backgroundMusic: 'ashen_battlefield',
  },
  [DiabloMapId.FUNGAL_DEPTHS]: {
    id: DiabloMapId.FUNGAL_DEPTHS,
    name: 'Fungal Depths',
    description: 'Cavernous tunnels choked with towering bioluminescent mushrooms. The air is thick with toxic spores and the ground pulses with mycelial networks.',
    width: 90, depth: 90,
    enemyTypes: [EnemyType.SPORE_CRAWLER, EnemyType.MYCELIUM_HORROR, EnemyType.TOXIC_SHROOM, EnemyType.FUNGAL_SHAMBLER, EnemyType.SPOREQUEEN, EnemyType.CORDYCEPS_HOST, EnemyType.LUMINOUS_JELLY, EnemyType.ROT_BORER],
    maxEnemies: 30, spawnInterval: 3.5, treasureCount: 5,
    ambientColor: '#1a2a1a', groundColor: '#2a3a2a', fogDensity: 0.028, fogColor: '#334433',
    backgroundMusic: 'fungal_depths',
  },
  [DiabloMapId.OBSIDIAN_FORTRESS]: {
    id: DiabloMapId.OBSIDIAN_FORTRESS,
    name: 'Obsidian Fortress',
    description: 'A fortress carved from volcanic glass, its walls reflecting hellfire. Demonic legions drill in its courtyards while dark inquisitors judge the damned.',
    width: 100, depth: 100,
    enemyTypes: [EnemyType.OBSIDIAN_SENTINEL, EnemyType.HELLFIRE_ARCHER, EnemyType.DARK_INQUISITOR, EnemyType.DOOM_HOUND, EnemyType.OBSIDIAN_WARLORD, EnemyType.MAGMA_IMP, EnemyType.OBSIDIAN_HOUND, EnemyType.SHADOW_INQUISITOR],
    maxEnemies: 32, spawnInterval: 3.5, treasureCount: 5,
    ambientColor: '#220a0a', groundColor: '#331515', fogDensity: 0.025, fogColor: '#442222',
    backgroundMusic: 'obsidian_fortress',
  },
  [DiabloMapId.CELESTIAL_RUINS]: {
    id: DiabloMapId.CELESTIAL_RUINS,
    name: 'Celestial Ruins',
    description: 'Shattered temples floating among the stars. Fallen cosmic guardians patrol bridges of pure light between crumbling astral platforms.',
    width: 110, depth: 110,
    enemyTypes: [EnemyType.STAR_WISP, EnemyType.ASTRAL_GUARDIAN, EnemyType.COMET_DRAKE, EnemyType.VOID_MONK, EnemyType.CELESTIAL_ARCHON, EnemyType.NOVA_SPRITE, EnemyType.CONSTELLATION_GOLEM, EnemyType.GRAVITY_WELL],
    maxEnemies: 34, spawnInterval: 3.5, treasureCount: 6,
    ambientColor: '#111133', groundColor: '#1a1a44', fogDensity: 0.015, fogColor: '#222255',
    backgroundMusic: 'celestial_ruins',
  },
  [DiabloMapId.INFERNAL_THRONE]: {
    id: DiabloMapId.INFERNAL_THRONE,
    name: 'Infernal Throne',
    description: 'The seat of demonic power in the deepest layer of the abyss. Rivers of molten souls flow beneath a throne of compressed agony and despair.',
    width: 95, depth: 95,
    enemyTypes: [EnemyType.PIT_FIEND, EnemyType.HELLBORN_MAGE, EnemyType.INFERNAL_BRUTE, EnemyType.SOUL_COLLECTOR, EnemyType.DEMON_OVERLORD, EnemyType.CHAIN_DEVIL, EnemyType.BRIMSTONE_CRAWLER, EnemyType.WRATH_SPECTER],
    maxEnemies: 36, spawnInterval: 3, treasureCount: 6,
    ambientColor: '#1a0505', groundColor: '#2a0a0a', fogDensity: 0.032, fogColor: '#331111',
    backgroundMusic: 'infernal_throne',
  },
  [DiabloMapId.ASTRAL_VOID]: {
    id: DiabloMapId.ASTRAL_VOID,
    name: 'Astral Void',
    description: 'The space between dimensions where reality itself unravels. Entities that predate creation drift through an endless expanse of fractured timelines.',
    width: 85, depth: 85,
    enemyTypes: [EnemyType.REALITY_SHREDDER, EnemyType.TEMPORAL_WRAITH, EnemyType.DIMENSION_WEAVER, EnemyType.VOID_TITAN, EnemyType.ASTRAL_ANNIHILATOR, EnemyType.PARADOX_SHADE, EnemyType.ANTIMATTER_WISP, EnemyType.FRACTURE_BEAST],
    maxEnemies: 40, spawnInterval: 2.5, treasureCount: 7,
    ambientColor: '#050511', groundColor: '#0a0a1a', fogDensity: 0.042, fogColor: '#111122',
    backgroundMusic: 'astral_void',
  },
  [DiabloMapId.SHATTERED_COLOSSEUM]: {
    id: DiabloMapId.SHATTERED_COLOSSEUM,
    name: 'Shattered Colosseum',
    description: 'A titanic arena crumbling into the earth where spectral gladiators still fight for an audience of ghosts. The roar of phantom crowds echoes off bloodstained pillars.',
    width: 140, depth: 140,
    enemyTypes: [EnemyType.SPECTRAL_GLADIATOR, EnemyType.ARENA_BEAST, EnemyType.GHOSTLY_RETIARIUS, EnemyType.CURSED_CHAMPION, EnemyType.COLOSSEUM_WARDEN, EnemyType.LION_SPIRIT, EnemyType.PIT_FIGHTER_GHOST, EnemyType.MIRMILLO_SPECTER],
    maxEnemies: 20, spawnInterval: 6, treasureCount: 3,
    ambientColor: '#2a2822', groundColor: '#3a3832', fogDensity: 0.01, fogColor: '#554e44',
    backgroundMusic: 'shattered_colosseum',
  },
  [DiabloMapId.PETRIFIED_GARDEN]: {
    id: DiabloMapId.PETRIFIED_GARDEN,
    name: 'Petrified Garden',
    description: 'A once-magnificent botanical garden cursed by a gorgon queen. Stone statues of former visitors line the paths between calcified rose bushes and fossilized fountains.',
    width: 120, depth: 120,
    enemyTypes: [EnemyType.STONE_NYMPH, EnemyType.BASILISK_HATCHLING, EnemyType.GRANITE_GOLEM, EnemyType.PETRIFIED_TREANT, EnemyType.GORGON_MATRIARCH, EnemyType.MOSS_BASILISK, EnemyType.CALCIFIED_NYMPH, EnemyType.STONE_SERPENT],
    maxEnemies: 22, spawnInterval: 5.5, treasureCount: 4,
    ambientColor: '#2a2a2a', groundColor: '#3a3a38', fogDensity: 0.016, fogColor: '#555550',
    backgroundMusic: 'petrified_garden',
  },
  [DiabloMapId.SUNKEN_CITADEL]: {
    id: DiabloMapId.SUNKEN_CITADEL,
    name: 'Sunken Citadel',
    description: 'A grand fortress dragged beneath the waves by an ancient curse. Drowned knights patrol flooded corridors as bioluminescent algae casts eerie green light on barnacled battlements.',
    width: 100, depth: 100,
    enemyTypes: [EnemyType.DROWNED_KNIGHT, EnemyType.DEPTH_LURKER, EnemyType.TIDAL_PHANTOM, EnemyType.CORAL_ABOMINATION, EnemyType.ABYSSAL_WARDEN, EnemyType.BARNACLE_KNIGHT, EnemyType.PRESSURE_PHANTOM, EnemyType.KELP_HORROR],
    maxEnemies: 24, spawnInterval: 5, treasureCount: 5,
    ambientColor: '#0a2233', groundColor: '#153344', fogDensity: 0.024, fogColor: '#1a3344',
    backgroundMusic: 'sunken_citadel',
  },
  [DiabloMapId.WYRMSCAR_CANYON]: {
    id: DiabloMapId.WYRMSCAR_CANYON,
    name: 'Wyrmscar Canyon',
    description: 'A deep canyon scorched black by generations of dragonfire. Nesting wyverns circle overhead while drake broodlings swarm the charred ravines below.',
    width: 130, depth: 130,
    enemyTypes: [EnemyType.CANYON_RAPTOR, EnemyType.SCORCH_WYVERN, EnemyType.DRAKE_BROODLING, EnemyType.WYRMFIRE_SHAMAN, EnemyType.CANYON_WYRMLORD, EnemyType.CLIFF_RAPTOR, EnemyType.NEST_GUARDIAN, EnemyType.MAGMA_DRAKE],
    maxEnemies: 26, spawnInterval: 4.5, treasureCount: 4,
    ambientColor: '#332211', groundColor: '#443322', fogDensity: 0.014, fogColor: '#554433',
    backgroundMusic: 'wyrmscar_canyon',
  },
  [DiabloMapId.PLAGUEROT_SEWERS]: {
    id: DiabloMapId.PLAGUEROT_SEWERS,
    name: 'Plaguerot Sewers',
    description: 'The festering underbelly of a city consumed by plague. Toxic rivers of bile flow through crumbling tunnels where the infected have devolved into something no longer human.',
    width: 90, depth: 90,
    enemyTypes: [EnemyType.SEWER_RAT_SWARM, EnemyType.PLAGUE_BEARER, EnemyType.BILE_ELEMENTAL, EnemyType.AFFLICTED_BRUTE, EnemyType.PESTILENCE_LORD, EnemyType.BLOAT_RAT, EnemyType.PESTILENT_SLIME, EnemyType.SEWER_HARPY],
    maxEnemies: 28, spawnInterval: 4, treasureCount: 3,
    ambientColor: '#1a2a11', groundColor: '#2a3a22', fogDensity: 0.03, fogColor: '#334422',
    backgroundMusic: 'plaguerot_sewers',
  },
  [DiabloMapId.ETHEREAL_SANCTUM]: {
    id: DiabloMapId.ETHEREAL_SANCTUM,
    name: 'Ethereal Sanctum',
    description: 'A temple that phases in and out of existence, straddling multiple planes simultaneously. Its guardians shift between corporeal and spectral forms without warning.',
    width: 110, depth: 110,
    enemyTypes: [EnemyType.PHASE_WALKER, EnemyType.ETHEREAL_SENTINEL, EnemyType.SPIRIT_WEAVER, EnemyType.PLANAR_GUARDIAN, EnemyType.SANCTUM_OVERSEER, EnemyType.ETHER_WISP, EnemyType.SPECTRAL_MONK, EnemyType.PHASE_SPIDER],
    maxEnemies: 30, spawnInterval: 3.5, treasureCount: 5,
    ambientColor: '#1a1a33', groundColor: '#2a2a44', fogDensity: 0.02, fogColor: '#333355',
    backgroundMusic: 'ethereal_sanctum',
  },
  [DiabloMapId.IRON_WASTES]: {
    id: DiabloMapId.IRON_WASTES,
    name: 'Iron Wastes',
    description: 'A blasted wasteland littered with the rusting hulks of colossal war machines. Self-repairing automatons scavenge parts from fallen titans to build ever-deadlier forms.',
    width: 140, depth: 140,
    enemyTypes: [EnemyType.SCRAP_AUTOMATON, EnemyType.RUST_REVENANT, EnemyType.SIEGE_CRAWLER, EnemyType.WAR_ENGINE_CORE, EnemyType.IRON_JUGGERNAUT, EnemyType.JUNK_GOLEM, EnemyType.SCRAP_HAWK, EnemyType.RUST_MITE_SWARM],
    maxEnemies: 32, spawnInterval: 3.5, treasureCount: 5,
    ambientColor: '#2a2222', groundColor: '#3a3333', fogDensity: 0.018, fogColor: '#554444',
    backgroundMusic: 'iron_wastes',
  },
  [DiabloMapId.BLIGHTED_THRONE]: {
    id: DiabloMapId.BLIGHTED_THRONE,
    name: 'Blighted Throne',
    description: 'The corrupted throne room of a king who bargained with dark powers. His court has become a nightmarish parody of nobility, with courtiers fused to their seats and heralds who scream prophecies of doom.',
    width: 100, depth: 100,
    enemyTypes: [EnemyType.CORRUPTED_ROYAL_GUARD, EnemyType.BLIGHT_COURTIER, EnemyType.THRONE_REVENANT, EnemyType.DARK_HERALD, EnemyType.BLIGHTED_KING, EnemyType.PLAGUE_KNIGHT, EnemyType.BLIGHTED_NOBLE, EnemyType.ROT_JESTER],
    maxEnemies: 34, spawnInterval: 3, treasureCount: 6,
    ambientColor: '#1a0a1a', groundColor: '#2a1a2a', fogDensity: 0.028, fogColor: '#332233',
    backgroundMusic: 'blighted_throne',
  },
  [DiabloMapId.CHRONO_LABYRINTH]: {
    id: DiabloMapId.CHRONO_LABYRINTH,
    name: 'Chrono Labyrinth',
    description: 'A maze where corridors loop through fractured timelines. Past and future versions of the same enemies coexist, and the walls rearrange with each tick of an impossible clock.',
    width: 95, depth: 95,
    enemyTypes: [EnemyType.TEMPORAL_ECHO, EnemyType.CLOCKWORK_MINOTAUR, EnemyType.PARADOX_MAGE, EnemyType.TIME_DEVOURER, EnemyType.CHRONO_TITAN, EnemyType.PHASE_BEETLE, EnemyType.TIMELOST_SOLDIER, EnemyType.ENTROPY_WEAVER],
    maxEnemies: 36, spawnInterval: 3, treasureCount: 6,
    ambientColor: '#112244', groundColor: '#1a2a44', fogDensity: 0.022, fogColor: '#223355',
    backgroundMusic: 'chrono_labyrinth',
  },
  [DiabloMapId.ELDRITCH_NEXUS]: {
    id: DiabloMapId.ELDRITCH_NEXUS,
    name: 'Eldritch Nexus',
    description: 'The convergence point of all dark dimensions. Tentacles of pure madness writhe from impossible geometries while alien intelligences probe the boundaries of sanity itself.',
    width: 80, depth: 80,
    enemyTypes: [EnemyType.ELDRITCH_TENDRIL, EnemyType.MIND_FLAYER, EnemyType.NEXUS_ABERRATION, EnemyType.DIMENSIONAL_HORROR, EnemyType.ELDRITCH_OVERMIND, EnemyType.TENTACLE_HORROR, EnemyType.GIBBERING_MOUTHER, EnemyType.PSYCHIC_LEECH],
    maxEnemies: 42, spawnInterval: 2.5, treasureCount: 7,
    ambientColor: '#0a050a', groundColor: '#110a11', fogDensity: 0.045, fogColor: '#150f15',
    backgroundMusic: 'eldritch_nexus',
  },
  [DiabloMapId.CITY_RUINS]: {
    id: DiabloMapId.CITY_RUINS,
    name: 'City Ruins',
    description: 'The shattered remains of a once-great city. Crumbling buildings lean against each other over narrow alleyways choked with rubble and ash. Corrupted watchmen still patrol their forgotten posts.',
    width: 130, depth: 130,
    enemyTypes: [EnemyType.RUINS_WATCHMAN, EnemyType.FALLEN_SENTINEL, EnemyType.RUBBLE_LURKER, EnemyType.ALLEY_STALKER, EnemyType.RUINED_CAPTAIN, EnemyType.COLLAPSED_GOLEM, EnemyType.GUTTER_RAT_SWARM, EnemyType.TOWER_SHADE],
    maxEnemies: 20, spawnInterval: 6, treasureCount: 3,
    ambientColor: '#3a3530', groundColor: '#5c5550', fogDensity: 0.012, fogColor: '#8a8580',
    backgroundMusic: 'city_ruins_ambient',
  },
  [DiabloMapId.CITY]: {
    id: DiabloMapId.CITY,
    name: 'City of Thornwall',
    description: 'A walled city under the grip of a corrupt garrison. Narrow streets wind between tall stone buildings while armored enforcers patrol the market squares and shadowy alleyways.',
    width: 120, depth: 120,
    enemyTypes: [EnemyType.CORRUPT_GUARD, EnemyType.GATE_ENFORCER, EnemyType.ROOFTOP_ARCHER, EnemyType.ALLEY_THUG, EnemyType.CITY_WARDEN, EnemyType.MARKET_BRUTE, EnemyType.SEWER_CREEPER, EnemyType.BELL_TOWER_SENTINEL],
    maxEnemies: 22, spawnInterval: 5.5, treasureCount: 3,
    ambientColor: '#2e3038', groundColor: '#4a4e58', fogDensity: 0.01, fogColor: '#6e7280',
    backgroundMusic: 'city_ambient',
  },
  [DiabloMapId.CAMELOT]: {
    id: DiabloMapId.CAMELOT,
    name: 'Camelot',
    description: 'The great citadel of Camelot. A safe haven with merchants and artisans.',
    width: 100,
    depth: 100,
    enemyTypes: [],
    maxEnemies: 0,
    spawnInterval: 999,
    treasureCount: 0,
    ambientColor: '#445566',
    groundColor: '#887766',
    fogDensity: 0.008,
    fogColor: '#99aabb',
    backgroundMusic: 'camelot_hub',
  },
};

// ---------------------------------------------------------------------------
//  MAP COMPLETION REWARDS
// ---------------------------------------------------------------------------

export const MAP_COMPLETION_REWARDS: Partial<Record<DiabloMapId, MapCompletionReward>> = {
  [DiabloMapId.FOREST]: { gold: 200, xp: 500, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The forest is safe once more.' },
  [DiabloMapId.ELVEN_VILLAGE]: { gold: 300, xp: 800, guaranteedDropRarity: ItemRarity.RARE, bonusMessage: 'Aelindor begins to heal.' },
  [DiabloMapId.NECROPOLIS_DUNGEON]: { gold: 500, xp: 1200, guaranteedDropRarity: ItemRarity.RARE, bonusMessage: 'The dead rest at last.' },
  [DiabloMapId.VOLCANIC_WASTES]: { gold: 800, xp: 2000, guaranteedDropRarity: ItemRarity.EPIC, bonusMessage: 'The flames die down.' },
  [DiabloMapId.ABYSSAL_RIFT]: { gold: 1200, xp: 3000, guaranteedDropRarity: ItemRarity.EPIC, bonusMessage: 'The rift seals shut.' },
  [DiabloMapId.DRAGONS_SANCTUM]: { gold: 2000, xp: 5000, guaranteedDropRarity: ItemRarity.LEGENDARY, bonusMessage: 'The dragons fall silent.' },
  [DiabloMapId.SUNSCORCH_DESERT]: { gold: 150, xp: 400, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The sands grow still.' },
  [DiabloMapId.EMERALD_GRASSLANDS]: { gold: 150, xp: 350, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'Peace returns to the plains.' },
  [DiabloMapId.RIVERSIDE_VILLAGE]: { gold: 120, xp: 300, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The village is safe once more.' },
  [DiabloMapId.WHISPERING_MARSH]: { gold: 175, xp: 420, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The swamp falls silent at last.' },
  [DiabloMapId.CRYSTAL_CAVERNS]: { gold: 200, xp: 500, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The caverns glow with peaceful light.' },
  [DiabloMapId.FROZEN_TUNDRA]: { gold: 400, xp: 1000, guaranteedDropRarity: ItemRarity.RARE, bonusMessage: 'The blizzard subsides at last.' },
  [DiabloMapId.HAUNTED_CATHEDRAL]: { gold: 500, xp: 1200, guaranteedDropRarity: ItemRarity.RARE, bonusMessage: 'The cathedral finds peace once more.' },
  [DiabloMapId.THORNWOOD_THICKET]: { gold: 450, xp: 1100, guaranteedDropRarity: ItemRarity.RARE, bonusMessage: 'The blight recedes from the wood.' },
  [DiabloMapId.CLOCKWORK_FOUNDRY]: { gold: 1000, xp: 2500, guaranteedDropRarity: ItemRarity.EPIC, bonusMessage: 'The machinery grinds to a halt.' },
  [DiabloMapId.CRIMSON_CITADEL]: { gold: 1200, xp: 3000, guaranteedDropRarity: ItemRarity.EPIC, bonusMessage: 'The crimson walls crumble to dust.' },
  [DiabloMapId.STORMSPIRE_PEAK]: { gold: 1500, xp: 3500, guaranteedDropRarity: ItemRarity.EPIC, bonusMessage: 'The storms clear and sunlight breaks through.' },
  [DiabloMapId.SHADOW_REALM]: { gold: 2500, xp: 6000, guaranteedDropRarity: ItemRarity.LEGENDARY, bonusMessage: 'The nightmares dissolve into nothing.' },
  [DiabloMapId.PRIMORDIAL_ABYSS]: { gold: 4000, xp: 10000, guaranteedDropRarity: ItemRarity.LEGENDARY, bonusMessage: 'The abyss is sealed. Reality holds firm.' },
  [DiabloMapId.MOONLIT_GROVE]: { gold: 125, xp: 300, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The moonlight returns to its gentle glow.' },
  [DiabloMapId.CORAL_DEPTHS]: { gold: 175, xp: 450, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The coral reefs pulse with renewed life.' },
  [DiabloMapId.ANCIENT_LIBRARY]: { gold: 250, xp: 600, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The forbidden tomes seal themselves once more.' },
  [DiabloMapId.JADE_TEMPLE]: { gold: 350, xp: 900, guaranteedDropRarity: ItemRarity.RARE, bonusMessage: 'The jade idols fall silent and crumble to dust.' },
  [DiabloMapId.ASHEN_BATTLEFIELD]: { gold: 450, xp: 1100, guaranteedDropRarity: ItemRarity.RARE, bonusMessage: 'The fallen soldiers finally find their rest.' },
  [DiabloMapId.FUNGAL_DEPTHS]: { gold: 900, xp: 2200, guaranteedDropRarity: ItemRarity.EPIC, bonusMessage: 'The toxic spores dissipate into nothing.' },
  [DiabloMapId.OBSIDIAN_FORTRESS]: { gold: 1100, xp: 2800, guaranteedDropRarity: ItemRarity.EPIC, bonusMessage: 'The obsidian walls fracture and collapse.' },
  [DiabloMapId.CELESTIAL_RUINS]: { gold: 2000, xp: 5000, guaranteedDropRarity: ItemRarity.LEGENDARY, bonusMessage: 'The stars realign and the ruins ascend to peace.' },
  [DiabloMapId.INFERNAL_THRONE]: { gold: 3000, xp: 7500, guaranteedDropRarity: ItemRarity.LEGENDARY, bonusMessage: 'The throne shatters and hellfire extinguishes.' },
  [DiabloMapId.ASTRAL_VOID]: { gold: 5000, xp: 12000, guaranteedDropRarity: ItemRarity.LEGENDARY, bonusMessage: 'Reality mends itself. The void between worlds seals shut.' },
  [DiabloMapId.SHATTERED_COLOSSEUM]: { gold: 130, xp: 320, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The phantom crowds fall silent at last.' },
  [DiabloMapId.PETRIFIED_GARDEN]: { gold: 200, xp: 500, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'Color returns to the stone. Life stirs again.' },
  [DiabloMapId.SUNKEN_CITADEL]: { gold: 275, xp: 650, guaranteedDropRarity: ItemRarity.RARE, bonusMessage: 'The waters recede and the citadel sees daylight once more.' },
  [DiabloMapId.WYRMSCAR_CANYON]: { gold: 400, xp: 1000, guaranteedDropRarity: ItemRarity.RARE, bonusMessage: 'The dragonfire fades and the canyon begins to heal.' },
  [DiabloMapId.PLAGUEROT_SEWERS]: { gold: 500, xp: 1200, guaranteedDropRarity: ItemRarity.RARE, bonusMessage: 'The plague dissipates. Clean water flows once more.' },
  [DiabloMapId.ETHEREAL_SANCTUM]: { gold: 1000, xp: 2500, guaranteedDropRarity: ItemRarity.EPIC, bonusMessage: 'The sanctum anchors itself to a single plane.' },
  [DiabloMapId.IRON_WASTES]: { gold: 1200, xp: 3000, guaranteedDropRarity: ItemRarity.EPIC, bonusMessage: 'The war machines power down. Silence reclaims the wastes.' },
  [DiabloMapId.BLIGHTED_THRONE]: { gold: 2200, xp: 5500, guaranteedDropRarity: ItemRarity.LEGENDARY, bonusMessage: 'The crown shatters and the blight withers to nothing.' },
  [DiabloMapId.CHRONO_LABYRINTH]: { gold: 3500, xp: 8000, guaranteedDropRarity: ItemRarity.LEGENDARY, bonusMessage: 'Time straightens. The labyrinth unravels into open space.' },
  [DiabloMapId.ELDRITCH_NEXUS]: { gold: 6000, xp: 15000, guaranteedDropRarity: ItemRarity.LEGENDARY, bonusMessage: 'The nexus collapses. Every dark dimension severs its link.' },
  [DiabloMapId.CITY_RUINS]: { gold: 150, xp: 350, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The ruined streets fall silent. The dead guards rest at last.' },
  [DiabloMapId.CITY]: { gold: 175, xp: 400, guaranteedDropRarity: ItemRarity.UNCOMMON, bonusMessage: 'The corrupt garrison is dismantled. Thornwall breathes free.' },
};

// ---------------------------------------------------------------------------
//  MAP MODIFIERS CONFIG
// ---------------------------------------------------------------------------
export const MAP_MODIFIER_DEFS: Record<string, {
  name: string;
  description: string;
  icon: string;
  color: string;
  dropRateBonus: number; // percentage increase to drop rate
  enemyHpMult: number;
  enemyDamageMult: number;
  enemySpeedMult: number;
  xpBonus: number;
  goldBonus: number;
}> = {
  ENEMY_SPEED: { name: 'Swift', description: 'Enemies are 40% faster', icon: '💨', color: '#44ccff', dropRateBonus: 15, enemyHpMult: 1, enemyDamageMult: 1, enemySpeedMult: 1.4, xpBonus: 15, goldBonus: 10 },
  ENEMY_FIRE_RESIST: { name: 'Fireproof', description: 'Enemies have 50% fire resistance', icon: '🔥', color: '#ff4400', dropRateBonus: 10, enemyHpMult: 1, enemyDamageMult: 1, enemySpeedMult: 1, xpBonus: 10, goldBonus: 5 },
  ENEMY_ICE_RESIST: { name: 'Frostbound', description: 'Enemies have 50% ice resistance', icon: '❄️', color: '#4488ff', dropRateBonus: 10, enemyHpMult: 1, enemyDamageMult: 1, enemySpeedMult: 1, xpBonus: 10, goldBonus: 5 },
  ENEMY_LIGHTNING_RESIST: { name: 'Grounded', description: 'Enemies have 50% lightning resistance', icon: '⚡', color: '#ffdd00', dropRateBonus: 10, enemyHpMult: 1, enemyDamageMult: 1, enemySpeedMult: 1, xpBonus: 10, goldBonus: 5 },
  ENEMY_THORNS: { name: 'Thorns', description: 'Enemies reflect 15% damage back', icon: '🌹', color: '#ff4488', dropRateBonus: 20, enemyHpMult: 1, enemyDamageMult: 1, enemySpeedMult: 1, xpBonus: 20, goldBonus: 15 },
  ENEMY_REGEN: { name: 'Regenerating', description: 'Enemies regenerate 2% HP per second', icon: '💚', color: '#44ff44', dropRateBonus: 15, enemyHpMult: 1, enemyDamageMult: 1, enemySpeedMult: 1, xpBonus: 15, goldBonus: 10 },
  EXTRA_ELITES: { name: 'Champions', description: '50% more elite/boss spawns', icon: '👑', color: '#ffd700', dropRateBonus: 25, enemyHpMult: 1, enemyDamageMult: 1, enemySpeedMult: 1, xpBonus: 25, goldBonus: 20 },
  EXPLOSIVE_DEATH: { name: 'Volatile', description: 'Enemies explode on death for 30% max HP', icon: '💥', color: '#ff8800', dropRateBonus: 15, enemyHpMult: 1, enemyDamageMult: 1, enemySpeedMult: 1, xpBonus: 15, goldBonus: 10 },
  DOUBLE_HP: { name: 'Fortified', description: 'Enemies have double HP', icon: '🛡️', color: '#888888', dropRateBonus: 30, enemyHpMult: 2, enemyDamageMult: 1, enemySpeedMult: 1, xpBonus: 30, goldBonus: 25 },
  VAMPIRIC: { name: 'Vampiric', description: 'Enemies heal 5% of damage dealt', icon: '🧛', color: '#cc0000', dropRateBonus: 20, enemyHpMult: 1, enemyDamageMult: 1, enemySpeedMult: 1, xpBonus: 20, goldBonus: 15 },
};

