// ---------------------------------------------------------------------------
// Warband mode – creature definitions
// Large non-humanoid units (trolls, cyclops, etc.)
// ---------------------------------------------------------------------------

export type CreatureType =
  | "troll"
  | "cyclops"
  // Creature Den
  | "spider"
  | "giant_frog"
  | "rhino"
  | "vampire_bat"
  | "red_dragon"
  | "frost_dragon"
  | "fire_dragon"
  | "ice_dragon"
  | "fire_elemental"
  | "ice_elemental"
  | "earth_elemental"
  | "lightning_elemental"
  | "distortion_elemental"
  | "minor_fire_elemental"
  | "minor_ice_elemental"
  | "minor_lightning_elemental"
  | "minor_distortion_elemental"
  | "minor_earth_elemental"
  | "fire_imp"
  | "ice_imp"
  | "lightning_imp"
  | "distortion_imp"
  | "void_snail"
  | "faery_queen"
  | "devourer"
  | "pixie"
  | "bat"
  // Faction creatures
  | "treant"
  | "siege_troll"
  | "mana_wraith"
  | "elemental_avatar"
  | "storm_conduit"
  | "frost_wyrm"
  | "magma_titan"
  | "stone_fist"
  | "magma_golem"
  | "obsidian_sentinel"
  | "cinder_wraith"
  | "volcanic_behemoth"
  | "bone_colossus"
  | "wraith_lord"
  | "banshee"
  | "pit_lord"
  | "doom_guard"
  | "succubus"
  | "imp_overlord"
  | "seraphim"
  | "archon"
  | "alpha_wolf"
  | "thunderhawk"
  | "dire_bear"
  | "war_golem"
  | "rune_core"
  | "siege_automaton"
  | "crystal_golem"
  | "iron_colossus"
  // Siege Workshop
  | "battering_ram"
  | "catapult"
  | "trebuchet"
  | "ballista"
  // Elite Siege Workshop
  | "cannon"
  | "giant_siege"
  // Extra Siege
  | "bolt_thrower"
  | "siege_catapult"
  | "war_wagon"
  | "bombard"
  | "siege_tower"
  | "hellfire_mortar";

export type CreatureAbilityType =
  | 'fire_breath'
  | 'stomp'
  | 'regenerate'
  | 'explode_on_death'
  | 'poison_aura'
  | 'lightning_strike'
  | 'ice_nova'
  | 'summon';

export interface CreatureSpecialAbility {
  type: CreatureAbilityType;
  cooldownTicks: number;
  damage: number;
  radius: number;
}

export interface CreatureDef {
  type: CreatureType;
  name: string;
  hp: number;
  radius: number;       // collision radius (replaces FIGHTER_RADIUS)
  height: number;       // visual height
  scale: number;        // overall scale multiplier vs human (1.0)
  speed: number;        // walk speed (absolute, not multiplier)
  damage: number;       // base melee damage (no weapon)
  reach: number;        // melee reach
  attackTicks: number;  // windup ticks (slower than humans)
  releaseTicks: number; // release window ticks
  specialAbility?: CreatureSpecialAbility;
}

export const CREATURE_DEFS: Record<CreatureType, CreatureDef> = {
  troll: {
    type: "troll",
    name: "Troll",
    hp: 400,
    radius: 1.6,
    height: 7.0,
    scale: 4.0,
    speed: 2.8,
    damage: 55,
    reach: 3.0,
    attackTicks: 24,
    releaseTicks: 10,
    specialAbility: { type: 'regenerate', cooldownTicks: 60, damage: 5, radius: 0 },
  },
  cyclops: {
    type: "cyclops",
    name: "Cyclops",
    hp: 650,
    radius: 4.4,
    height: 20.0,
    scale: 11.2,
    speed: 2.2,
    damage: 80,
    reach: 3.8,
    attackTicks: 30,
    releaseTicks: 12,
  },

  // ---- Creature Den ----

  spider: {
    type: "spider",
    name: "Spider",
    hp: 65,
    radius: 0.5,
    height: 1.2,
    scale: 1.0,
    speed: 4.0,
    damage: 12,
    reach: 1.5,
    attackTicks: 12,
    releaseTicks: 6,
  },
  giant_frog: {
    type: "giant_frog",
    name: "Giant Frog",
    hp: 200,
    radius: 0.7,
    height: 1.8,
    scale: 1.4,
    speed: 3.0,
    damage: 18,
    reach: 3.5,
    attackTicks: 16,
    releaseTicks: 6,
  },
  rhino: {
    type: "rhino",
    name: "Rhino",
    hp: 350,
    radius: 0.9,
    height: 2.5,
    scale: 1.8,
    speed: 3.5,
    damage: 35,
    reach: 2.0,
    attackTicks: 20,
    releaseTicks: 8,
  },
  vampire_bat: {
    type: "vampire_bat",
    name: "Vampire Bat",
    hp: 350,
    radius: 0.7,
    height: 3.0,
    scale: 1.6,
    speed: 4.5,
    damage: 30,
    reach: 2.0,
    attackTicks: 14,
    releaseTicks: 6,
  },
  red_dragon: {
    type: "red_dragon",
    name: "Red Dragon",
    hp: 500,
    radius: 2.4,
    height: 9.0,
    scale: 5.0,
    speed: 2.5,
    damage: 65,
    reach: 3.5,
    attackTicks: 26,
    releaseTicks: 10,
    specialAbility: { type: 'fire_breath', cooldownTicks: 600, damage: 40, radius: 5 },
  },
  fire_elemental: {
    type: "fire_elemental",
    name: "Fire Elemental",
    hp: 450,
    radius: 0.8,
    height: 4.0,
    scale: 2.2,
    speed: 2.8,
    damage: 50,
    reach: 2.5,
    attackTicks: 20,
    releaseTicks: 8,
    specialAbility: { type: 'explode_on_death', cooldownTicks: 0, damage: 30, radius: 3 },
  },
  ice_elemental: {
    type: "ice_elemental",
    name: "Ice Elemental",
    hp: 400,
    radius: 0.8,
    height: 4.0,
    scale: 2.2,
    speed: 2.4,
    damage: 45,
    reach: 2.8,
    attackTicks: 22,
    releaseTicks: 10,
    specialAbility: { type: 'ice_nova', cooldownTicks: 900, damage: 20, radius: 4 },
  },
  earth_elemental: {
    type: "earth_elemental",
    name: "Earth Elemental",
    hp: 600,
    radius: 1.0,
    height: 4.2,
    scale: 2.4,
    speed: 1.8,
    damage: 55,
    reach: 2.5,
    attackTicks: 28,
    releaseTicks: 12,
    specialAbility: { type: 'stomp', cooldownTicks: 480, damage: 25, radius: 3 },
  },

  frost_dragon: {
    type: "frost_dragon",
    name: "Frost Dragon",
    hp: 480,
    radius: 2.4,
    height: 9.0,
    scale: 5.0,
    speed: 2.5,
    damage: 60,
    reach: 3.5,
    attackTicks: 26,
    releaseTicks: 10,
    specialAbility: { type: 'ice_nova', cooldownTicks: 900, damage: 20, radius: 4 },
  },
  fire_dragon: {
    type: "fire_dragon",
    name: "Fire Dragon",
    hp: 900,
    radius: 6.0,
    height: 22.0,
    scale: 12.0,
    speed: 2.2,
    damage: 90,
    reach: 4.0,
    attackTicks: 30,
    releaseTicks: 12,
    specialAbility: { type: 'fire_breath', cooldownTicks: 600, damage: 40, radius: 5 },
  },
  ice_dragon: {
    type: "ice_dragon",
    name: "Ice Dragon",
    hp: 850,
    radius: 6.0,
    height: 22.0,
    scale: 12.0,
    speed: 2.2,
    damage: 85,
    reach: 4.0,
    attackTicks: 30,
    releaseTicks: 12,
    specialAbility: { type: 'ice_nova', cooldownTicks: 900, damage: 20, radius: 4 },
  },
  lightning_elemental: {
    type: "lightning_elemental",
    name: "Lightning Elemental",
    hp: 400,
    radius: 0.8,
    height: 4.0,
    scale: 2.2,
    speed: 3.2,
    damage: 48,
    reach: 2.5,
    attackTicks: 16,
    releaseTicks: 6,
    specialAbility: { type: 'lightning_strike', cooldownTicks: 600, damage: 35, radius: 0 },
  },
  distortion_elemental: {
    type: "distortion_elemental",
    name: "Distortion Elemental",
    hp: 380,
    radius: 0.8,
    height: 4.0,
    scale: 2.2,
    speed: 2.6,
    damage: 42,
    reach: 3.0,
    attackTicks: 22,
    releaseTicks: 10,
  },
  minor_fire_elemental: {
    type: "minor_fire_elemental",
    name: "Minor Fire Elemental",
    hp: 200,
    radius: 0.5,
    height: 2.5,
    scale: 1.4,
    speed: 3.0,
    damage: 25,
    reach: 2.0,
    attackTicks: 16,
    releaseTicks: 6,
  },
  minor_ice_elemental: {
    type: "minor_ice_elemental",
    name: "Minor Ice Elemental",
    hp: 180,
    radius: 0.5,
    height: 2.5,
    scale: 1.4,
    speed: 2.6,
    damage: 22,
    reach: 2.2,
    attackTicks: 18,
    releaseTicks: 8,
  },
  minor_lightning_elemental: {
    type: "minor_lightning_elemental",
    name: "Minor Lightning Elemental",
    hp: 190,
    radius: 0.5,
    height: 2.5,
    scale: 1.4,
    speed: 3.4,
    damage: 24,
    reach: 2.0,
    attackTicks: 14,
    releaseTicks: 6,
  },
  minor_distortion_elemental: {
    type: "minor_distortion_elemental",
    name: "Minor Distortion Elemental",
    hp: 170,
    radius: 0.5,
    height: 2.5,
    scale: 1.4,
    speed: 2.8,
    damage: 20,
    reach: 2.2,
    attackTicks: 18,
    releaseTicks: 8,
  },
  minor_earth_elemental: {
    type: "minor_earth_elemental",
    name: "Minor Earth Elemental",
    hp: 280,
    radius: 0.6,
    height: 2.8,
    scale: 1.5,
    speed: 2.0,
    damage: 28,
    reach: 2.0,
    attackTicks: 22,
    releaseTicks: 10,
  },
  fire_imp: {
    type: "fire_imp",
    name: "Fire Imp",
    hp: 35,
    radius: 0.3,
    height: 1.0,
    scale: 0.7,
    speed: 5.0,
    damage: 10,
    reach: 1.5,
    attackTicks: 10,
    releaseTicks: 4,
  },
  ice_imp: {
    type: "ice_imp",
    name: "Ice Imp",
    hp: 35,
    radius: 0.3,
    height: 1.0,
    scale: 0.7,
    speed: 5.0,
    damage: 10,
    reach: 1.5,
    attackTicks: 10,
    releaseTicks: 4,
  },
  lightning_imp: {
    type: "lightning_imp",
    name: "Lightning Imp",
    hp: 35,
    radius: 0.3,
    height: 1.0,
    scale: 0.7,
    speed: 5.0,
    damage: 10,
    reach: 1.5,
    attackTicks: 10,
    releaseTicks: 4,
  },
  distortion_imp: {
    type: "distortion_imp",
    name: "Distortion Imp",
    hp: 35,
    radius: 0.3,
    height: 1.0,
    scale: 0.7,
    speed: 5.0,
    damage: 10,
    reach: 1.5,
    attackTicks: 10,
    releaseTicks: 4,
  },
  void_snail: {
    type: "void_snail",
    name: "Void Snail",
    hp: 120,
    radius: 0.5,
    height: 1.5,
    scale: 1.2,
    speed: 1.5,
    damage: 8,
    reach: 2.0,
    attackTicks: 24,
    releaseTicks: 10,
  },
  faery_queen: {
    type: "faery_queen",
    name: "Faery Queen",
    hp: 80,
    radius: 0.4,
    height: 2.0,
    scale: 1.0,
    speed: 4.0,
    damage: 20,
    reach: 3.0,
    attackTicks: 16,
    releaseTicks: 6,
  },
  devourer: {
    type: "devourer",
    name: "Devourer",
    hp: 350,
    radius: 0.8,
    height: 2.5,
    scale: 1.8,
    speed: 2.0,
    damage: 25,
    reach: 3.5,
    attackTicks: 22,
    releaseTicks: 10,
  },
  pixie: {
    type: "pixie",
    name: "Pixie",
    hp: 40,
    radius: 0.2,
    height: 0.8,
    scale: 0.5,
    speed: 5.5,
    damage: 8,
    reach: 1.5,
    attackTicks: 8,
    releaseTicks: 4,
  },
  bat: {
    type: "bat",
    name: "Bat",
    hp: 30,
    radius: 0.3,
    height: 0.8,
    scale: 0.6,
    speed: 5.5,
    damage: 10,
    reach: 1.2,
    attackTicks: 8,
    releaseTicks: 4,
  },

  // ---- Faction Creatures ----

  treant: {
    type: "treant",
    name: "Treant Guardian",
    hp: 350,
    radius: 1.0,
    height: 4.5,
    scale: 2.5,
    speed: 1.8,
    damage: 40,
    reach: 3.0,
    attackTicks: 28,
    releaseTicks: 12,
  },
  siege_troll: {
    type: "siege_troll",
    name: "Siege Troll",
    hp: 500,
    radius: 2.0,
    height: 8.0,
    scale: 4.8,
    speed: 2.0,
    damage: 65,
    reach: 3.5,
    attackTicks: 30,
    releaseTicks: 12,
    specialAbility: { type: 'regenerate', cooldownTicks: 60, damage: 5, radius: 0 },
  },
  mana_wraith: {
    type: "mana_wraith",
    name: "Mana Wraith",
    hp: 120,
    radius: 0.6,
    height: 3.0,
    scale: 1.6,
    speed: 3.5,
    damage: 30,
    reach: 2.5,
    attackTicks: 16,
    releaseTicks: 6,
  },
  elemental_avatar: {
    type: "elemental_avatar",
    name: "Elemental Avatar",
    hp: 600,
    radius: 1.2,
    height: 5.0,
    scale: 2.8,
    speed: 2.2,
    damage: 60,
    reach: 3.0,
    attackTicks: 24,
    releaseTicks: 10,
  },
  storm_conduit: {
    type: "storm_conduit",
    name: "Storm Conduit",
    hp: 350,
    radius: 0.8,
    height: 4.0,
    scale: 2.2,
    speed: 3.0,
    damage: 45,
    reach: 2.8,
    attackTicks: 18,
    releaseTicks: 8,
    specialAbility: { type: 'lightning_strike', cooldownTicks: 600, damage: 35, radius: 0 },
  },
  frost_wyrm: {
    type: "frost_wyrm",
    name: "Frost Wyrm",
    hp: 550,
    radius: 1.4,
    height: 4.5,
    scale: 2.6,
    speed: 2.4,
    damage: 55,
    reach: 3.5,
    attackTicks: 26,
    releaseTicks: 10,
    specialAbility: { type: 'ice_nova', cooldownTicks: 900, damage: 20, radius: 4 },
  },
  magma_titan: {
    type: "magma_titan",
    name: "Magma Titan",
    hp: 800,
    radius: 1.5,
    height: 6.0,
    scale: 3.2,
    speed: 1.5,
    damage: 75,
    reach: 3.5,
    attackTicks: 32,
    releaseTicks: 14,
  },
  stone_fist: {
    type: "stone_fist",
    name: "Stone Fist",
    hp: 400,
    radius: 0.9,
    height: 3.5,
    scale: 2.0,
    speed: 2.0,
    damage: 50,
    reach: 2.5,
    attackTicks: 24,
    releaseTicks: 10,
  },
  magma_golem: {
    type: "magma_golem",
    name: "Magma Golem",
    hp: 450,
    radius: 1.0,
    height: 3.8,
    scale: 2.2,
    speed: 1.8,
    damage: 50,
    reach: 2.5,
    attackTicks: 26,
    releaseTicks: 10,
    specialAbility: { type: 'stomp', cooldownTicks: 600, damage: 30, radius: 3.5 },
  },
  obsidian_sentinel: {
    type: "obsidian_sentinel",
    name: "Obsidian Sentinel",
    hp: 500,
    radius: 1.0,
    height: 4.0,
    scale: 2.2,
    speed: 1.6,
    damage: 55,
    reach: 2.5,
    attackTicks: 28,
    releaseTicks: 12,
  },
  cinder_wraith: {
    type: "cinder_wraith",
    name: "Cinder Wraith",
    hp: 100,
    radius: 0.5,
    height: 2.8,
    scale: 1.4,
    speed: 4.5,
    damage: 25,
    reach: 2.0,
    attackTicks: 12,
    releaseTicks: 6,
  },
  volcanic_behemoth: {
    type: "volcanic_behemoth",
    name: "Volcanic Behemoth",
    hp: 900,
    radius: 1.8,
    height: 6.5,
    scale: 3.5,
    speed: 1.2,
    damage: 85,
    reach: 4.0,
    attackTicks: 35,
    releaseTicks: 14,
  },
  bone_colossus: {
    type: "bone_colossus",
    name: "Bone Colossus",
    hp: 700,
    radius: 1.5,
    height: 6.0,
    scale: 3.2,
    speed: 1.4,
    damage: 70,
    reach: 3.5,
    attackTicks: 32,
    releaseTicks: 12,
  },
  wraith_lord: {
    type: "wraith_lord",
    name: "Wraith Lord",
    hp: 200,
    radius: 0.8,
    height: 3.5,
    scale: 1.8,
    speed: 3.0,
    damage: 40,
    reach: 3.0,
    attackTicks: 18,
    releaseTicks: 8,
  },
  banshee: {
    type: "banshee",
    name: "Banshee",
    hp: 80,
    radius: 0.5,
    height: 2.5,
    scale: 1.4,
    speed: 4.0,
    damage: 20,
    reach: 2.5,
    attackTicks: 14,
    releaseTicks: 6,
  },
  pit_lord: {
    type: "pit_lord",
    name: "Pit Lord",
    hp: 650,
    radius: 1.3,
    height: 5.5,
    scale: 3.0,
    speed: 2.0,
    damage: 70,
    reach: 3.5,
    attackTicks: 28,
    releaseTicks: 12,
  },
  doom_guard: {
    type: "doom_guard",
    name: "Doom Guard",
    hp: 400,
    radius: 1.0,
    height: 4.5,
    scale: 2.4,
    speed: 2.4,
    damage: 55,
    reach: 3.0,
    attackTicks: 22,
    releaseTicks: 10,
  },
  succubus: {
    type: "succubus",
    name: "Succubus",
    hp: 150,
    radius: 0.5,
    height: 2.8,
    scale: 1.4,
    speed: 3.8,
    damage: 30,
    reach: 2.5,
    attackTicks: 14,
    releaseTicks: 6,
  },
  imp_overlord: {
    type: "imp_overlord",
    name: "Imp Overlord",
    hp: 130,
    radius: 0.5,
    height: 2.0,
    scale: 1.2,
    speed: 4.0,
    damage: 22,
    reach: 2.0,
    attackTicks: 12,
    releaseTicks: 6,
  },
  seraphim: {
    type: "seraphim",
    name: "Seraphim",
    hp: 300,
    radius: 0.8,
    height: 4.0,
    scale: 2.0,
    speed: 3.0,
    damage: 35,
    reach: 3.0,
    attackTicks: 18,
    releaseTicks: 8,
  },
  archon: {
    type: "archon",
    name: "Archon",
    hp: 350,
    radius: 0.9,
    height: 4.2,
    scale: 2.2,
    speed: 2.6,
    damage: 50,
    reach: 3.0,
    attackTicks: 22,
    releaseTicks: 10,
  },
  alpha_wolf: {
    type: "alpha_wolf",
    name: "Alpha Wolf",
    hp: 180,
    radius: 0.6,
    height: 1.8,
    scale: 1.4,
    speed: 5.0,
    damage: 28,
    reach: 1.8,
    attackTicks: 10,
    releaseTicks: 4,
  },
  thunderhawk: {
    type: "thunderhawk",
    name: "Thunderhawk",
    hp: 120,
    radius: 0.5,
    height: 2.5,
    scale: 1.6,
    speed: 5.5,
    damage: 22,
    reach: 2.0,
    attackTicks: 10,
    releaseTicks: 4,
  },
  dire_bear: {
    type: "dire_bear",
    name: "Dire Bear",
    hp: 500,
    radius: 1.2,
    height: 3.0,
    scale: 2.2,
    speed: 2.5,
    damage: 55,
    reach: 2.5,
    attackTicks: 22,
    releaseTicks: 10,
  },
  war_golem: {
    type: "war_golem",
    name: "War Golem",
    hp: 550,
    radius: 1.2,
    height: 4.5,
    scale: 2.5,
    speed: 1.5,
    damage: 60,
    reach: 3.0,
    attackTicks: 28,
    releaseTicks: 12,
    specialAbility: { type: 'stomp', cooldownTicks: 600, damage: 30, radius: 3.5 },
  },
  rune_core: {
    type: "rune_core",
    name: "Rune Core",
    hp: 200,
    radius: 0.6,
    height: 2.5,
    scale: 1.4,
    speed: 2.5,
    damage: 35,
    reach: 3.0,
    attackTicks: 20,
    releaseTicks: 8,
  },
  siege_automaton: {
    type: "siege_automaton",
    name: "Siege Automaton",
    hp: 700,
    radius: 1.5,
    height: 6.0,
    scale: 3.2,
    speed: 1.2,
    damage: 80,
    reach: 3.5,
    attackTicks: 32,
    releaseTicks: 14,
  },
  crystal_golem: {
    type: "crystal_golem",
    name: "Crystal Golem",
    hp: 350,
    radius: 0.8,
    height: 3.5,
    scale: 2.0,
    speed: 2.2,
    damage: 45,
    reach: 2.5,
    attackTicks: 22,
    releaseTicks: 10,
    specialAbility: { type: 'stomp', cooldownTicks: 600, damage: 30, radius: 3.5 },
  },
  iron_colossus: {
    type: "iron_colossus",
    name: "Iron Colossus",
    hp: 800,
    radius: 1.6,
    height: 6.5,
    scale: 3.5,
    speed: 1.2,
    damage: 85,
    reach: 4.0,
    attackTicks: 34,
    releaseTicks: 14,
    specialAbility: { type: 'stomp', cooldownTicks: 600, damage: 30, radius: 3.5 },
  },

  // ---- Siege Workshop ----

  battering_ram: {
    type: "battering_ram",
    name: "Battering Ram",
    hp: 300,
    radius: 0.8,
    height: 2.0,
    scale: 1.8,
    speed: 1.5,
    damage: 60,
    reach: 2.5,
    attackTicks: 30,
    releaseTicks: 10,
  },
  catapult: {
    type: "catapult",
    name: "Catapult",
    hp: 150,
    radius: 0.9,
    height: 2.5,
    scale: 1.8,
    speed: 1.0,
    damage: 45,
    reach: 5.0,
    attackTicks: 40,
    releaseTicks: 8,
  },
  trebuchet: {
    type: "trebuchet",
    name: "Trebuchet",
    hp: 250,
    radius: 1.2,
    height: 4.0,
    scale: 2.5,
    speed: 0.6,
    damage: 80,
    reach: 8.0,
    attackTicks: 50,
    releaseTicks: 10,
  },
  ballista: {
    type: "ballista",
    name: "Ballista",
    hp: 120,
    radius: 0.7,
    height: 2.0,
    scale: 1.5,
    speed: 1.2,
    damage: 55,
    reach: 6.0,
    attackTicks: 24,
    releaseTicks: 6,
  },

  // ---- Elite Siege Workshop ----

  cannon: {
    type: "cannon",
    name: "Cannon",
    hp: 400,
    radius: 0.8,
    height: 2.0,
    scale: 1.6,
    speed: 0.8,
    damage: 140,
    reach: 7.0,
    attackTicks: 60,
    releaseTicks: 8,
  },
  giant_siege: {
    type: "giant_siege",
    name: "Siege Giant",
    hp: 1500,
    radius: 2.6,
    height: 12.0,
    scale: 6.4,
    speed: 1.5,
    damage: 130,
    reach: 4.0,
    attackTicks: 35,
    releaseTicks: 14,
  },

  // ---- Extra Siege ----

  bolt_thrower: {
    type: "bolt_thrower",
    name: "Bolt Thrower",
    hp: 200,
    radius: 0.9,
    height: 2.2,
    scale: 1.8,
    speed: 0.9,
    damage: 65,
    reach: 7.0,
    attackTicks: 28,
    releaseTicks: 8,
  },
  siege_catapult: {
    type: "siege_catapult",
    name: "Siege Catapult",
    hp: 300,
    radius: 1.2,
    height: 2.8,
    scale: 2.2,
    speed: 0.6,
    damage: 75,
    reach: 6.0,
    attackTicks: 45,
    releaseTicks: 10,
  },
  war_wagon: {
    type: "war_wagon",
    name: "War Wagon",
    hp: 600,
    radius: 1.2,
    height: 2.5,
    scale: 2.2,
    speed: 1.2,
    damage: 50,
    reach: 5.5,
    attackTicks: 22,
    releaseTicks: 8,
  },
  bombard: {
    type: "bombard",
    name: "Bombard",
    hp: 350,
    radius: 1.0,
    height: 2.0,
    scale: 2.0,
    speed: 0.5,
    damage: 120,
    reach: 7.5,
    attackTicks: 70,
    releaseTicks: 8,
  },
  siege_tower: {
    type: "siege_tower",
    name: "Siege Tower",
    hp: 900,
    radius: 1.5,
    height: 7.0,
    scale: 3.5,
    speed: 0.5,
    damage: 80,
    reach: 2.5,
    attackTicks: 30,
    releaseTicks: 12,
  },
  hellfire_mortar: {
    type: "hellfire_mortar",
    name: "Hellfire Mortar",
    hp: 450,
    radius: 1.0,
    height: 2.0,
    scale: 2.0,
    speed: 0.4,
    damage: 140,
    reach: 9.0,
    attackTicks: 80,
    releaseTicks: 8,
  },
};
