// Balance and world configuration for Medieval GTA 3D

export const GTA3D = {
  // Movement
  WALK_SPEED: 4.0,
  RUN_SPEED: 7.5,
  HORSE_SPEED: 14.0,
  ROLL_SPEED: 10.0,
  ROLL_DURATION: 0.35,

  // Combat
  FIST_DAMAGE: 8,
  SWORD_DAMAGE: 25,
  AXE_DAMAGE: 35,
  MACE_DAMAGE: 30,
  SPEAR_DAMAGE: 22,
  BOW_DAMAGE: 18,
  CROSSBOW_DAMAGE: 30,
  ATTACK_COOLDOWN_FIST: 0.35,
  ATTACK_COOLDOWN_SWORD: 0.55,
  ATTACK_COOLDOWN_AXE: 0.8,
  ATTACK_COOLDOWN_MACE: 0.7,
  ATTACK_COOLDOWN_SPEAR: 0.6,
  ATTACK_COOLDOWN_BOW: 0.9,
  ATTACK_COOLDOWN_CROSSBOW: 1.4,
  ATTACK_RANGE_MELEE: 2.5,
  ATTACK_RANGE_SPEAR: 3.5,
  ATTACK_RANGE_BOW: 40,
  BLOCK_REDUCTION: 0.75,

  // Player
  PLAYER_MAX_HP: 100,
  STAMINA_MAX: 100,
  STAMINA_DRAIN: 25,
  STAMINA_REGEN: 15,
  INVINCIBLE_DURATION: 0.4,

  // NPCs
  GUARD_HP: 80,
  KNIGHT_HP: 150,
  CIVILIAN_HP: 30,
  CRIMINAL_HP: 50,
  ARCHER_HP: 60,
  BANDIT_HP: 60,
  GUARD_ALERT_RADIUS: 15,
  GUARD_AGGRO_RADIUS: 10,
  GUARD_CHASE_SPEED: 5.5,
  KNIGHT_CHASE_SPEED: 6.0,
  NPC_WANDER_SPEED: 1.5,
  NPC_WANDER_RADIUS: 8,
  NPC_FLEE_SPEED: 5.5,
  NPC_ATTACK_RANGE: 2.5,

  // Wanted
  WANTED_DECAY_TIME: 30,
  WANTED_MAX: 5,
  WANTED_ALERT_RADIUS_PER_STAR: 5,

  // Horse
  HORSE_HP: 80,
  HORSE_STEAL_RANGE: 3,
  HORSE_MOUNT_RANGE: 3,

  // World (3D units)
  WORLD_SIZE: 200,
  CITY_CENTER: { x: 0, y: 0, z: 0 },
  CITY_RADIUS: 60,
  WALL_HEIGHT: 6,
  WALL_THICKNESS: 1.5,
  GATE_WIDTH: 8,

  // Camera
  CAMERA_HEIGHT: 18,
  CAMERA_DISTANCE: 22,
  CAMERA_LERP: 0.06,
  CAMERA_ANGLE: Math.PI / 5, // tilt angle

  // Day/Night
  DAY_CYCLE_SPEED: 0.002,

  // Interaction
  INTERACT_RANGE: 3,
  DIALOG_COOLDOWN: 0.5,
  PICKUP_RANGE: 2,
  HEALTH_POTION_HEAL: 30,

  // Notification
  NOTIFICATION_DURATION: 3.0,

  // SIM
  SIM_TICK_MS: 16,
};
