// Per-player state: gold, owned buildings, base, direction
import type { Direction, PlayerId, PlayerSlot } from "@/types";
import { AIPersonality } from "@/types";
import { BalanceConfig } from "@sim/config/BalanceConfig";

export interface PlayerState {
  id: PlayerId;
  gold: number; // Always a whole integer — spend/receive in whole gold only
  goldAccum: number; // Sub-integer accumulator for income ticks (not displayed)
  mana: number; // Whole integer mana resource (generated by Archive buildings)
  manaAccum: number; // Sub-integer accumulator for mana income ticks
  direction: Direction; // Which side of the battlefield this player controls
  slot: PlayerSlot; // Map corner slot (nw/ne/sw/se)
  isAI: boolean; // Whether this player is AI-controlled
  aiPersonality: AIPersonality; // AI behavior variant (only used when isAI = true)
  ownedBaseId: string | null; // The player's main Base ID
  ownedBuildings: string[]; // Building IDs this player owns
}

/**
 * @param id        - Unique player identifier.
 * @param direction - Side the player controls (WEST or EAST).
 * @param startGold - Starting gold (defaults to BalanceConfig.START_GOLD).
 * @param slot      - Map corner slot (defaults to "nw").
 * @param isAI      - Whether this player is AI-controlled (defaults to false).
 */
export function createPlayerState(
  id: PlayerId,
  direction: Direction,
  startGold: number = BalanceConfig.START_GOLD,
  slot: PlayerSlot = "nw",
  isAI: boolean = false,
): PlayerState {
  return {
    id,
    gold: Math.floor(startGold),
    goldAccum: 0,
    mana: 0,
    manaAccum: 0,
    direction,
    slot,
    isAI,
    aiPersonality: AIPersonality.BALANCED,
    ownedBaseId: null,
    ownedBuildings: [],
  };
}
