// Building types, costs, shop inventories, placement rules
import { BuildingType, UnitType } from "@/types";
import type { BuildingTurret } from "@sim/entities/Building";

/** Which territory zone a building may be placed in. */
export type PlacementZone = "own" | "neutral" | "any";

export interface BuildingDef {
  type: BuildingType;
  cost: number; // gold cost (0 = starting/Castle)
  hp: number;
  goldIncome: number; // additional gold/sec this building contributes when owned/captured
  shopInventory: UnitType[]; // unit types this building can train
  blueprints: BuildingType[]; // building blueprints sold from this building's shop
  footprint: { w: number; h: number };
  placementZone: PlacementZone;
  /** If true, enemy units can recapture this building even after it is owned. */
  capturable?: boolean;
  /** Turrets the building starts with (omit attackTimer/targetId — set to 0/null at spawn). */
  defaultTurrets?: Omit<BuildingTurret, "attackTimer" | "targetId">[];
  /** Maximum number of this building type a single player may own at once. */
  maxCount?: number;
  /** Blueprint is only purchasable once the player owns at least minCount of the given type(s). */
  prerequisite?: { types: BuildingType[]; minCount: number };
}

export const BUILDING_DEFINITIONS: Record<BuildingType, BuildingDef> = {
  [BuildingType.CASTLE]: {
    type: BuildingType.CASTLE,
    cost: 0,
    hp: 500,
    goldIncome: 2,
    shopInventory: [UnitType.SWORDSMAN, UnitType.ARCHER],
    blueprints: [
      BuildingType.BARRACKS,
      BuildingType.STABLES,
      BuildingType.MAGE_TOWER,
      BuildingType.ARCHERY_RANGE,
      BuildingType.SIEGE_WORKSHOP,
      BuildingType.BLACKSMITH,
      BuildingType.CREATURE_DEN,
      BuildingType.TOWER,
      BuildingType.FARM,
      BuildingType.HAMLET,
      BuildingType.EMBASSY,
      BuildingType.TEMPLE,
      BuildingType.WALL,
      BuildingType.MILL,
      BuildingType.ELITE_HALL,
      BuildingType.MARKET,
    ],
    footprint: { w: 4, h: 4 },
    placementZone: "own",
    defaultTurrets: [
      { projectileTag: "arrow", damage: 12, range: 6, attackSpeed: 1.0 },
    ],
  },
  [BuildingType.BARRACKS]: {
    type: BuildingType.BARRACKS,
    cost: 100,
    hp: 200,
    goldIncome: 1,
    shopInventory: [
      UnitType.SWORDSMAN,
      UnitType.PIKEMAN,
      UnitType.KNIGHT,
      UnitType.MAGE_HUNTER,
      UnitType.GLADIATOR,
    ],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
  },
  [BuildingType.STABLES]: {
    type: BuildingType.STABLES,
    cost: 120,
    hp: 200,
    goldIncome: 1,
    shopInventory: [
      UnitType.KNIGHT,
      UnitType.SIEGE_HUNTER,
      UnitType.HORSE_ARCHER,
      UnitType.SCOUT_CAVALRY,
      UnitType.LANCER,
      UnitType.ELITE_LANCER,
      UnitType.KNIGHT_LANCER,
    ],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
    prerequisite: { types: [BuildingType.BARRACKS], minCount: 1 },
  },
  [BuildingType.MAGE_TOWER]: {
    type: BuildingType.MAGE_TOWER,
    cost: 150,
    hp: 180,
    goldIncome: 2,
    shopInventory: [
      UnitType.FIRE_MAGE,
      UnitType.STORM_MAGE,
      UnitType.COLD_MAGE,
      UnitType.DISTORTION_MAGE,
      UnitType.SUMMONER,
    ],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
  },
  [BuildingType.ARCHERY_RANGE]: {
    type: BuildingType.ARCHERY_RANGE,
    cost: 100,
    hp: 150,
    goldIncome: 1,
    shopInventory: [UnitType.ARCHER, UnitType.CROSSBOWMAN, UnitType.LONGBOWMAN],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
  },
  [BuildingType.SIEGE_WORKSHOP]: {
    type: BuildingType.SIEGE_WORKSHOP,
    cost: 120,
    hp: 180,
    goldIncome: 1,
    shopInventory: [UnitType.BALLISTA, UnitType.BATTERING_RAM],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
  },
  [BuildingType.BLACKSMITH]: {
    type: BuildingType.BLACKSMITH,
    cost: 100,
    hp: 150,
    goldIncome: 2,
    shopInventory: [],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
    prerequisite: { types: [BuildingType.BARRACKS], minCount: 1 },
  },
  [BuildingType.TOWN]: {
    type: BuildingType.TOWN,
    cost: 0,
    hp: 200,
    goldIncome: 3,
    shopInventory: [],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "neutral",
    capturable: true,
  },
  [BuildingType.CREATURE_DEN]: {
    type: BuildingType.CREATURE_DEN,
    cost: 130,
    hp: 200,
    goldIncome: 1,
    shopInventory: [
      UnitType.SPIDER,
      UnitType.VOID_SNAIL,
      UnitType.FAERY_QUEEN,
      UnitType.GIANT_FROG,
      UnitType.DEVOURER,
      UnitType.RED_DRAGON,
      UnitType.FROST_DRAGON,
    ],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
  },
  [BuildingType.TOWER]: {
    type: BuildingType.TOWER,
    cost: 80,
    hp: 250,
    goldIncome: 0,
    shopInventory: [],
    blueprints: [],
    footprint: { w: 1, h: 1 },
    placementZone: "own",
    capturable: true,
    defaultTurrets: [
      { projectileTag: "arrow", damage: 9, range: 6, attackSpeed: 1.0 },
    ],
  },
  [BuildingType.FARM]: {
    type: BuildingType.FARM,
    cost: 120,
    hp: 150,
    goldIncome: 3,
    shopInventory: [],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
    capturable: true,
    maxCount: 5,
  },
  [BuildingType.HAMLET]: {
    type: BuildingType.HAMLET,
    cost: 200,
    hp: 200,
    goldIncome: 5,
    shopInventory: [],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
    maxCount: 1,
    prerequisite: { types: [BuildingType.FARM], minCount: 5 },
  },
  [BuildingType.EMBASSY]: {
    type: BuildingType.EMBASSY,
    cost: 120,
    hp: 200,
    goldIncome: 1,
    shopInventory: [UnitType.DIPLOMAT],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
    maxCount: 2,
  },
  [BuildingType.TEMPLE]: {
    type: BuildingType.TEMPLE,
    cost: 150,
    hp: 200,
    goldIncome: 1,
    shopInventory: [UnitType.MONK, UnitType.CLERIC, UnitType.SAINT],
    blueprints: [],
    footprint: { w: 2, h: 3 },
    placementZone: "own",
  },
  [BuildingType.WALL]: {
    type: BuildingType.WALL,
    cost: 50,
    hp: 500,
    goldIncome: 0,
    shopInventory: [],
    blueprints: [],
    footprint: { w: 1, h: 3 },
    placementZone: "own",
    capturable: false,
  },
  [BuildingType.FIREPIT]: {
    type: BuildingType.FIREPIT,
    cost: 0,
    hp: 100,
    goldIncome: 0,
    shopInventory: [],
    blueprints: [],
    footprint: { w: 2, h: 1 },
    placementZone: "any",
    capturable: false,
  },
  [BuildingType.MILL]: {
    type: BuildingType.MILL,
    cost: 200,
    hp: 300,
    goldIncome: 5,
    shopInventory: [],
    blueprints: [],
    footprint: { w: 1, h: 2 },
    placementZone: "own",
    capturable: false,
  },
  [BuildingType.ELITE_HALL]: {
    type: BuildingType.ELITE_HALL,
    cost: 300,
    hp: 400,
    goldIncome: 8,
    shopInventory: [],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
    capturable: false,
    prerequisite: {
      types: [BuildingType.MAGE_TOWER, BuildingType.BLACKSMITH],
      minCount: 1,
    },
  },
  [BuildingType.MARKET]: {
    type: BuildingType.MARKET,
    cost: 250,
    hp: 250,
    goldIncome: 10,
    shopInventory: [],
    blueprints: [],
    footprint: { w: 2, h: 2 },
    placementZone: "own",
    capturable: false,
  },
};
