// Stats, costs, animation keys for all unit types
import { UnitType, AbilityType } from "@/types";

export interface UnitDef {
  type: UnitType;
  cost: number; // gold cost to train
  hp: number;
  atk: number; // damage per hit
  attackSpeed: number; // attacks per second
  speed: number; // tiles per second
  range: number; // attack range in tiles
  spawnTime: number; // seconds to train
  abilityTypes: AbilityType[];
  spriteKey: string;
  /** If true, unit ignores enemy units and only attacks buildings/bases. */
  siegeOnly?: boolean;
  /** If set, unit always prefers the nearest enemy of these types over all others. */
  huntTargets?: UnitType[];
  /** If true, unit ignores all combat and only seeks neutral buildings to capture. */
  diplomatOnly?: boolean;
  /** Visual size properties for rendering */
  size?: {
    width: number; // multiplier for sprite width (1.0 = normal)
    height: number; // multiplier for sprite height (1.0 = normal)
    healthBarOffset?: number; // Y offset for health bar (negative = higher)
  };
  /** Flavor text for shop description */
  description?: string;
  /** If true, the unit deals 5x damage on its first hit. */
  isChargeUnit?: boolean;
  /** If true, the unit targets and heals friendly units instead of attacking enemies. */
  isHealer?: boolean;
  /** Maximum number of this unit type a single player may own at once. */
  maxCount?: number;
  /** Passive HP regeneration per second. 0 = no regen (default). */
  regenRate?: number;
  /** Power tier (1–7) derived from gold cost. */
  tier?: number;
  /** Magic element for mage / healer units. */
  element?: "fire" | "cold" | "lightning" | "distortion" | "summon" | "nature" | "heal";
  /** Critical hit chance (0.0–1.0). Default 0.05 (5%) if omitted. */
  critChance?: number;
  /** Block chance (0.0–1.0). Default 0.0 (0%) if omitted. Shield units override this. */
  blockChance?: number;
}

/** Compute tier from gold cost. Same thresholds for all categories. */
export function computeTier(cost: number): number {
  if (cost < 400) return 1;
  if (cost < 600) return 2;
  if (cost < 900) return 3;
  if (cost < 1300) return 4;
  if (cost < 1900) return 5;
  if (cost < 2800) return 6;
  return 7;
}

export const UNIT_DEFINITIONS: Record<UnitType, UnitDef> = {
  [UnitType.SWORDSMAN]: {
    type: UnitType.SWORDSMAN,
    cost: 150,
    hp: 100,
    atk: 15,
    attackSpeed: 1.0,
    speed: 1,
    range: 1,
    spawnTime: 3,
    abilityTypes: [],
    blockChance: 0.15,
    spriteKey: "swordsman",
    description:
      "A sturdy frontline warrior with reliable steel and unwavering courage.",
    tier: 1,
  },
  [UnitType.TEMPLAR]: {
    type: UnitType.TEMPLAR,
    cost: 350,
    hp: 150,
    atk: 20,
    attackSpeed: 1.0,
    speed: 1,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "templar",
    regenRate: 5,
    description:
      "Holy warrior in shining armor. Better protected than swordsmen with divine blessing.",
    tier: 1,
    element: "heal",
    blockChance: 0.2,
  },
  [UnitType.ASSASSIN]: {
    type: UnitType.ASSASSIN,
    cost: 800,
    hp: 65,
    atk: 40,
    attackSpeed: 1.3,
    speed: 1.5,
    range: 1,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "assassin",
    description:
      "Deadly melee striker in black garb with sword and dagger. Fast and lethal but fragile.",
    tier: 3,
    critChance: 0.15,
  },
  [UnitType.REPEATER]: {
    type: UnitType.REPEATER,
    cost: 820,
    hp: 80,
    atk: 15,
    attackSpeed: 2.0,
    speed: 1,
    range: 3,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "repeater",
    description:
      "Rapid-fire crossbow. Low range but shoots very fast in close quarters.",
    tier: 3,
  },
  [UnitType.ARCHER]: {
    type: UnitType.ARCHER,
    cost: 200,
    hp: 70,
    atk: 20,
    attackSpeed: 0.8,
    speed: 1,
    range: 4,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "archer",
    description:
      "Deadly marksman who rains arrows from afar, picking off enemies before they can strike.",
    tier: 1,
  },
  [UnitType.LONGBOWMAN]: {
    type: UnitType.LONGBOWMAN,
    cost: 275,
    hp: 65,
    atk: 18,
    attackSpeed: 0.7,
    speed: 0.9,
    range: 6,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "longbowman",
    description:
      "Elite archer with unmatched range, capable of striking enemies from across the battlefield.",
    tier: 1,
  },
  [UnitType.CROSSBOWMAN]: {
    type: UnitType.CROSSBOWMAN,
    cost: 300,
    hp: 75,
    atk: 30,
    attackSpeed: 0.5,
    speed: 0.9,
    range: 3,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "crossbowman",
    description:
      "Heavy crossbowman who delivers devastating bolts at the cost of slower reload speed.",
    tier: 1,
  },
  [UnitType.KNIGHT]: {
    type: UnitType.KNIGHT,
    cost: 300,
    hp: 200,
    atk: 25,
    attackSpeed: 0.7,
    speed: 1.5,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "knight",
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    description:
      "Armored cavalry unit that charges into battle with devastating force and speed.",
    tier: 1,
    blockChance: 0.1,
  },
  [UnitType.QUESTING_KNIGHT]: {
    type: UnitType.QUESTING_KNIGHT,
    cost: 300,
    hp: 200,
    atk: 28,
    attackSpeed: 0.7,
    speed: 1.5,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "questing_knight",
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    description:
      "He does not actually do alot of questing, except for the Queen's favor.",
    tier: 1,
  },
  [UnitType.FIRE_MAGE]: {
    type: UnitType.FIRE_MAGE,
    cost: 400,
    hp: 60,
    atk: 10,
    attackSpeed: 0.5,
    speed: 0.75,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.FIREBALL],
    spriteKey: "mage",
    description:
      "Pyromancer who hurls explosive fireballs, engulfing enemies in flames.",
    tier: 2,
    element: "fire",
  },
  [UnitType.STORM_MAGE]: {
    type: UnitType.STORM_MAGE,
    cost: 400,
    hp: 60,
    atk: 10,
    attackSpeed: 0.5,
    speed: 0.75,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.CHAIN_LIGHTNING],
    spriteKey: "mage",
    description:
      "Storm caller who unleashes devastating lightning bolts from the heavens.",
    tier: 2,
    element: "lightning",
  },
  [UnitType.PIKEMAN]: {
    type: UnitType.PIKEMAN,
    cost: 175,
    hp: 90,
    atk: 18,
    attackSpeed: 0.9,
    speed: 0.9,
    range: 2,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "pikeman",
    tier: 1,
  },
  [UnitType.SUMMONED]: {
    type: UnitType.SUMMONED,
    cost: 100,
    hp: 40,
    atk: 10,
    attackSpeed: 1.2,
    speed: 1.25,
    range: 1,
    spawnTime: 0,
    abilityTypes: [],
    spriteKey: "summoned",
    tier: 1,
  },
  [UnitType.BATTERING_RAM]: {
    type: UnitType.BATTERING_RAM,
    cost: 400,
    hp: 300,
    atk: 60,
    attackSpeed: 0.4,
    speed: 0.5,
    range: 1,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "battering_ram",
    siegeOnly: true,
    tier: 2,
  },
  [UnitType.MAGE_HUNTER]: {
    type: UnitType.MAGE_HUNTER,
    cost: 250,
    hp: 80,
    atk: 22,
    attackSpeed: 1.1,
    speed: 1.25,
    range: 1,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "mage_hunter",
    huntTargets: [UnitType.FIRE_MAGE, UnitType.STORM_MAGE],
    tier: 1,
  },
  [UnitType.SIEGE_HUNTER]: {
    type: UnitType.SIEGE_HUNTER,
    cost: 300,
    hp: 120,
    atk: 35,
    attackSpeed: 0.9,
    speed: 1.5,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "siege_hunter",
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    huntTargets: [
      UnitType.BATTERING_RAM,
      UnitType.CATAPULT,
      UnitType.SIEGE_CATAPULT,
      UnitType.TREBUCHET,
    ],
    tier: 1,
  },
  [UnitType.SUMMONER]: {
    type: UnitType.SUMMONER,
    cost: 750,
    hp: 55,
    atk: 5,
    attackSpeed: 0.4,
    speed: 0.75,
    range: 6,
    spawnTime: 8,
    abilityTypes: [AbilityType.SUMMON],
    spriteKey: "golem",
    tier: 3,
    element: "summon",
  },
  [UnitType.CONSTRUCTIONIST]: {
    type: UnitType.CONSTRUCTIONIST,
    cost: 1200,
    hp: 55,
    atk: 5,
    attackSpeed: 0.4,
    speed: 0.75,
    range: 6,
    spawnTime: 8,
    abilityTypes: [AbilityType.SUMMON],
    spriteKey: "constructionist",
    tier: 4,
    element: "summon",
  },
  [UnitType.COLD_MAGE]: {
    type: UnitType.COLD_MAGE,
    cost: 500,
    hp: 55,
    atk: 5,
    attackSpeed: 0.4,
    speed: 0.75,
    range: 6,
    spawnTime: 7,
    abilityTypes: [AbilityType.ICE_BALL],
    spriteKey: "cold_mage",
    tier: 1,
    element: "cold",
  },
  [UnitType.SPIDER]: {
    type: UnitType.SPIDER,
    cost: 300,
    hp: 65,
    atk: 8,
    attackSpeed: 0.7,
    speed: 1.1,
    range: 4,
    spawnTime: 5,
    abilityTypes: [AbilityType.WEB],
    spriteKey: "spider",
    tier: 1,
  },
  [UnitType.GLADIATOR]: {
    type: UnitType.GLADIATOR,
    cost: 350,
    hp: 140,
    atk: 18,
    attackSpeed: 0.8,
    speed: 1.0,
    range: 2.5,
    spawnTime: 6,
    abilityTypes: [AbilityType.GLADIATOR_NET],
    spriteKey: "gladiator",
    tier: 1,
  },
  [UnitType.DIPLOMAT]: {
    type: UnitType.DIPLOMAT,
    cost: 300,
    hp: 80,
    atk: 0,
    attackSpeed: 0,
    speed: 1.25,
    range: 0,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "diplomat",
    diplomatOnly: true,
    description: "A silver-tongued envoy in rich purple doublet and crimson cape. Ignores combat entirely — seeks neutral buildings to capture through diplomacy.",
    tier: 1,
  },
  [UnitType.SETTLER]: {
    type: UnitType.SETTLER,
    cost: 0,
    hp: 40,
    atk: 0,
    attackSpeed: 0,
    speed: 0.75,
    range: 0,
    spawnTime: 0,
    abilityTypes: [],
    spriteKey: "settler",
    diplomatOnly: true,
    description: "A brave settler who establishes a forward castle on neutral territory. Cannot fight.",
    tier: 1,
  },
  [UnitType.ENGINEER]: {
    type: UnitType.ENGINEER,
    cost: 0,
    hp: 30,
    atk: 0,
    attackSpeed: 0,
    speed: 0.8,
    range: 0,
    spawnTime: 0,
    abilityTypes: [],
    spriteKey: "engineer",
    diplomatOnly: true,
    description: "A skilled engineer who constructs a forward tower on neutral territory. Cannot fight.",
    tier: 1,
  },
  [UnitType.DISTORTION_MAGE]: {
    type: UnitType.DISTORTION_MAGE,
    cost: 450,
    hp: 65,
    atk: 10,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.DISTORTION_BLAST],
    spriteKey: "mage",
    tier: 1,
    element: "distortion",
  },
  [UnitType.FIRE_ADEPT_MAGE]: {
    type: UnitType.FIRE_ADEPT_MAGE,
    cost: 650,
    hp: 100,
    atk: 15,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 6,
    spawnTime: 7,
    abilityTypes: [AbilityType.FIREBALL, AbilityType.FIRE_IMP_SUMMON],
    spriteKey: "fire_adept_mage",
    description:
      "Master of fire magic. Throws devastating fireballs at enemies.",
    tier: 3,
    element: "fire",
  },
  [UnitType.COLD_ADEPT_MAGE]: {
    type: UnitType.COLD_ADEPT_MAGE,
    cost: 650,
    hp: 100,
    atk: 15,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 6,
    spawnTime: 7,
    abilityTypes: [AbilityType.ICE_BALL, AbilityType.ICE_IMP_SUMMON],
    spriteKey: "cold_adept_mage",
    description: "Master of ice magic. Casts ice storms that slow enemies.",
    tier: 3,
    element: "cold",
  },
  [UnitType.LIGHTNING_ADEPT_MAGE]: {
    type: UnitType.LIGHTNING_ADEPT_MAGE,
    cost: 650,
    hp: 100,
    atk: 15,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 6,
    spawnTime: 7,
    abilityTypes: [
      AbilityType.CHAIN_LIGHTNING,
      AbilityType.LIGHTNING_IMP_SUMMON,
    ],
    spriteKey: "lightning_adept_mage",
    description:
      "Master of lightning magic. Calls down chain lightning on enemies.",
    tier: 3,
    element: "lightning",
  },
  [UnitType.DISTORTION_ADEPT_MAGE]: {
    type: UnitType.DISTORTION_ADEPT_MAGE,
    cost: 650,
    hp: 100,
    atk: 15,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 6,
    spawnTime: 7,
    abilityTypes: [
      AbilityType.DISTORTION_BLAST,
      AbilityType.DISTORTION_IMP_SUMMON,
    ],
    spriteKey: "distortion_adept_mage",
    description:
      "Master of distortion magic. Warps space to damage and confuse enemies.",
    tier: 3,
    element: "distortion",
  },
  [UnitType.FIRE_MASTER_MAGE]: {
    type: UnitType.FIRE_MASTER_MAGE,
    cost: 1100,
    hp: 200,
    atk: 20,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 7,
    spawnTime: 8,
    abilityTypes: [AbilityType.FIREBALL, AbilityType.FIRE_MASTER_IMP_SUMMON],
    spriteKey: "fire_master_mage",
    regenRate: 5,
    description:
      "Grandmaster of fire magic. Throws devastating fireballs at enemies.",
    tier: 4,
    element: "fire",
  },
  [UnitType.COLD_MASTER_MAGE]: {
    type: UnitType.COLD_MASTER_MAGE,
    cost: 1100,
    hp: 200,
    atk: 20,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 7,
    spawnTime: 8,
    abilityTypes: [AbilityType.ICE_BALL, AbilityType.ICE_MASTER_IMP_SUMMON],
    spriteKey: "cold_master_mage",
    regenRate: 5,
    description:
      "Grandmaster of ice magic. Casts devastating ice storms that slow enemies.",
    tier: 4,
    element: "cold",
  },
  [UnitType.LIGHTNING_MASTER_MAGE]: {
    type: UnitType.LIGHTNING_MASTER_MAGE,
    cost: 1100,
    hp: 200,
    atk: 20,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 7,
    spawnTime: 8,
    abilityTypes: [
      AbilityType.CHAIN_LIGHTNING,
      AbilityType.LIGHTNING_MASTER_IMP_SUMMON,
    ],
    spriteKey: "lightning_master_mage",
    regenRate: 5,
    description:
      "Grandmaster of lightning magic. Calls down devastating chain lightning on enemies.",
    tier: 4,
    element: "lightning",
  },
  [UnitType.DISTORTION_MASTER_MAGE]: {
    type: UnitType.DISTORTION_MASTER_MAGE,
    cost: 1100,
    hp: 200,
    atk: 20,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 7,
    spawnTime: 8,
    abilityTypes: [
      AbilityType.DISTORTION_BLAST,
      AbilityType.DISTORTION_MASTER_IMP_SUMMON,
    ],
    spriteKey: "distortion_master_mage",
    regenRate: 5,
    description:
      "Grandmaster of distortion magic. Warps space to devastatingly damage and confuse enemies.",
    tier: 4,
    element: "distortion",
  },
  [UnitType.VOID_SNAIL]: {
    type: UnitType.VOID_SNAIL,
    cost: 250,
    hp: 120,
    atk: 5,
    attackSpeed: 0.4,
    speed: 0.5,
    range: 3,
    spawnTime: 5,
    abilityTypes: [AbilityType.VOID_DISTORTION],
    spriteKey: "spider", // placeholder or snail-like
    tier: 1,
  },
  [UnitType.FAERY_QUEEN]: {
    type: UnitType.FAERY_QUEEN,
    cost: 750,
    hp: 80,
    atk: 15,
    attackSpeed: 0.7,
    speed: 1.1,
    range: 6,
    spawnTime: 10,
    abilityTypes: [AbilityType.FAERY_DISTORTION],
    spriteKey: "cold_mage", // placeholder or fairy-like
    tier: 3,
  },
  [UnitType.GIANT_FROG]: {
    type: UnitType.GIANT_FROG,
    cost: 500,
    hp: 200,
    atk: 10,
    attackSpeed: 0.6,
    speed: 0.9,
    range: 7,
    spawnTime: 6,
    abilityTypes: [AbilityType.FROG_TONGUE],
    spriteKey: "spider", // placeholder (spider-like legs/movement)
    tier: 2,
  },
  [UnitType.DEVOURER]: {
    type: UnitType.DEVOURER,
    cost: 650,
    hp: 350,
    atk: 15,
    attackSpeed: 0.5,
    speed: 0.6,
    range: 3,
    spawnTime: 8,
    abilityTypes: [AbilityType.DEVOUR_PULL],
    spriteKey: "swordsman", // placeholder (tanky humanoid)
    tier: 3,
  },
  [UnitType.TROLL]: {
    type: UnitType.TROLL,
    cost: 700,
    hp: 400,
    atk: 30,
    attackSpeed: 0.6,
    speed: 0.5,
    range: 1,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "troll",
    regenRate: 5,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "Massive troll with immense health. Slow but devastating in melee.",
    tier: 3,
  },
  [UnitType.RHINO]: {
    type: UnitType.RHINO,
    cost: 400,
    hp: 350,
    atk: 25,
    attackSpeed: 0.5,
    speed: 0.6,
    range: 1,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "rhino",
    size: { width: 2.0, height: 1.0 },
    description:
      "Armored rhino with thick skin. Slow but tanky, charges at enemies with its horn.",
    tier: 2,
  },
  [UnitType.PIXIE]: {
    type: UnitType.PIXIE,
    cost: 150,
    hp: 40,
    atk: 8,
    attackSpeed: 0.8,
    speed: 1.8,
    range: 5,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "pixie",
    description:
      "Small ethereal pixie with magic attacks. Flies quickly and casts spells with its outstretched arms.",
    tier: 1,
  },
  [UnitType.UNICORN]: {
    type: UnitType.UNICORN,
    cost: 0,
    hp: 80,
    atk: 15,
    attackSpeed: 1.0,
    speed: 1.5,
    range: 1,
    spawnTime: 0,
    abilityTypes: [],
    spriteKey: "unicorn",
    description:
      "A majestic unicorn summoned through arcane magic. Fast melee attacker with a magical horn.",
    tier: 2,
  },
  [UnitType.FIRE_IMP]: {
    type: UnitType.FIRE_IMP,
    cost: 120,
    hp: 35,
    atk: 7,
    attackSpeed: 0.8,
    speed: 1.6,
    range: 4,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "fire_imp",
    description:
      "Small fire imp with flame attacks. Flies quickly and shoots fireballs with its outstretched arms.",
    tier: 1,
  },
  [UnitType.ICE_IMP]: {
    type: UnitType.ICE_IMP,
    cost: 120,
    hp: 35,
    atk: 7,
    attackSpeed: 0.8,
    speed: 1.6,
    range: 4,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "ice_imp",
    description:
      "Small ice imp with frost attacks. Flies quickly and shoots ice shards with its outstretched arms.",
    tier: 1,
  },
  [UnitType.LIGHTNING_IMP]: {
    type: UnitType.LIGHTNING_IMP,
    cost: 120,
    hp: 35,
    atk: 7,
    attackSpeed: 0.8,
    speed: 1.6,
    range: 4,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "lightning_imp",
    description:
      "Small lightning imp with shock attacks. Flies quickly and shoots lightning bolts with its outstretched arms.",
    tier: 1,
  },
  [UnitType.DISTORTION_IMP]: {
    type: UnitType.DISTORTION_IMP,
    cost: 120,
    hp: 35,
    atk: 7,
    attackSpeed: 0.8,
    speed: 1.6,
    range: 4,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "distortion_imp",
    description:
      "Small distortion imp with warp attacks. Flies quickly and shoots distortion bolts with its outstretched arms.",
    tier: 1,
  },
  [UnitType.BAT]: {
    type: UnitType.BAT,
    cost: 150,
    hp: 30,
    atk: 10,
    attackSpeed: 1.2,
    speed: 2.0,
    range: 1,
    spawnTime: 2,
    abilityTypes: [],
    spriteKey: "bat",
    description:
      "Swarm of tiny bats. Very fast but fragile. Overwhelms enemies with numbers.",
    tier: 1,
  },
  [UnitType.VAMPIRE_BAT]: {
    type: UnitType.VAMPIRE_BAT,
    cost: 1200,
    hp: 350,
    atk: 35,
    attackSpeed: 1.0,
    speed: 1.5,
    range: 1,
    spawnTime: 12,
    abilityTypes: [],
    spriteKey: "vampire_bat",
    regenRate: 8,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "Half-man, half-bat abomination with preternatural speed and vampiric regeneration. Fragile but deadly.",
    tier: 4,
  },
  [UnitType.HORSE_ARCHER]: {
    type: UnitType.HORSE_ARCHER,
    cost: 350,
    hp: 100,
    atk: 15,
    attackSpeed: 0.8,
    speed: 1.75,
    range: 4,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "horse_archer",
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    tier: 1,
  },
  [UnitType.SHORTBOW]: {
    type: UnitType.SHORTBOW,
    cost: 150,
    hp: 60,
    atk: 10,
    attackSpeed: 1.2,
    speed: 1.1,
    range: 3,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "archer", // placeholder
    tier: 1,
  },
  [UnitType.BALLISTA]: {
    type: UnitType.BALLISTA,
    cost: 500,
    hp: 120,
    atk: 50,
    attackSpeed: 0.3,
    speed: 0.5,
    range: 5,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "battering_ram", // placeholder (siege)
    tier: 2,
  },
  [UnitType.BOLT_THROWER]: {
    type: UnitType.BOLT_THROWER,
    cost: 600,
    hp: 100,
    atk: 30,
    attackSpeed: 0.35, // slow but long range
    speed: 0.5,
    range: 7,
    spawnTime: 10,
    abilityTypes: [],
    spriteKey: "bolt_thrower",
    tier: 3,
  },
  [UnitType.CATAPULT]: {
    type: UnitType.CATAPULT,
    cost: 900,
    hp: 150,
    atk: 40,
    attackSpeed: 0.15,
    speed: 0.4,
    range: 8,
    spawnTime: 12,
    abilityTypes: [],
    spriteKey: "catapult",
    description:
      "Heavy catapult that launches boulders in a high arc, devastating buildings from extreme range.",
    tier: 3,
  },
  [UnitType.SIEGE_CATAPULT]: {
    type: UnitType.SIEGE_CATAPULT,
    cost: 550,
    hp: 200,
    atk: 55,
    attackSpeed: 0.1,
    speed: 0.3,
    range: 11,
    spawnTime: 15,
    abilityTypes: [],
    spriteKey: "siege_catapult",
    size: {
      width: 2.0,
      height: 1.0,
      healthBarOffset: -0.5,
    },
    description:
      "Massive siege catapult with extreme range, hurling enormous boulders that crush anything in their path.",
    tier: 2,
  },
  [UnitType.TREBUCHET]: {
    type: UnitType.TREBUCHET,
    cost: 500,
    hp: 250,
    atk: 70,
    attackSpeed: 0.07,
    speed: 0.2,
    range: 200,
    spawnTime: 18,
    abilityTypes: [],
    spriteKey: "trebuchet",
    siegeOnly: true,
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    description:
      "Colossal trebuchet capable of bombarding fortifications from incredible distance.",
    tier: 1,
  },
  [UnitType.WAR_WAGON]: {
    type: UnitType.WAR_WAGON,
    cost: 1500,
    hp: 500,
    atk: 45,
    attackSpeed: 0.4,
    speed: 0.45,
    range: 5,
    spawnTime: 14,
    abilityTypes: [],
    spriteKey: "war_wagon",
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    description:
      "Iron-banded war wagon bristling with bolt launchers. Fights armies and fortifications alike.",
    tier: 5,
  },
  [UnitType.BOMBARD]: {
    type: UnitType.BOMBARD,
    cost: 1700,
    hp: 300,
    atk: 120,
    attackSpeed: 0.08,
    speed: 0.3,
    range: 10,
    spawnTime: 16,
    abilityTypes: [],
    spriteKey: "bombard",
    size: {
      width: 2.0,
      height: 1.0,
      healthBarOffset: -0.5,
    },
    description:
      "Primitive bronze cannon that hurls massive iron balls. Devastating but painfully slow to reload.",
    tier: 5,
  },
  [UnitType.SIEGE_TOWER]: {
    type: UnitType.SIEGE_TOWER,
    cost: 2200,
    hp: 900,
    atk: 90,
    attackSpeed: 0.3,
    speed: 0.25,
    range: 1,
    spawnTime: 20,
    abilityTypes: [],
    spriteKey: "siege_tower",
    siegeOnly: true,
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    description:
      "Massive multi-story tower on iron-shod wheels that crashes into fortifications, reducing them to rubble.",
    tier: 6,
  },
  [UnitType.HELLFIRE_MORTAR]: {
    type: UnitType.HELLFIRE_MORTAR,
    cost: 2200,
    hp: 550,
    atk: 150,
    attackSpeed: 0.05,
    speed: 0.2,
    range: 14,
    spawnTime: 22,
    abilityTypes: [],
    spriteKey: "hellfire_mortar",
    siegeOnly: true,
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    description:
      "Squat iron mortar that lobs flaming pitch over staggering distances, reducing buildings to ash.",
    tier: 6,
  },
  [UnitType.SCOUT_CAVALRY]: {
    type: UnitType.SCOUT_CAVALRY,
    cost: 200,
    hp: 60,
    atk: 10,
    attackSpeed: 1.0,
    speed: 1.6,
    range: 1,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "scout_cavalry",
    isChargeUnit: true,
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    tier: 1,
  },
  [UnitType.LANCER]: {
    type: UnitType.LANCER,
    cost: 350,
    hp: 120,
    atk: 20,
    attackSpeed: 0.8,
    speed: 1.5,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "lancer",
    isChargeUnit: true,
    tier: 1,
  },
  [UnitType.ROYAL_LANCER]: {
    type: UnitType.ROYAL_LANCER,
    cost: 900,
    hp: 220,
    atk: 40,
    attackSpeed: 0.9,
    speed: 1.5,
    range: 1,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "royal_lancer",
    isChargeUnit: true,
    tier: 3,
  },
  [UnitType.ELITE_LANCER]: {
    type: UnitType.ELITE_LANCER,
    cost: 500,
    hp: 180,
    atk: 25,
    attackSpeed: 0.8,
    speed: 1.4,
    range: 1,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "elite_lancer",
    isChargeUnit: true,
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    tier: 2,
  },
  [UnitType.KNIGHT_LANCER]: {
    type: UnitType.KNIGHT_LANCER,
    cost: 650,
    hp: 250,
    atk: 30,
    attackSpeed: 0.6,
    speed: 1.1,
    range: 1,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "knight_lancer",
    isChargeUnit: true,
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    tier: 3,
  },
  [UnitType.MONK]: {
    type: UnitType.MONK,
    cost: 250,
    hp: 80,
    atk: 0,
    attackSpeed: 0.8,
    speed: 1,
    range: 1.5,
    spawnTime: 4,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "diplomat", // placeholder (religious robes)
    isHealer: true,
    tier: 2,
    element: "heal",
  },
  [UnitType.CLERIC]: {
    type: UnitType.CLERIC,
    cost: 450,
    hp: 120,
    atk: 0,
    attackSpeed: 0.6,
    speed: 0.9,
    range: 3,
    spawnTime: 7,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "mage", // placeholder
    isHealer: true,
    tier: 3,
    element: "heal",
  },
  [UnitType.SAINT]: {
    type: UnitType.SAINT,
    cost: 750,
    hp: 200,
    atk: 0,
    attackSpeed: 0.5,
    speed: 0.75,
    range: 5,
    spawnTime: 10,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "faery_queen", // placeholder (ethereal/divine)
    isHealer: true,
    tier: 4,
    element: "heal",
  },
  [UnitType.RED_DRAGON]: {
    type: UnitType.RED_DRAGON,
    cost: 1250,
    hp: 500,
    atk: 35,
    attackSpeed: 0.8,
    speed: 1.2,
    range: 2,
    spawnTime: 15,
    abilityTypes: [AbilityType.FIRE_BREATH],
    spriteKey: "red_dragon",
    size: {
      width: 1.0, // normal width
      height: 2.0, // 2x taller than normal
      healthBarOffset: -0.8, // health bar positioned higher
    },
    description:
      "Fire-breathing drake that scorches all who dare oppose it.",
    tier: 4,
  },
  [UnitType.FROST_DRAGON]: {
    type: UnitType.FROST_DRAGON,
    cost: 1200,
    hp: 480,
    atk: 30,
    attackSpeed: 0.8,
    speed: 1.2,
    range: 2,
    spawnTime: 15,
    abilityTypes: [AbilityType.FROST_BREATH],
    spriteKey: "frost_dragon",
    size: {
      width: 1.0, // normal width
      height: 2.0, // 2x taller than normal
      healthBarOffset: -0.8, // health bar positioned higher
    },
    description:
      "Ice drake whose freezing breath slows enemies to a crawl before shattering them.",
    tier: 4,
  },
  [UnitType.FIRE_DRAGON]: {
    type: UnitType.FIRE_DRAGON,
    cost: 2000,
    hp: 900,
    atk: 55,
    attackSpeed: 0.7,
    speed: 1.0,
    range: 2,
    spawnTime: 20,
    abilityTypes: [AbilityType.FIRE_BREATH],
    spriteKey: "fire_dragon",
    size: {
      width: 2.0,
      height: 3.0,
      healthBarOffset: -1.2,
    },
    description:
      "Ancient fire dragon with armoured scales and devastating breath. Towers above the battlefield.",
    tier: 5,
  },
  [UnitType.ICE_DRAGON]: {
    type: UnitType.ICE_DRAGON,
    cost: 1900,
    hp: 850,
    atk: 50,
    attackSpeed: 0.7,
    speed: 1.0,
    range: 2,
    spawnTime: 20,
    abilityTypes: [AbilityType.FROST_BREATH],
    spriteKey: "ice_dragon",
    size: {
      width: 2.0,
      height: 3.0,
      healthBarOffset: -1.2,
    },
    description:
      "Ancient ice dragon whose freezing breath encases entire formations in ice.",
    tier: 5,
  },
  [UnitType.CYCLOPS]: {
    type: UnitType.CYCLOPS,
    cost: 1750, // Very expensive
    hp: 800, // Very high hitpoints
    atk: 60, // Very high attack
    attackSpeed: 0.6, // Slow but devastating attacks
    speed: 0.8, // Slow movement
    range: 1.5, // Melee with slightly extended reach due to club
    spawnTime: 20, // Long training time
    abilityTypes: [], // Basic melee attacks only
    spriteKey: "cyclops",
    size: {
      width: 2.0, // 2 tiles wide
      height: 3.0, // 3 tiles tall
      healthBarOffset: -2.0, // Health bar positioned very high
    },
    description:
      "Massive one-eyed giant wielding a tree trunk, crushing enemies with earth-shattering blows.",
    tier: 5,
  },
  [UnitType.ANGEL]: {
    type: UnitType.ANGEL,
    cost: 4000,
    hp: 1500,
    atk: 90,
    attackSpeed: 0.7,
    speed: 1.2,
    range: 1,
    spawnTime: 25,
    abilityTypes: [],
    spriteKey: "angel",
    regenRate: 5,
    size: {
      width: 3.0,
      height: 3.0,
      healthBarOffset: -2.0,
    },
    description:
      "Divine celestial warrior of the heavens, wielding a blazing sword and radiating holy light.",
    tier: 7,
    element: "heal",
  },
  [UnitType.DARK_SAVANT]: {
    type: UnitType.DARK_SAVANT,
    cost: 3300,
    hp: 200,
    atk: 35,
    attackSpeed: 0.5,
    speed: 0.75,
    range: 5,
    spawnTime: 15,
    abilityTypes: [AbilityType.FIREBALL, AbilityType.FIRE_AURA],
    spriteKey: "fire_mage",
    regenRate: 5,
    description:
      "Master of dark pyromancy who hurls devastating fireballs with increased destructive power.",
    tier: 7,
    element: "fire",
  },
  [UnitType.HALBERDIER]: {
    type: UnitType.HALBERDIER,
    cost: 200,
    hp: 105,
    atk: 22,
    attackSpeed: 1.0,
    speed: 1.0,
    range: 2,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "halberdier",
    description:
      "Elite human infantry wielding a halberd. Tougher and harder-hitting than the common pikeman.",
    tier: 1,
  },
  [UnitType.ELVEN_ARCHER]: {
    type: UnitType.ELVEN_ARCHER,
    cost: 300,
    hp: 70,
    atk: 17,
    attackSpeed: 0.75,
    speed: 1.0,
    range: 7,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "elven_archer",
    description:
      "Graceful elven marksman with unparalleled range and precision, striking from positions others cannot reach.",
    tier: 1,
  },
  [UnitType.HERO]: {
    type: UnitType.HERO,
    cost: 250,
    hp: 120,
    atk: 18,
    attackSpeed: 1.1,
    speed: 1.2,
    range: 1,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "hero",
    maxCount: 4,
    description:
      "Legendary warrior whose prowess inspires allies and terrifies foes. Max: 4",
    tier: 1,
  },
  [UnitType.DEFENDER]: {
    type: UnitType.DEFENDER,
    cost: 400,
    hp: 250,
    atk: 12,
    attackSpeed: 0.8,
    speed: 0.7,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "defender",
    description:
      "Heavily armored soldier with a massive tower shield, nearly immovable on the front line.",
    tier: 2,
    blockChance: 0.2,
  },
  [UnitType.PHALANX]: {
    type: UnitType.PHALANX,
    cost: 450,
    hp: 220,
    atk: 14,
    attackSpeed: 0.8,
    speed: 0.7,
    range: 2,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "phalanx",
    description:
      "Armored spearman with a long spear and tower shield, holding enemies at bay from behind a wall of steel.",
    tier: 2,
    blockChance: 0.2,
  },
  [UnitType.ROYAL_PHALANX]: {
    type: UnitType.ROYAL_PHALANX,
    cost: 650,
    hp: 300,
    atk: 18,
    attackSpeed: 0.9,
    speed: 0.65,
    range: 2.5,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "royal_phalanx",
    description:
      "Elite pikeman in gilded armor wielding an enormous pike, impaling foes long before they can strike.",
    tier: 3,
    blockChance: 0.15,
  },
  [UnitType.ROYAL_DEFENDER]: {
    type: UnitType.ROYAL_DEFENDER,
    cost: 700,
    hp: 450,
    atk: 20,
    attackSpeed: 0.7,
    speed: 0.6,
    range: 1,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "royal_defender",
    description:
      "Heavily armored royal guard with massive shield. Blocks attacks and strikes with devastating melee blows.",
    tier: 3,
    blockChance: 0.3,
  },
  [UnitType.AXEMAN]: {
    type: UnitType.AXEMAN,
    cost: 400,
    hp: 350,
    atk: 28,
    attackSpeed: 0.9,
    speed: 0.9,
    range: 1,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "axeman",
    description:
      "Fierce warrior wielding a mighty battle axe. Strikes with devastating power but lacks defensive gear.",
    tier: 2,
  },
  [UnitType.BERSERKER]: {
    type: UnitType.BERSERKER,
    cost: 600,
    hp: 250,
    atk: 35,
    attackSpeed: 1.1,
    speed: 1.0,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "berserker",
    description:
      "Naked fury with a two-handed axe. High attack but low defense. Terrifying in combat.",
    tier: 3,
  },
  [UnitType.ANCIENT_DEFENDER]: {
    type: UnitType.ANCIENT_DEFENDER,
    cost: 1100,
    hp: 700,
    atk: 30,
    attackSpeed: 0.6,
    speed: 0.55,
    range: 1,
    spawnTime: 12,
    abilityTypes: [],
    spriteKey: "ancient_defender",
    size: { width: 1.0, height: 1.5, healthBarOffset: -1.2 },
    description:
      "An undying sentinel from a forgotten age. Its blackened armor is fused to ashen skin, and its tower shield has turned back a thousand charges.",
    tier: 4,
    blockChance: 0.25,
  },
  [UnitType.ANCIENT_PHALANX]: {
    type: UnitType.ANCIENT_PHALANX,
    cost: 1050,
    hp: 500,
    atk: 28,
    attackSpeed: 0.7,
    speed: 0.55,
    range: 3,
    spawnTime: 11,
    abilityTypes: [],
    spriteKey: "ancient_phalanx",
    size: { width: 1.0, height: 1.5, healthBarOffset: -1.2 },
    description:
      "A grey-skinned spearman who has outlived empires. Its corroded pike still reaches further than any mortal weapon.",
    tier: 4,
    blockChance: 0.2,
  },
  [UnitType.ANCIENT_AXEMAN]: {
    type: UnitType.ANCIENT_AXEMAN,
    cost: 1000,
    hp: 600,
    atk: 45,
    attackSpeed: 0.8,
    speed: 0.75,
    range: 1,
    spawnTime: 10,
    abilityTypes: [],
    spriteKey: "ancient_axeman",
    size: { width: 1.0, height: 1.5, healthBarOffset: -1.2 },
    description:
      "A hulking relic of a brutal era, swinging a pitted black axe with terrible strength. Its grey flesh feels no pain.",
    tier: 4,
  },
  [UnitType.ANCIENT_ARCHER]: {
    type: UnitType.ANCIENT_ARCHER,
    cost: 1000,
    hp: 350,
    atk: 45,
    attackSpeed: 0.65,
    speed: 0.7,
    range: 5,
    spawnTime: 11,
    abilityTypes: [],
    spriteKey: "ancient_archer",
    size: { width: 1.0, height: 1.5, healthBarOffset: -1.2 },
    description:
      "A spectral bowman from a lost age, drawing a blackened longbow with impossible strength. Its arrows strike with the weight of centuries.",
    tier: 4,
  },
  [UnitType.ANCIENT_LONGBOWMAN]: {
    type: UnitType.ANCIENT_LONGBOWMAN,
    cost: 1050,
    hp: 300,
    atk: 35,
    attackSpeed: 0.55,
    speed: 0.6,
    range: 8,
    spawnTime: 12,
    abilityTypes: [],
    spriteKey: "ancient_longbowman",
    size: { width: 1.0, height: 1.5, healthBarOffset: -1.2 },
    description:
      "An ageless sentinel whose corroded greatbow reaches across the entire field. Its shafts fall like judgement from a forgotten sky.",
    tier: 4,
  },
  [UnitType.ANCIENT_CROSSBOWMAN]: {
    type: UnitType.ANCIENT_CROSSBOWMAN,
    cost: 1100,
    hp: 400,
    atk: 65,
    attackSpeed: 0.3,
    speed: 0.6,
    range: 4,
    spawnTime: 12,
    abilityTypes: [],
    spriteKey: "ancient_crossbowman",
    size: { width: 1.0, height: 1.5, healthBarOffset: -1.2 },
    description:
      "A grim relic cranking a siege-weight arbalest of pitted black iron. Each bolt punches through shields like parchment.",
    tier: 4,
  },
  [UnitType.ELDER_ARCHER]: {
    type: UnitType.ELDER_ARCHER,
    cost: 2600,
    hp: 700,
    atk: 85,
    attackSpeed: 0.55,
    speed: 0.5,
    range: 6,
    spawnTime: 20,
    abilityTypes: [],
    spriteKey: "elder_archer",
    size: { width: 1.0, height: 2.0, healthBarOffset: -1.6 },
    description:
      "A towering void-wraith with a bow of petrified shadow. Its arrows tear through the air like screaming voids, striking with force beyond mortal comprehension.",
    tier: 6,
  },
  [UnitType.ELDER_REPEATER]: {
    type: UnitType.ELDER_REPEATER,
    cost: 2800,
    hp: 500,
    atk: 40,
    attackSpeed: 2.5,
    speed: 0.65,
    range: 4,
    spawnTime: 22,
    abilityTypes: [],
    spriteKey: "elder_repeater",
    size: { width: 1.0, height: 2.0, healthBarOffset: -1.6 },
    description:
      "A nightmare of fused iron and sinew, cranking an impossible repeating arbalest. Bolts pour forth in an endless black rain that shreds all in its path.",
    tier: 6,
  },
  [UnitType.ELDER_JAVELINEER]: {
    type: UnitType.ELDER_JAVELINEER,
    cost: 2700,
    hp: 650,
    atk: 100,
    attackSpeed: 0.4,
    speed: 0.6,
    range: 4,
    spawnTime: 20,
    abilityTypes: [],
    spriteKey: "elder_javelineer",
    size: { width: 1.0, height: 2.0, healthBarOffset: -1.6 },
    description:
      "A colossal horror hurling javelins of black iron that impale entire formations. Each throw carries the weight of a fallen age.",
    tier: 6,
  },
  [UnitType.ELDER_HORSE_ARCHER]: {
    type: UnitType.ELDER_HORSE_ARCHER,
    cost: 2800,
    hp: 800,
    atk: 70,
    attackSpeed: 0.7,
    speed: 1.4,
    range: 5,
    spawnTime: 22,
    abilityTypes: [],
    spriteKey: "elder_horse_archer",
    size: {
      width: 3.0,
      height: 3.0,
      healthBarOffset: -2.0,
    },
    description:
      "A nightmare warhorse of impossible scale, its void-black rider loosing spectral arrows from a bow that hums with forgotten dread.",
    tier: 6,
  },
  [UnitType.ELDER_DEFENDER]: {
    type: UnitType.ELDER_DEFENDER,
    cost: 2200,
    hp: 1200,
    atk: 45,
    attackSpeed: 0.5,
    speed: 0.45,
    range: 1,
    spawnTime: 20,
    abilityTypes: [],
    spriteKey: "elder_defender",
    size: { width: 1.0, height: 2.0, healthBarOffset: -1.6 },
    description:
      "No longer human, no longer mortal. A towering monolith of fused black iron and petrified flesh, its void-dark shield swallows all who approach.",
    tier: 5,
    blockChance: 0.3,
  },
  [UnitType.ELDER_PHALANX]: {
    type: UnitType.ELDER_PHALANX,
    cost: 2000,
    hp: 900,
    atk: 40,
    attackSpeed: 0.6,
    speed: 0.45,
    range: 3.5,
    spawnTime: 18,
    abilityTypes: [],
    spriteKey: "elder_phalanx",
    size: { width: 1.0, height: 2.0, healthBarOffset: -1.6 },
    description:
      "An impossibly tall sentinel whose barbed lance impales foes before they even glimpse its featureless helm. Whatever it once was, it is something else now.",
    blockChance: 0.25,
    tier: 5,
  },
  [UnitType.ELDER_AXEMAN]: {
    type: UnitType.ELDER_AXEMAN,
    cost: 1900,
    hp: 1000,
    atk: 65,
    attackSpeed: 0.7,
    speed: 0.6,
    range: 1,
    spawnTime: 16,
    abilityTypes: [],
    spriteKey: "elder_axeman",
    size: { width: 1.0, height: 2.0, healthBarOffset: -1.6 },
    description:
      "A nightmarish executioner of slag and sinew. Its jagged black cleaver carves through ranks with each terrible stroke.",
    tier: 5,
  },
  [UnitType.JAVELINEER]: {
    type: UnitType.JAVELINEER,
    cost: 400,
    hp: 100,
    atk: 35,
    attackSpeed: 0.5,
    speed: 1,
    range: 3,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "javelin",
    description:
      "Light infantry armed with javelins and a buckler. High damage but slow attack and short range.",
    tier: 2,
  },
  [UnitType.ARBALESTIER]: {
    type: UnitType.ARBALESTIER,
    cost: 700,
    hp: 120,
    atk: 50,
    attackSpeed: 0.3,
    speed: 0.8,
    range: 6,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "arbelestier",
    description:
      "Heavy crossbowman with plate armor. Devastating damage but very slow reload time.",
    tier: 3,
  },
  [UnitType.ROYAL_ARBALESTIER]: {
    type: UnitType.ROYAL_ARBALESTIER,
    cost: 800,
    hp: 140,
    atk: 55,
    attackSpeed: 0.35,
    speed: 0.9,
    range: 7,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "arbelestier",
    description:
      "Elite royal crossbowman with enhanced armor and precision. Superior range and damage.",
    tier: 3,
  },
  [UnitType.WARCHIEF]: {
    type: UnitType.WARCHIEF,
    cost: 400,
    hp: 160,
    atk: 24,
    attackSpeed: 0.9,
    speed: 1.1,
    range: 1.5,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "warchief",
    description:
      "Brutal horde warchief wielding a massive cleaver. Inspires nearby warriors with savage fury.",
    tier: 2,
  },
  [UnitType.ARCHMAGE]: {
    type: UnitType.ARCHMAGE,
    cost: 600,
    hp: 80,
    atk: 18,
    attackSpeed: 0.6,
    speed: 0.85,
    range: 6,
    spawnTime: 6,
    abilityTypes: [AbilityType.FIREBALL],
    spriteKey: "archmage",
    regenRate: 3,
    description:
      "Supreme arcanist channelling raw magical energy. Devastating at range with arcane bolts.",
    tier: 3,
    element: "fire",
  },
  [UnitType.RUFUS]: {
    type: UnitType.RUFUS,
    cost: 50,
    hp: 40,
    atk: 5,
    attackSpeed: 1.2,
    speed: 2.0,
    range: 1,
    spawnTime: 2,
    abilityTypes: [],
    spriteKey: "rufus",
    maxCount: 1,
    description:
      "The loyal dog of the king. Weak but fast, Rufus patrols the hearth with unwavering devotion.",
    tier: 1,
  },
  [UnitType.TROUBADOUR]: {
    type: UnitType.TROUBADOUR,
    cost: 100,
    hp: 50,
    atk: 8,
    attackSpeed: 0.8,
    speed: 1.0,
    range: 1,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "troubadour",
    maxCount: 1,
    description:
      "A wandering troubadour who sings ballads of glory. Weak in combat but steadfast in spirit.",
    tier: 1,
  },
  [UnitType.GIANT_COURT_JESTER]: {
    type: UnitType.GIANT_COURT_JESTER,
    cost: 300,
    hp: 500,
    atk: 1,
    attackSpeed: 0.5,
    speed: 0.4,
    range: 1,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "giant_court_jester",
    size: {
      width: 2.0,
      height: 3.0,
      healthBarOffset: -2.0,
    },
    maxCount: 1,
    description:
      "The giant court jester, would truly barely hurt a fly. Enormous and resilient, but utterly harmless.",
    tier: 1,
  },
  [UnitType.FISHERMAN]: {
    type: UnitType.FISHERMAN,
    cost: 200,
    hp: 80,
    atk: 10,
    attackSpeed: 0.8,
    speed: 1.0,
    range: 4,
    spawnTime: 4,
    abilityTypes: [AbilityType.FISHERMAN_NET],
    spriteKey: "fisherman",
    maxCount: 1,
    description:
      "A humble fisherman who casts his net with surprising skill, hauling enemies in like the catch of the day.",
    tier: 1,
  },
  [UnitType.FIRE_ELEMENTAL]: {
    type: UnitType.FIRE_ELEMENTAL,
    cost: 2000,
    hp: 1000,
    atk: 70,
    attackSpeed: 0.7,
    speed: 0.9,
    range: 1.5,
    spawnTime: 22,
    abilityTypes: [AbilityType.FIRE_AURA],
    spriteKey: "fire_elemental",
    size: {
      width: 3.0,
      height: 3.0,
      healthBarOffset: -2.0,
    },
    description:
      "A towering inferno given form — cracked obsidian plates barely contain the molten fury within.",
    tier: 5,
    element: "fire",
  },
  [UnitType.ICE_ELEMENTAL]: {
    type: UnitType.ICE_ELEMENTAL,
    cost: 2000,
    hp: 900,
    atk: 55,
    attackSpeed: 0.8,
    speed: 0.8,
    range: 2,
    spawnTime: 22,
    abilityTypes: [AbilityType.ICE_AURA],
    spriteKey: "ice_elemental",
    size: {
      width: 3.0,
      height: 3.0,
      healthBarOffset: -2.0,
    },
    description:
      "An ancient glacier given terrible sentience — jagged crystals of primordial ice radiate a killing frost.",
    tier: 5,
    element: "cold",
  },
  [UnitType.MINOR_FIRE_ELEMENTAL]: {
    type: UnitType.MINOR_FIRE_ELEMENTAL,
    cost: 800,
    hp: 450,
    atk: 30,
    attackSpeed: 0.8,
    speed: 1.0,
    range: 1.5,
    spawnTime: 14,
    abilityTypes: [AbilityType.MINOR_FIRE_AURA],
    spriteKey: "minor_fire_elemental",
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    description:
      "A lesser flame spirit of smoldering basalt and flickering fire — its aura scorches all nearby.",
    tier: 3,
    element: "fire",
  },
  [UnitType.MINOR_ICE_ELEMENTAL]: {
    type: UnitType.MINOR_ICE_ELEMENTAL,
    cost: 800,
    hp: 400,
    atk: 25,
    attackSpeed: 0.9,
    speed: 0.9,
    range: 2,
    spawnTime: 14,
    abilityTypes: [AbilityType.MINOR_ICE_AURA],
    spriteKey: "minor_ice_elemental",
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    description:
      "A lesser frost spirit of cracked ice and biting wind — its chilling aura slows those who draw near.",
    tier: 3,
    element: "cold",
  },
  [UnitType.LIGHTNING_ELEMENTAL]: {
    type: UnitType.LIGHTNING_ELEMENTAL,
    cost: 2000,
    hp: 900,
    atk: 65,
    attackSpeed: 0.6,
    speed: 1.0,
    range: 1.5,
    spawnTime: 22,
    abilityTypes: [AbilityType.LIGHTNING_AURA],
    spriteKey: "lightning_elemental",
    size: { width: 3.0, height: 3.0, healthBarOffset: -2.0 },
    description:
      "A tempest given terrible form — arcing bolts of lightning leap from its crackling body to annihilate nearby foes.",
    tier: 5,
    element: "lightning",
  },
  [UnitType.DISTORTION_ELEMENTAL]: {
    type: UnitType.DISTORTION_ELEMENTAL,
    cost: 2000,
    hp: 850,
    atk: 60,
    attackSpeed: 0.7,
    speed: 0.85,
    range: 2,
    spawnTime: 22,
    abilityTypes: [AbilityType.DISTORTION_AURA],
    spriteKey: "distortion_elemental",
    size: { width: 3.0, height: 3.0, healthBarOffset: -2.0 },
    description:
      "A rift in reality given sentience — the very fabric of space warps and tears around its unstable form.",
    tier: 5,
    element: "distortion",
  },
  [UnitType.MINOR_LIGHTNING_ELEMENTAL]: {
    type: UnitType.MINOR_LIGHTNING_ELEMENTAL,
    cost: 800,
    hp: 420,
    atk: 28,
    attackSpeed: 0.7,
    speed: 1.1,
    range: 1.5,
    spawnTime: 14,
    abilityTypes: [AbilityType.MINOR_LIGHTNING_AURA],
    spriteKey: "minor_lightning_elemental",
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "A lesser storm spirit of crackling sparks and static charge — its aura zaps those who draw near.",
    tier: 3,
    element: "lightning",
  },
  [UnitType.MINOR_DISTORTION_ELEMENTAL]: {
    type: UnitType.MINOR_DISTORTION_ELEMENTAL,
    cost: 800,
    hp: 380,
    atk: 24,
    attackSpeed: 0.8,
    speed: 0.95,
    range: 2,
    spawnTime: 14,
    abilityTypes: [AbilityType.MINOR_DISTORTION_AURA],
    spriteKey: "minor_distortion_elemental",
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "A lesser void spirit of rippling space — its unstable aura warps reality around nearby foes.",
    tier: 3,
    element: "distortion",
  },
  [UnitType.EARTH_ELEMENTAL]: {
    type: UnitType.EARTH_ELEMENTAL,
    cost: 2500,
    hp: 1400,
    atk: 75,
    attackSpeed: 0.5,
    speed: 0.6,
    range: 1.5,
    spawnTime: 25,
    abilityTypes: [],
    spriteKey: "earth_elemental",
    size: {
      width: 3.0,
      height: 3.0,
      healthBarOffset: -2.0,
    },
    description:
      "A living mountain given terrible purpose — granite plates and crystal veins form an unstoppable juggernaut that shrugs off all punishment.",
    tier: 6,
  },
  [UnitType.MINOR_EARTH_ELEMENTAL]: {
    type: UnitType.MINOR_EARTH_ELEMENTAL,
    cost: 875,
    hp: 600,
    atk: 32,
    attackSpeed: 0.6,
    speed: 0.7,
    range: 1.5,
    spawnTime: 16,
    abilityTypes: [],
    spriteKey: "minor_earth_elemental",
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    description:
      "A lesser stone spirit of cracked granite and crystal — immensely tough but slow, it grinds enemies to dust with raw strength.",
    tier: 3,
  },

  // ── Giant units (T7) ────────────────────────────────────────────────
  [UnitType.GIANT_WARRIOR]: {
    type: UnitType.GIANT_WARRIOR,
    cost: 3200,
    hp: 1200,
    atk: 100,
    attackSpeed: 0.45,
    speed: 0.45,
    range: 1,
    spawnTime: 12,
    abilityTypes: [],
    spriteKey: "giant_warrior",
    size: {
      width: 2.0,
      height: 3.0,
      healthBarOffset: -2.5,
    },
    description:
      "A towering war giant clad in heavy plate, wielding a massive iron-bound club that shatters formations on impact.",
    tier: 7,
  },
  [UnitType.GIANT_ARCHER]: {
    type: UnitType.GIANT_ARCHER,
    cost: 3000,
    hp: 700,
    atk: 85,
    attackSpeed: 0.5,
    speed: 0.3,
    range: 8,
    spawnTime: 11,
    abilityTypes: [],
    spriteKey: "giant_archer",
    size: {
      width: 2.0,
      height: 3.0,
      healthBarOffset: -2.5,
    },
    description:
      "A hill giant archer wielding a greatbow the size of a ballista — each arrow strikes with the force of a siege bolt.",
    tier: 7,
  },
  [UnitType.GIANT_SIEGE]: {
    type: UnitType.GIANT_SIEGE,
    cost: 3400,
    hp: 1500,
    atk: 130,
    attackSpeed: 0.2,
    speed: 0.2,
    range: 2,
    spawnTime: 14,
    abilityTypes: [],
    spriteKey: "giant_siege",
    siegeOnly: true,
    size: {
      width: 2.0,
      height: 3.0,
      healthBarOffset: -2.5,
    },
    description:
      "A colossal siege giant that hurls boulders at fortifications, each throw powerful enough to crack castle walls.",
    tier: 7,
  },
  [UnitType.GIANT_MAGE]: {
    type: UnitType.GIANT_MAGE,
    cost: 3200,
    hp: 600,
    atk: 95,
    attackSpeed: 0.4,
    speed: 0.25,
    range: 9,
    spawnTime: 12,
    abilityTypes: [],
    spriteKey: "giant_mage",
    size: {
      width: 2.0,
      height: 3.0,
      healthBarOffset: -2.5,
    },
    description:
      "An ancient giant steeped in primal sorcery, channelling devastating arcane blasts through a rune-carved staff.",
    tier: 7,
  },
  [UnitType.GIANT_CAVALRY]: {
    type: UnitType.GIANT_CAVALRY,
    cost: 3400,
    hp: 1000,
    atk: 90,
    attackSpeed: 0.5,
    speed: 1.3,
    range: 1,
    spawnTime: 14,
    abilityTypes: [],
    spriteKey: "giant_cavalry",
    isChargeUnit: true,
    size: {
      width: 3.0,
      height: 3.0,
      healthBarOffset: -2.5,
    },
    description:
      "A titan rider astride an armored warhorse of monstrous proportions — their thunderous charge shatters entire battle lines.",
    tier: 7,
  },
  [UnitType.ROYAL_GUARD]: {
    type: UnitType.ROYAL_GUARD,
    cost: 2400,
    hp: 1100,
    atk: 55,
    attackSpeed: 0.7,
    speed: 0.5,
    range: 1,
    spawnTime: 18,
    abilityTypes: [],
    spriteKey: "royal_guard",
    description:
      "An elite tower-shield soldier clad in gilded plate. Nearly immovable, they anchor battle lines and absorb tremendous punishment.",
    tier: 6,
    blockChance: 0.3,
  },
  [UnitType.MARKSMAN]: {
    type: UnitType.MARKSMAN,
    cost: 2200,
    hp: 500,
    atk: 90,
    attackSpeed: 0.35,
    speed: 0.4,
    range: 9,
    spawnTime: 18,
    abilityTypes: [],
    spriteKey: "marksman",
    description:
      "A master sharpshooter with a heavy arbalest. Devastating single-target damage at extreme range, but painfully slow to reload.",
    tier: 6,
  },
  [UnitType.CANNON]: {
    type: UnitType.CANNON,
    cost: 2400,
    hp: 400,
    atk: 140,
    attackSpeed: 0.15,
    speed: 0.15,
    range: 12,
    spawnTime: 20,
    abilityTypes: [],
    spriteKey: "cannon",
    siegeOnly: true,
    description:
      "A black-powder siege cannon that obliterates fortifications from extreme range. Immobile while firing, useless against troops.",
    tier: 6,
  },
  [UnitType.BATTLEMAGE]: {
    type: UnitType.BATTLEMAGE,
    cost: 2200,
    hp: 550,
    atk: 70,
    attackSpeed: 0.5,
    speed: 0.7,
    range: 5,
    spawnTime: 16,
    abilityTypes: [],
    spriteKey: "battlemage",
    element: "fire",
    description:
      "A war-hardened sorcerer in enchanted plate, wielding blade and spell alike. More resilient than a pure mage, with solid ranged damage.",
    tier: 6,
  },
  [UnitType.CATAPHRACT]: {
    type: UnitType.CATAPHRACT,
    cost: 2200,
    hp: 900,
    atk: 55,
    attackSpeed: 0.6,
    speed: 1.0,
    range: 1,
    spawnTime: 18,
    abilityTypes: [],
    spriteKey: "cataphract",
    isChargeUnit: true,
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.5,
    },
    description:
      "A fully armored knight on a barded warhorse. Slower than light cavalry but far tougher — their charge is devastating.",
    tier: 6,
  },
  // ---------------------------------------------------------------------------
  // National Mages (T1–T7) — spell abilities configured at runtime
  // ---------------------------------------------------------------------------
  [UnitType.NATIONAL_MAGE_T1]: {
    type: UnitType.NATIONAL_MAGE_T1,
    cost: 300, hp: 70, atk: 10, attackSpeed: 0.5,
    speed: 0.75, range: 5, spawnTime: 6,
    abilityTypes: [AbilityType.NATIONAL_T1_SPELL_A, AbilityType.NATIONAL_T1_SPELL_B],
    spriteKey: "mage", tier: 1, element: "fire",
    description: "A national mage wielding two chosen spells.",
  },
  [UnitType.NATIONAL_MAGE_T2]: {
    type: UnitType.NATIONAL_MAGE_T2,
    cost: 500, hp: 110, atk: 12, attackSpeed: 0.5,
    speed: 0.75, range: 5, spawnTime: 7,
    abilityTypes: [AbilityType.NATIONAL_T2_SPELL_A, AbilityType.NATIONAL_T2_SPELL_B],
    spriteKey: "mage", tier: 2, element: "fire",
    description: "An experienced national mage with two chosen spells.",
  },
  [UnitType.NATIONAL_MAGE_T3]: {
    type: UnitType.NATIONAL_MAGE_T3,
    cost: 800, hp: 160, atk: 14, attackSpeed: 0.5,
    speed: 0.75, range: 5, spawnTime: 8, regenRate: 5,
    abilityTypes: [AbilityType.NATIONAL_T3_SPELL],
    spriteKey: "mage", tier: 3, element: "fire",
    description: "A veteran national mage with a powerful chosen spell.",
  },
  [UnitType.NATIONAL_MAGE_T4]: {
    type: UnitType.NATIONAL_MAGE_T4,
    cost: 1200, hp: 220, atk: 16, attackSpeed: 0.5,
    speed: 0.75, range: 5, spawnTime: 9, regenRate: 5,
    abilityTypes: [AbilityType.NATIONAL_T4_SPELL],
    spriteKey: "mage", tier: 4, element: "fire",
    description: "A masterful national mage commanding devastating magic.",
  },
  [UnitType.NATIONAL_MAGE_T5]: {
    type: UnitType.NATIONAL_MAGE_T5,
    cost: 1800, hp: 280, atk: 18, attackSpeed: 0.5,
    speed: 0.75, range: 5, spawnTime: 10, regenRate: 5,
    abilityTypes: [AbilityType.NATIONAL_T5_SPELL],
    spriteKey: "mage", tier: 5, element: "fire",
    description: "An archmage of the nation, wielding immense magical power.",
  },
  [UnitType.NATIONAL_MAGE_T6]: {
    type: UnitType.NATIONAL_MAGE_T6,
    cost: 2600, hp: 350, atk: 20, attackSpeed: 0.5,
    speed: 0.75, range: 5, spawnTime: 11, regenRate: 5,
    abilityTypes: [AbilityType.NATIONAL_T6_SPELL],
    spriteKey: "mage", tier: 6, element: "fire",
    description: "A legendary national mage of terrifying magical might.",
  },
  [UnitType.NATIONAL_MAGE_T7]: {
    type: UnitType.NATIONAL_MAGE_T7,
    cost: 3500, hp: 430, atk: 22, attackSpeed: 0.5,
    speed: 0.75, range: 5, spawnTime: 12, regenRate: 5,
    abilityTypes: [AbilityType.NATIONAL_T7_SPELL],
    spriteKey: "mage", tier: 7, element: "fire",
    description: "The supreme national mage — a living conduit of arcane devastation.",
  },
  // ---------------------------------------------------------------------------
  // Halfling faction units
  // ---------------------------------------------------------------------------
  [UnitType.HALFLING_SLINGER]: {
    type: UnitType.HALFLING_SLINGER,
    cost: 200,
    hp: 50,
    atk: 11,
    attackSpeed: 1.2,
    speed: 1.3,
    range: 5,
    spawnTime: 2,
    abilityTypes: [],
    spriteKey: "archer",
    description:
      "Nimble halfling skirmisher whipping stones with deadly accuracy. Small, fast, and surprisingly lethal.",
    tier: 1,
  },
  [UnitType.HALFLING_CHEF]: {
    type: UnitType.HALFLING_CHEF,
    cost: 350,
    hp: 90,
    atk: 5,
    attackSpeed: 0.8,
    speed: 1.1,
    range: 3,
    spawnTime: 5,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "monk",
    isHealer: true,
    description:
      "A halfling master chef whose hearty cooking restores allies in the heat of battle. Heals nearby friendly units.",
    tier: 2,
  },
  // ---------------------------------------------------------------------------
  // Lava Children faction units
  // ---------------------------------------------------------------------------
  [UnitType.MAGMA_GOLEM]: {
    type: UnitType.MAGMA_GOLEM,
    cost: 600,
    hp: 280,
    atk: 30,
    attackSpeed: 0.6,
    speed: 0.6,
    range: 1.5,
    spawnTime: 7,
    abilityTypes: [AbilityType.FIRE_AURA],
    spriteKey: "troll",
    regenRate: 3,
    description:
      "A massive construct of living magma. Incredibly tough, burns nearby enemies with its molten aura, but ponderous and slow.",
    tier: 3,
  },
  [UnitType.LAVA_SHAMAN]: {
    type: UnitType.LAVA_SHAMAN,
    cost: 500,
    hp: 100,
    atk: 22,
    attackSpeed: 0.7,
    speed: 0.85,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.FIREBALL],
    spriteKey: "fire_mage",
    element: "fire",
    description:
      "A volcanic priest who channels raw lava into searing fireballs. Fragile but devastating at range.",
    tier: 2,
  },
  // ---------------------------------------------------------------------------
  // Dwarf faction units
  // ---------------------------------------------------------------------------
  [UnitType.DWARVEN_GUARDIAN]: {
    type: UnitType.DWARVEN_GUARDIAN,
    cost: 300,
    hp: 160,
    atk: 18,
    attackSpeed: 0.8,
    speed: 0.7,
    range: 1.5,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "royal_defender",
    description:
      "An ironclad dwarf shieldbearer. Slow but extremely tough, the backbone of any dwarven battle line.",
    tier: 1,
  },
  [UnitType.RUNESMITH]: {
    type: UnitType.RUNESMITH,
    cost: 450,
    hp: 110,
    atk: 22,
    attackSpeed: 0.65,
    speed: 0.75,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.CHAIN_LIGHTNING],
    spriteKey: "storm_mage",
    element: "lightning",
    description:
      "A master of dwarven rune-craft who inscribes lightning into stone and hurls it at foes. The pride of every hold.",
    tier: 2,
  },
  // ---------------------------------------------------------------------------
  // Orc faction units
  // ---------------------------------------------------------------------------
  [UnitType.ORC_BRUTE]: {
    type: UnitType.ORC_BRUTE,
    cost: 400,
    hp: 160,
    atk: 32,
    attackSpeed: 0.7,
    speed: 1.05,
    range: 1.5,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "berserker",
    isChargeUnit: true,
    description:
      "A hulking orc warrior who charges headlong into battle. Devastating first strike, and tough enough to keep swinging.",
    tier: 2,
  },
  [UnitType.ORC_DRUMMER]: {
    type: UnitType.ORC_DRUMMER,
    cost: 200,
    hp: 120,
    atk: 8,
    attackSpeed: 0.9,
    speed: 1.0,
    range: 1.5,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "warchief",
    description:
      "An orc war-drummer whose pounding rhythm steels nearby warriors. Not a fighter, but invaluable for morale.",
    tier: 1,
  },
  // ---------------------------------------------------------------------------
  // Undead faction units
  // ---------------------------------------------------------------------------
  [UnitType.DEATH_KNIGHT]: {
    type: UnitType.DEATH_KNIGHT,
    cost: 500,
    hp: 220,
    atk: 26,
    attackSpeed: 0.8,
    speed: 0.9,
    range: 1.5,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "cataphract",
    regenRate: 4,
    description:
      "A fallen knight raised by dark magic. Nearly indestructible, slowly regenerating from wounds that would fell the living.",
    tier: 2,
  },
  [UnitType.NECROMANCER]: {
    type: UnitType.NECROMANCER,
    cost: 550,
    hp: 75,
    atk: 20,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 6,
    spawnTime: 7,
    abilityTypes: [AbilityType.SUMMON],
    spriteKey: "dark_savant",
    element: "summon",
    description:
      "A master of death magic who raises skeletal minions to overwhelm the enemy. Fragile but endlessly productive.",
    tier: 2,
  },
  // ---------------------------------------------------------------------------
  // Demon faction units
  // ---------------------------------------------------------------------------
  [UnitType.PIT_LORD]: {
    type: UnitType.PIT_LORD,
    cost: 700,
    hp: 320,
    atk: 35,
    attackSpeed: 0.55,
    speed: 0.65,
    range: 1.5,
    spawnTime: 8,
    abilityTypes: [AbilityType.FIRE_BREATH],
    spriteKey: "cyclops",
    regenRate: 2,
    description:
      "A towering demon lord from the deepest pits. Breathes hellfire and crushes all in its path. Slow but terrifying.",
    tier: 3,
  },
  [UnitType.HELLFIRE_WARLOCK]: {
    type: UnitType.HELLFIRE_WARLOCK,
    cost: 650,
    hp: 85,
    atk: 30,
    attackSpeed: 0.6,
    speed: 0.85,
    range: 6,
    spawnTime: 7,
    abilityTypes: [AbilityType.FIREBALL, AbilityType.FIRE_IMP_SUMMON],
    spriteKey: "fire_master_mage",
    element: "fire",
    description:
      "A demonic sorcerer who rains hellfire and summons imps from the abyss to swarm the enemy.",
    tier: 3,
  },
  // ---------------------------------------------------------------------------
  // Angel faction units
  // ---------------------------------------------------------------------------
  [UnitType.SERAPHIM]: {
    type: UnitType.SERAPHIM,
    cost: 600,
    hp: 150,
    atk: 8,
    attackSpeed: 0.7,
    speed: 1.2,
    range: 4,
    spawnTime: 7,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "angel",
    isHealer: true,
    element: "heal",
    description:
      "A six-winged celestial being radiating divine light. Its healing touch can restore entire formations from the brink of death.",
    tier: 3,
  },
  [UnitType.DIVINE_CHAMPION]: {
    type: UnitType.DIVINE_CHAMPION,
    cost: 400,
    hp: 140,
    atk: 20,
    attackSpeed: 0.9,
    speed: 1.1,
    range: 1.5,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "templar",
    description:
      "A holy warrior blessed by the heavens. Fast, resilient, and strikes with righteous fury.",
    tier: 2,
  },
  // ---------------------------------------------------------------------------
  // Beastkin faction units
  // ---------------------------------------------------------------------------
  [UnitType.ALPHA_WOLF]: {
    type: UnitType.ALPHA_WOLF,
    cost: 350,
    hp: 130,
    atk: 20,
    attackSpeed: 1.0,
    speed: 1.6,
    range: 1.5,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "scout_cavalry",
    isChargeUnit: true,
    description:
      "A massive dire wolf that leads the pack. Blisteringly fast, it charges down prey and tears them apart before they can react.",
    tier: 1,
  },
  [UnitType.BEAST_SHAMAN]: {
    type: UnitType.BEAST_SHAMAN,
    cost: 400,
    hp: 95,
    atk: 18,
    attackSpeed: 0.7,
    speed: 1.0,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.SUMMON],
    spriteKey: "summoner",
    element: "nature",
    description:
      "A wild mystic who communes with nature spirits, summoning beast companions to fight alongside the pack.",
    tier: 2,
  },
  // ---------------------------------------------------------------------------
  // Golem Collective faction units
  // ---------------------------------------------------------------------------
  [UnitType.WAR_GOLEM]: {
    type: UnitType.WAR_GOLEM,
    cost: 500,
    hp: 350,
    atk: 25,
    attackSpeed: 0.5,
    speed: 0.5,
    range: 1.5,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "giant_warrior",
    regenRate: 2,
    description:
      "A colossal enchanted construct of living stone. Incredibly slow but nearly indestructible — the ultimate wall of rock.",
    tier: 2,
  },
  [UnitType.RUNE_CORE]: {
    type: UnitType.RUNE_CORE,
    cost: 350,
    hp: 120,
    atk: 15,
    attackSpeed: 0.8,
    speed: 0.7,
    range: 5,
    spawnTime: 5,
    abilityTypes: [AbilityType.DISTORTION_BLAST],
    spriteKey: "constructionist",
    element: "distortion",
    description:
      "A floating crystalline core pulsing with arcane energy. Projects distortion blasts that warp and shatter enemy formations.",
    tier: 1,
  },
  // ---------------------------------------------------------------------------
  // Pirate faction units
  // ---------------------------------------------------------------------------
  [UnitType.PIRATE_CAPTAIN]: {
    type: UnitType.PIRATE_CAPTAIN,
    cost: 350,
    hp: 140,
    atk: 18,
    attackSpeed: 1.0,
    speed: 1.15,
    range: 1.5,
    spawnTime: 4,
    abilityTypes: [AbilityType.GLADIATOR_NET],
    spriteKey: "gladiator",
    description:
      "A cunning sea-dog who fights dirty — nets enemies to pin them down, then cuts them apart with cutlass and dagger.",
    tier: 1,
  },
  [UnitType.CORSAIR_GUNNER]: {
    type: UnitType.CORSAIR_GUNNER,
    cost: 350,
    hp: 80,
    atk: 35,
    attackSpeed: 0.4,
    speed: 0.9,
    range: 6,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "marksman",
    description:
      "A pirate sharpshooter armed with a hand cannon. Devastating single shots, but painfully slow to reload.",
    tier: 1,
  },
  // ---------------------------------------------------------------------------
  // Elements faction unit
  // ---------------------------------------------------------------------------
  [UnitType.ELEMENTAL_AVATAR]: {
    type: UnitType.ELEMENTAL_AVATAR,
    cost: 800,
    hp: 250,
    atk: 30,
    attackSpeed: 0.9,
    speed: 1.0,
    range: 4,
    spawnTime: 7,
    abilityTypes: [AbilityType.FIREBALL, AbilityType.FIRE_AURA],
    spriteKey: "fireElemental",
    element: "fire",
    description:
      "A towering convergence of all primal elements — fire, ice, storm, and void swirl within its form. Hurls fireballs and radiates searing heat.",
    tier: 3,
  },
  // ---------------------------------------------------------------------------
  // Additional faction units
  // ---------------------------------------------------------------------------
  [UnitType.KNIGHT_COMMANDER]: {
    type: UnitType.KNIGHT_COMMANDER,
    cost: 500,
    hp: 150,
    atk: 12,
    attackSpeed: 0.8,
    speed: 1.3,
    range: 3,
    spawnTime: 6,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "knight_commander",
    isHealer: true,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "A mounted battlefield commander who rallies the wounded from horseback. Gallops between formations, restoring health where it's needed most.",
    tier: 2,
    element: "heal",
  },
  [UnitType.BLADEDANCER]: {
    type: UnitType.BLADEDANCER,
    cost: 450,
    hp: 85,
    atk: 22,
    attackSpeed: 1.2,
    speed: 1.5,
    range: 1,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "bladedancer",
    description:
      "An elven warrior who fights like wind through leaves — twin moonblades blur in a dance of death that shreds anything within reach.",
    tier: 2,
  },
  [UnitType.BOAR_RIDER]: {
    type: UnitType.BOAR_RIDER,
    cost: 400,
    hp: 180,
    atk: 28,
    attackSpeed: 0.7,
    speed: 1.4,
    range: 1.5,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "boar_rider",
    isChargeUnit: true,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "A savage orc mounted on a tusked war boar. The beast and rider charge as one — whatever stands in their path doesn't stand for long.",
    tier: 2,
  },
  [UnitType.CHRONOMANCER]: {
    type: UnitType.CHRONOMANCER,
    cost: 500,
    hp: 70,
    atk: 12,
    attackSpeed: 0.5,
    speed: 0.8,
    range: 6,
    spawnTime: 7,
    abilityTypes: [AbilityType.ICE_BALL, AbilityType.DISTORTION_BLAST],
    spriteKey: "chronomancer",
    element: "distortion",
    description:
      "A time-bending arcanist who freezes and warps enemies simultaneously. Foes are slowed, displaced, and utterly helpless.",
    tier: 2,
  },
  [UnitType.STORM_CONDUIT]: {
    type: UnitType.STORM_CONDUIT,
    cost: 600,
    hp: 200,
    atk: 25,
    attackSpeed: 0.7,
    speed: 1.1,
    range: 4,
    spawnTime: 6,
    abilityTypes: [AbilityType.CHAIN_LIGHTNING],
    spriteKey: "storm_conduit",
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    element: "lightning",
    description:
      "A living bolt of lightning given form — arcs of electricity leap from its crackling body to chain through enemy ranks.",
    tier: 3,
  },
  [UnitType.HALFLING_BURGLAR]: {
    type: UnitType.HALFLING_BURGLAR,
    cost: 300,
    hp: 55,
    atk: 18,
    attackSpeed: 1.3,
    speed: 1.6,
    range: 1,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "halfling_burglar",
    description:
      "A light-fingered halfling who slips past enemy lines with uncanny speed. What they lack in size, they make up for in stab frequency.",
    tier: 1,
  },
  [UnitType.OBSIDIAN_SENTINEL]: {
    type: UnitType.OBSIDIAN_SENTINEL,
    cost: 400,
    hp: 300,
    atk: 15,
    attackSpeed: 0.5,
    speed: 0.5,
    range: 1.5,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "obsidian_sentinel",
    regenRate: 4,
    description:
      "A hulking statue of volcanic glass, nearly immune to damage. It stands like a black mountain, slowly grinding attackers to dust.",
    tier: 2,
  },
  [UnitType.DWARVEN_CANNON]: {
    type: UnitType.DWARVEN_CANNON,
    cost: 600,
    hp: 150,
    atk: 65,
    attackSpeed: 0.2,
    speed: 0.4,
    range: 8,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "dwarven_cannon",
    description:
      "A masterwork dwarven cannon, compact enough for field deployment. Fires iron shot with devastating accuracy at extreme range.",
    tier: 3,
  },
  [UnitType.ORC_SHAMAN]: {
    type: UnitType.ORC_SHAMAN,
    cost: 350,
    hp: 90,
    atk: 20,
    attackSpeed: 0.6,
    speed: 0.9,
    range: 5,
    spawnTime: 5,
    abilityTypes: [AbilityType.FIREBALL],
    spriteKey: "orc_shaman",
    element: "fire",
    description:
      "A rare orc born with the gift of flame. Where most orcs solve problems with axes, this one solves them with fireballs — same result, bigger radius.",
    tier: 1,
  },
  [UnitType.BANSHEE]: {
    type: UnitType.BANSHEE,
    cost: 300,
    hp: 60,
    atk: 15,
    attackSpeed: 0.8,
    speed: 1.3,
    range: 5,
    spawnTime: 4,
    abilityTypes: [AbilityType.ICE_BALL],
    spriteKey: "banshee",
    element: "cold",
    description:
      "A wailing spirit of freezing despair. Its keening cry chills the blood and slows the living to a crawl.",
    tier: 1,
  },
  [UnitType.SUCCUBUS]: {
    type: UnitType.SUCCUBUS,
    cost: 450,
    hp: 90,
    atk: 18,
    attackSpeed: 0.9,
    speed: 1.2,
    range: 4,
    spawnTime: 5,
    abilityTypes: [AbilityType.WEB],
    spriteKey: "succubus",
    description:
      "A beguiling demon who ensnares enemies in webs of dark enchantment, rooting them helplessly while allies close in for the kill.",
    tier: 2,
  },
  [UnitType.VALKYRIE]: {
    type: UnitType.VALKYRIE,
    cost: 400,
    hp: 130,
    atk: 24,
    attackSpeed: 1.0,
    speed: 1.4,
    range: 1.5,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "valkyrie",
    isChargeUnit: true,
    description:
      "A winged holy warrior who descends from the sky like divine judgment. Her charge shatters formations with the force of heaven's fury.",
    tier: 2,
  },
  [UnitType.THUNDERHAWK]: {
    type: UnitType.THUNDERHAWK,
    cost: 350,
    hp: 80,
    atk: 16,
    attackSpeed: 1.0,
    speed: 1.8,
    range: 4,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "thunderhawk",
    description:
      "A massive raptor bonded to a Beastkin rider. Faster than any land creature, it swoops in to strike and wheels away before retaliation.",
    tier: 1,
  },
  [UnitType.SIEGE_AUTOMATON]: {
    type: UnitType.SIEGE_AUTOMATON,
    cost: 600,
    hp: 400,
    atk: 50,
    attackSpeed: 0.3,
    speed: 0.35,
    range: 5,
    spawnTime: 9,
    abilityTypes: [],
    spriteKey: "siege_automaton",
    siegeOnly: true,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "A hulking mechanical construct built for one purpose — demolition. Its rune-powered fists reduce walls and towers to rubble.",
    tier: 3,
  },
  [UnitType.POWDER_MONKEY]: {
    type: UnitType.POWDER_MONKEY,
    cost: 350,
    hp: 60,
    atk: 25,
    attackSpeed: 0.6,
    speed: 1.2,
    range: 3,
    spawnTime: 3,
    abilityTypes: [AbilityType.FIREBALL],
    spriteKey: "powder_monkey",
    element: "fire",
    description:
      "A nimble crew member armed with satchel charges and black powder bombs. Tosses explosives with gleeful abandon — stand well back.",
    tier: 1,
  },
  // ---------------------------------------------------------------------------
  // Wave 2 faction units — 2 per race
  // ---------------------------------------------------------------------------
  // ── Man ──
  [UnitType.WAR_CHAPLAIN]: {
    type: UnitType.WAR_CHAPLAIN,
    cost: 450,
    hp: 120,
    atk: 10,
    attackSpeed: 0.7,
    speed: 0.9,
    range: 4,
    spawnTime: 6,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "war_chaplain",
    isHealer: true,
    element: "heal",
    description:
      "A battlefield priest in full plate armour. His holy chants mend the broken and bolster the faithful — a walking cathedral of restoration.",
    tier: 2,
  },
  [UnitType.SHIELD_CAPTAIN]: {
    type: UnitType.SHIELD_CAPTAIN,
    cost: 550,
    hp: 280,
    atk: 14,
    attackSpeed: 0.6,
    speed: 0.6,
    range: 1,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "shield_captain",
    regenRate: 3,
    description:
      "An officer wielding an enormous tower shield. Nearly impossible to kill from the front, he anchors the line while his men rally behind him.",
    tier: 2,
    blockChance: 0.3,
  },
  // ── Elves ──
  [UnitType.TREANT_GUARDIAN]: {
    type: UnitType.TREANT_GUARDIAN,
    cost: 600,
    hp: 350,
    atk: 22,
    attackSpeed: 0.5,
    speed: 0.5,
    range: 1.5,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "treant_guardian",
    regenRate: 6,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "An ancient tree awakened to war. Its bark turns blades and its roots drag foes into the earth. Slow but nearly unkillable.",
    tier: 3,
  },
  [UnitType.MOONWEAVER]: {
    type: UnitType.MOONWEAVER,
    cost: 500,
    hp: 65,
    atk: 18,
    attackSpeed: 0.6,
    speed: 0.9,
    range: 6,
    spawnTime: 6,
    abilityTypes: [AbilityType.DISTORTION_BLAST],
    spriteKey: "moonweaver",
    element: "distortion",
    description:
      "An elven mage who weaves moonlight into bolts of warped reality. Enemies struck are displaced and disoriented.",
    tier: 2,
  },
  // ── Horde ──
  [UnitType.SIEGE_TROLL]: {
    type: UnitType.SIEGE_TROLL,
    cost: 500,
    hp: 250,
    atk: 45,
    attackSpeed: 0.3,
    speed: 0.5,
    range: 5,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "siege_troll",
    siegeOnly: true,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "A hulking troll that uproots boulders and hurls them at walls. Useless against soldiers, devastating against structures.",
    tier: 2,
  },
  [UnitType.BLOOD_BERSERKER]: {
    type: UnitType.BLOOD_BERSERKER,
    cost: 500,
    hp: 110,
    atk: 30,
    attackSpeed: 1.3,
    speed: 1.5,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "blood_berserker",
    regenRate: 5,
    description:
      "A frenzied warrior who feeds on the blood of the fallen. Each swing restores vitality — the more he kills, the harder he is to stop.",
    tier: 2,
  },
  // ── Adept ──
  [UnitType.SPELL_WEAVER]: {
    type: UnitType.SPELL_WEAVER,
    cost: 700,
    hp: 75,
    atk: 15,
    attackSpeed: 0.5,
    speed: 0.8,
    range: 6,
    spawnTime: 7,
    abilityTypes: [AbilityType.FIREBALL, AbilityType.CHAIN_LIGHTNING],
    spriteKey: "spell_weaver",
    element: "fire",
    description:
      "A rare arcanist who channels fire and lightning simultaneously. Two elements, twice the devastation.",
    tier: 3,
  },
  [UnitType.MANA_WRAITH]: {
    type: UnitType.MANA_WRAITH,
    cost: 450,
    hp: 50,
    atk: 22,
    attackSpeed: 0.9,
    speed: 1.3,
    range: 5,
    spawnTime: 5,
    abilityTypes: [AbilityType.DISTORTION_BLAST],
    spriteKey: "mana_wraith",
    element: "distortion",
    description:
      "A sentient vortex of raw mana given form. It drifts through the battlefield, siphoning energy and unleashing distortion blasts.",
    tier: 2,
  },
  // ── Elements ──
  [UnitType.FROST_WYRM]: {
    type: UnitType.FROST_WYRM,
    cost: 800,
    hp: 220,
    atk: 35,
    attackSpeed: 0.6,
    speed: 1.0,
    range: 4,
    spawnTime: 7,
    abilityTypes: [AbilityType.FROST_BREATH],
    spriteKey: "frost_wyrm",
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    element: "cold",
    description:
      "A serpentine wyrm of living ice. Its breath flash-freezes everything in a cone before it, turning battlefields into frozen wastelands.",
    tier: 3,
  },
  [UnitType.MAGMA_TITAN]: {
    type: UnitType.MAGMA_TITAN,
    cost: 700,
    hp: 400,
    atk: 40,
    attackSpeed: 0.4,
    speed: 0.4,
    range: 1.5,
    spawnTime: 8,
    abilityTypes: [AbilityType.FIRE_AURA],
    spriteKey: "magma_titan",
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    element: "fire",
    description:
      "A towering colossus of molten rock and seething flame. Each step leaves pools of lava, and its fists shatter the earth itself.",
    tier: 3,
  },
  // ── Halflings ──
  [UnitType.HALFLING_RIDER]: {
    type: UnitType.HALFLING_RIDER,
    cost: 300,
    hp: 90,
    atk: 16,
    attackSpeed: 0.9,
    speed: 1.6,
    range: 1,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "halfling_rider",
    isChargeUnit: true,
    description:
      "A halfling mounted on a giant spiny hedgehog. The beast rolls into enemies at terrifying speed — surprisingly effective for something so adorable.",
    tier: 1,
  },
  [UnitType.HALFLING_ALCHEMIST]: {
    type: UnitType.HALFLING_ALCHEMIST,
    cost: 350,
    hp: 50,
    atk: 14,
    attackSpeed: 0.7,
    speed: 1.0,
    range: 4,
    spawnTime: 5,
    abilityTypes: [AbilityType.FIREBALL],
    spriteKey: "halfling_alchemist",
    element: "fire",
    description:
      "A diminutive chemist who hurls volatile potions. Some explode, some dissolve, and some do things best left unmentioned.",
    tier: 1,
  },
  // ── Lava Children ──
  [UnitType.CINDER_WRAITH]: {
    type: UnitType.CINDER_WRAITH,
    cost: 350,
    hp: 70,
    atk: 20,
    attackSpeed: 0.8,
    speed: 1.4,
    range: 4,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "cinder_wraith",
    element: "fire",
    description:
      "A ghostly flame given hunger and purpose. It flickers across the battlefield, hurling cinders at anything that breathes.",
    tier: 1,
  },
  [UnitType.VOLCANIC_BEHEMOTH]: {
    type: UnitType.VOLCANIC_BEHEMOTH,
    cost: 700,
    hp: 450,
    atk: 55,
    attackSpeed: 0.25,
    speed: 0.3,
    range: 4,
    spawnTime: 9,
    abilityTypes: [],
    spriteKey: "volcanic_behemoth",
    siegeOnly: true,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "A walking volcano that hurls chunks of molten rock at fortifications. The ground cracks and smokes wherever it treads.",
    tier: 3,
  },
  // ── Dwarves ──
  [UnitType.IRONBREAKER]: {
    type: UnitType.IRONBREAKER,
    cost: 500,
    hp: 250,
    atk: 20,
    attackSpeed: 0.8,
    speed: 0.7,
    range: 1,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "ironbreaker",
    regenRate: 3,
    description:
      "The elite of dwarven infantry. Clad in gromril plate from helm to boot, they form an impenetrable wall of enchanted steel.",
    tier: 2,
    blockChance: 0.25,
  },
  [UnitType.THUNDERER]: {
    type: UnitType.THUNDERER,
    cost: 450,
    hp: 100,
    atk: 35,
    attackSpeed: 0.4,
    speed: 0.7,
    range: 6,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "thunderer",
    description:
      "A dwarven handgunner whose masterwork firearm punches through armour at extreme range. Slow to reload, but every shot counts.",
    tier: 2,
  },
  // ── Orcs ──
  [UnitType.WYVERN_RIDER]: {
    type: UnitType.WYVERN_RIDER,
    cost: 600,
    hp: 160,
    atk: 30,
    attackSpeed: 0.7,
    speed: 1.6,
    range: 1.5,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "wyvern_rider",
    isChargeUnit: true,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "An orc mounted on a venomous wyvern. The pair dive from above, striking with devastating force before wheeling away for another pass.",
    tier: 3,
  },
  [UnitType.PIT_FIGHTER]: {
    type: UnitType.PIT_FIGHTER,
    cost: 450,
    hp: 95,
    atk: 22,
    attackSpeed: 1.2,
    speed: 1.3,
    range: 1,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "pit_fighter",
    description:
      "A scarred arena champion wielding twin axes. Years in the fighting pits have honed reflexes that make him a blur of steel.",
    tier: 2,
  },
  // ── Undead ──
  [UnitType.BONE_COLOSSUS]: {
    type: UnitType.BONE_COLOSSUS,
    cost: 650,
    hp: 380,
    atk: 50,
    attackSpeed: 0.3,
    speed: 0.35,
    range: 5,
    spawnTime: 9,
    abilityTypes: [],
    spriteKey: "bone_colossus",
    siegeOnly: true,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "A monstrous construct of fused bones and dark magic, animated solely to tear down walls. Each massive fist is a battering ram of ossified death.",
    tier: 3,
  },
  [UnitType.WRAITH_LORD]: {
    type: UnitType.WRAITH_LORD,
    cost: 500,
    hp: 130,
    atk: 25,
    attackSpeed: 0.8,
    speed: 1.2,
    range: 3,
    spawnTime: 6,
    abilityTypes: [AbilityType.ICE_BALL],
    spriteKey: "wraith_lord",
    element: "cold",
    regenRate: 5,
    description:
      "An ancient king's spirit, clad in spectral armour. Its chilling presence freezes the blood of the living and its phantom blade cuts through steel like mist.",
    tier: 2,
  },
  // ── Demons ──
  [UnitType.DOOM_GUARD]: {
    type: UnitType.DOOM_GUARD,
    cost: 550,
    hp: 220,
    atk: 32,
    attackSpeed: 0.7,
    speed: 0.9,
    range: 1.5,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "doom_guard",
    size: { width: 1.5, height: 1.5 },
    description:
      "An armoured demon of terrifying discipline. Unlike its chaotic kin, the Doom Guard fights with cold precision and an enormous fel-iron greatsword.",
    tier: 2,
  },
  [UnitType.IMP_OVERLORD]: {
    type: UnitType.IMP_OVERLORD,
    cost: 450,
    hp: 80,
    atk: 12,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.FIRE_IMP_SUMMON],
    spriteKey: "imp_overlord",
    element: "summon",
    description:
      "A bloated demon lord who commands legions of fire imps. It rarely fights directly — why bother when you can send a horde of screaming imps instead?",
    tier: 2,
  },
  // ── Angels ──
  [UnitType.ARCHON]: {
    type: UnitType.ARCHON,
    cost: 600,
    hp: 180,
    atk: 28,
    attackSpeed: 0.9,
    speed: 1.2,
    range: 1.5,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "archon",
    regenRate: 4,
    description:
      "A supreme celestial warrior encased in golden divine armour. Its radiant presence inspires allies and its blade burns with holy fire.",
    tier: 3,
  },
  [UnitType.CELESTIAL_ARCHER]: {
    type: UnitType.CELESTIAL_ARCHER,
    cost: 450,
    hp: 90,
    atk: 24,
    attackSpeed: 0.8,
    speed: 1.1,
    range: 6,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "celestial_archer",
    description:
      "An angelic marksman whose arrows trail holy light. Each shot seeks the wicked with unerring accuracy across the entire battlefield.",
    tier: 2,
  },
  // ── Beastkin ──
  [UnitType.DIRE_BEAR]: {
    type: UnitType.DIRE_BEAR,
    cost: 500,
    hp: 300,
    atk: 28,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 1.5,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "dire_bear",
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    regenRate: 4,
    description:
      "A massive cave bear bonded to the Beastkin tribe. It absorbs punishment like a living fortress and mauls anything within reach of its claws.",
    tier: 2,
  },
  [UnitType.SERPENT_PRIEST]: {
    type: UnitType.SERPENT_PRIEST,
    cost: 400,
    hp: 75,
    atk: 16,
    attackSpeed: 0.7,
    speed: 0.9,
    range: 5,
    spawnTime: 5,
    abilityTypes: [AbilityType.WEB],
    spriteKey: "serpent_priest",
    element: "nature",
    description:
      "A serpent-scaled shaman who commands venomous magic. Its webs of nature magic root enemies while poison seeps through their veins.",
    tier: 2,
  },
  // ── Golem Collective ──
  [UnitType.CRYSTAL_GOLEM]: {
    type: UnitType.CRYSTAL_GOLEM,
    cost: 500,
    hp: 200,
    atk: 25,
    attackSpeed: 0.6,
    speed: 0.6,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.CHAIN_LIGHTNING],
    spriteKey: "crystal_golem",
    element: "lightning",
    description:
      "A golem of living crystal that channels lightning through its prismatic body. Arcs of electricity leap from facet to facet before striking foes.",
    tier: 2,
  },
  [UnitType.IRON_COLOSSUS]: {
    type: UnitType.IRON_COLOSSUS,
    cost: 700,
    hp: 500,
    atk: 35,
    attackSpeed: 0.4,
    speed: 0.4,
    range: 1.5,
    spawnTime: 9,
    abilityTypes: [],
    spriteKey: "iron_colossus",
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "The ultimate expression of golem engineering — a walking mountain of rune-etched iron. It doesn't so much fight as simply advance through anything in its path.",
    tier: 3,
  },
  // ── Pirates ──
  [UnitType.SEA_WITCH]: {
    type: UnitType.SEA_WITCH,
    cost: 500,
    hp: 70,
    atk: 18,
    attackSpeed: 0.6,
    speed: 0.9,
    range: 6,
    spawnTime: 6,
    abilityTypes: [AbilityType.CHAIN_LIGHTNING, AbilityType.ICE_BALL],
    spriteKey: "sea_witch",
    element: "lightning",
    description:
      "A storm sorceress who calls down tempests on her enemies. Lightning and ice crash together as she cackles from the crow's nest.",
    tier: 2,
  },
  [UnitType.BOARDING_MASTER]: {
    type: UnitType.BOARDING_MASTER,
    cost: 400,
    hp: 100,
    atk: 20,
    attackSpeed: 1.2,
    speed: 1.4,
    range: 1,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "boarding_master",
    description:
      "A dual-cutlass fighter trained in the brutal art of ship-to-ship combat. Fast, vicious, and utterly without mercy.",
    tier: 2,
  },
  // ---------------------------------------------------------------------------
  // New generic units
  // ---------------------------------------------------------------------------
  [UnitType.NOVICE_PRIEST]: {
    type: UnitType.NOVICE_PRIEST,
    cost: 250,
    hp: 60,
    atk: 5,
    attackSpeed: 0.8,
    speed: 0.6,
    range: 3,
    spawnTime: 8,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "novice_priest",
    element: "heal",
    description:
      "A humble healer just beginning their calling. Weak in combat but provides essential battlefield healing at a low cost.",
    tier: 1,
  },
  [UnitType.SKIRMISHER]: {
    type: UnitType.SKIRMISHER,
    cost: 300,
    hp: 55,
    atk: 10,
    attackSpeed: 1.2,
    speed: 1.0,
    range: 5,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "skirmisher",
    description:
      "A fast, agile javelin thrower who harasses enemies from a distance. Fragile but hard to catch.",
    tier: 1,
  },
  [UnitType.HEAVY_LANCER]: {
    type: UnitType.HEAVY_LANCER,
    cost: 1200,
    hp: 250,
    atk: 35,
    attackSpeed: 0.7,
    speed: 0.9,
    range: 1.5,
    spawnTime: 14,
    abilityTypes: [],
    spriteKey: "heavy_lancer",
    isChargeUnit: true,
    critChance: 0.1,
    size: { width: 2.0, height: 2.0, healthBarOffset: -1.0 },
    description:
      "An elite heavily armored lancer on a barded warhorse. Slower than light cavalry but devastating on the charge.",
    tier: 4,
  },
  [UnitType.DEBUFFER_WARLOCK]: {
    type: UnitType.DEBUFFER_WARLOCK,
    cost: 700,
    hp: 80,
    atk: 15,
    attackSpeed: 0.7,
    speed: 0.5,
    range: 6,
    spawnTime: 12,
    abilityTypes: [AbilityType.DISTORTION_BLAST],
    spriteKey: "debuffer_warlock",
    element: "distortion",
    description:
      "A shadow mage who weakens enemies with distortion magic. Low damage but disrupts enemy formations.",
    tier: 3,
  },
  [UnitType.WAR_DRUMMER]: {
    type: UnitType.WAR_DRUMMER,
    cost: 350,
    hp: 90,
    atk: 8,
    attackSpeed: 0.6,
    speed: 0.7,
    range: 1.2,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "war_drummer",
    description:
      "A battlefield musician whose thunderous drumming inspires nearby allies. Not a fighter, but invaluable for morale.",
    tier: 1,
  },
  // ---------------------------------------------------------------------------
  // New faction units
  // ---------------------------------------------------------------------------
  [UnitType.HORDE_ARCHER]: {
    type: UnitType.HORDE_ARCHER,
    cost: 300,
    hp: 65,
    atk: 12,
    attackSpeed: 0.9,
    speed: 0.7,
    range: 5.5,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "horde_archer",
    description:
      "A crude but effective orc bowman. What they lack in finesse they make up for in raw power and aggression.",
    tier: 1,
  },
  [UnitType.HORDE_HEALER]: {
    type: UnitType.HORDE_HEALER,
    cost: 350,
    hp: 70,
    atk: 6,
    attackSpeed: 0.7,
    speed: 0.6,
    range: 3,
    spawnTime: 9,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "horde_healer",
    element: "heal",
    description:
      "A tribal shaman who channels ancestral spirits to mend the wounded. Rough but effective battlefield healing.",
    tier: 1,
  },
  [UnitType.STONE_FIST]: {
    type: UnitType.STONE_FIST,
    cost: 400,
    hp: 180,
    atk: 18,
    attackSpeed: 0.6,
    speed: 0.5,
    range: 1.2,
    spawnTime: 10,
    abilityTypes: [],
    spriteKey: "stone_fist",
    blockChance: 0.15,
    description:
      "A living statue of enchanted stone that pummels foes with rune-carved fists. Slow but extremely durable.",
    tier: 2,
  },
  [UnitType.BLADE_ADEPT]: {
    type: UnitType.BLADE_ADEPT,
    cost: 350,
    hp: 80,
    atk: 16,
    attackSpeed: 1.0,
    speed: 0.8,
    range: 1.5,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "blade_adept",
    critChance: 0.1,
    description:
      "A mage-warrior who channels arcane energy through an enchanted blade. Fast, precise, and deadly.",
    tier: 1,
  },
  [UnitType.BUCCANEER]: {
    type: UnitType.BUCCANEER,
    cost: 400,
    hp: 160,
    atk: 14,
    attackSpeed: 0.8,
    speed: 0.6,
    range: 1.2,
    spawnTime: 9,
    abilityTypes: [],
    spriteKey: "buccaneer",
    blockChance: 0.2,
    description:
      "A heavily armored pirate fighter with a buckler and cutlass. Holds the line while the crew flanks.",
    tier: 2,
  },
};
