// Stats, costs, animation keys for all unit types
import { UnitType, AbilityType } from "@/types";

export interface UnitDef {
  type: UnitType;
  cost: number; // gold cost to train
  hp: number;
  atk: number; // damage per hit
  attackSpeed: number; // attacks per second
  speed: number; // tiles per second
  range: number; // attack range in tiles
  spawnTime: number; // seconds to train
  abilityTypes: AbilityType[];
  spriteKey: string;
  /** If true, unit ignores enemy units and only attacks buildings/bases. */
  siegeOnly?: boolean;
  /** If set, unit always prefers the nearest enemy of these types over all others. */
  huntTargets?: UnitType[];
}

export const UNIT_DEFINITIONS: Record<UnitType, UnitDef> = {
  [UnitType.SWORDSMAN]: {
    type: UnitType.SWORDSMAN,
    cost: 30,
    hp: 100,
    atk: 15,
    attackSpeed: 1.0,
    speed: 2,
    range: 1,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "swordsman",
  },
  [UnitType.ARCHER]: {
    type: UnitType.ARCHER,
    cost: 40,
    hp: 70,
    atk: 20,
    attackSpeed: 0.8,
    speed: 2,
    range: 4,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "archer",
  },
  [UnitType.KNIGHT]: {
    type: UnitType.KNIGHT,
    cost: 60,
    hp: 180,
    atk: 25,
    attackSpeed: 0.7,
    speed: 3,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "knight",
  },
  [UnitType.FIRE_MAGE]: {
    type: UnitType.FIRE_MAGE,
    cost: 80,
    hp: 60,
    atk: 10,
    attackSpeed: 0.5,
    speed: 1.5,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.FIREBALL],
    spriteKey: "mage",
  },
  [UnitType.STORM_MAGE]: {
    type: UnitType.STORM_MAGE,
    cost: 80,
    hp: 60,
    atk: 10,
    attackSpeed: 0.5,
    speed: 1.5,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.CHAIN_LIGHTNING],
    spriteKey: "mage",
  },
  [UnitType.PIKEMAN]: {
    type: UnitType.PIKEMAN,
    cost: 35,
    hp: 90,
    atk: 18,
    attackSpeed: 0.9,
    speed: 1.8,
    range: 2,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "pikeman",
  },
  [UnitType.SUMMONED]: {
    type: UnitType.SUMMONED,
    cost: 0,
    hp: 40,
    atk: 10,
    attackSpeed: 1.2,
    speed: 2.5,
    range: 1,
    spawnTime: 0,
    abilityTypes: [],
    spriteKey: "summoned",
  },
  [UnitType.BATTERING_RAM]: {
    type: UnitType.BATTERING_RAM,
    cost: 80,
    hp: 300,
    atk: 60,
    attackSpeed: 0.4,
    speed: 1.0,
    range: 1,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "battering_ram",
    siegeOnly: true,
  },
  [UnitType.MAGE_HUNTER]: {
    type: UnitType.MAGE_HUNTER,
    cost: 50,
    hp: 80,
    atk: 22,
    attackSpeed: 1.1,
    speed: 2.5,
    range: 1,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "mage_hunter",
    huntTargets: [UnitType.FIRE_MAGE, UnitType.STORM_MAGE],
  },
  [UnitType.SIEGE_HUNTER]: {
    type: UnitType.SIEGE_HUNTER,
    cost: 60,
    hp: 120,
    atk: 35,
    attackSpeed: 0.9,
    speed: 3.0,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "siege_hunter",
    huntTargets: [UnitType.BATTERING_RAM],
  },
  [UnitType.SUMMONER]: {
    type: UnitType.SUMMONER,
    cost: 120,
    hp: 55,
    atk: 5,
    attackSpeed: 0.4,
    speed: 1.5,
    range: 6,
    spawnTime: 8,
    abilityTypes: [AbilityType.SUMMON],
    spriteKey: "mage",
  },
  [UnitType.COLD_MAGE]: {
    type: UnitType.COLD_MAGE,
    cost: 100,
    hp: 55,
    atk: 5,
    attackSpeed: 0.4,
    speed: 1.5,
    range: 6,
    spawnTime: 7,
    abilityTypes: [AbilityType.ICE_BALL],
    spriteKey: "cold_mage",
  },
  [UnitType.SPIDER]: {
    type: UnitType.SPIDER,
    cost: 60,
    hp: 65,
    atk: 8,
    attackSpeed: 0.7,
    speed: 2.2,
    range: 4,
    spawnTime: 5,
    abilityTypes: [AbilityType.WEB],
    spriteKey: "spider",
  },
  [UnitType.GLADIATOR]: {
    type: UnitType.GLADIATOR,
    cost: 70,
    hp: 140,
    atk: 20,
    attackSpeed: 0.8,
    speed: 2.0,
    range: 4,
    spawnTime: 6,
    abilityTypes: [AbilityType.GLADIATOR_NET],
    spriteKey: "gladiator",
  },
};
