// Stats, costs, animation keys for all unit types
import { UnitType, AbilityType } from "@/types";

export interface UnitDef {
  type: UnitType;
  cost: number; // gold cost to train
  hp: number;
  atk: number; // damage per hit
  attackSpeed: number; // attacks per second
  speed: number; // tiles per second
  range: number; // attack range in tiles
  spawnTime: number; // seconds to train
  abilityTypes: AbilityType[];
  spriteKey: string;
  /** If true, unit ignores enemy units and only attacks buildings/bases. */
  siegeOnly?: boolean;
  /** If set, unit always prefers the nearest enemy of these types over all others. */
  huntTargets?: UnitType[];
  /** If true, unit ignores all combat and only seeks neutral buildings to capture. */
  diplomatOnly?: boolean;
  /** Visual size properties for rendering */
  size?: {
    width: number; // multiplier for sprite width (1.0 = normal)
    height: number; // multiplier for sprite height (1.0 = normal)
    healthBarOffset?: number; // Y offset for health bar (negative = higher)
  };
  /** Flavor text for shop description */
  description?: string;
  /** If true, the unit deals 5x damage on its first hit. */
  isChargeUnit?: boolean;
  /** If true, the unit targets and heals friendly units instead of attacking enemies. */
  isHealer?: boolean;
  /** Maximum number of this unit type a single player may own at once. */
  maxCount?: number;
}

export const UNIT_DEFINITIONS: Record<UnitType, UnitDef> = {
  [UnitType.SWORDSMAN]: {
    type: UnitType.SWORDSMAN,
    cost: 150,
    hp: 100,
    atk: 15,
    attackSpeed: 1.0,
    speed: 1,
    range: 1,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "swordsman",
    description:
      "A sturdy frontline warrior with reliable steel and unwavering courage.",
  },
  [UnitType.TEMPLAR]: {
    type: UnitType.TEMPLAR,
    cost: 350,
    hp: 150,
    atk: 20,
    attackSpeed: 1.0,
    speed: 1,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "templar",
    description:
      "Holy warrior in shining armor. Better protected than swordsmen with divine blessing.",
  },
  [UnitType.ASSASSIN]: {
    type: UnitType.ASSASSIN,
    cost: 800,
    hp: 65,
    atk: 40,
    attackSpeed: 1.3,
    speed: 1.5,
    range: 1,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "assassin",
    description:
      "Deadly melee striker in black garb with sword and dagger. Fast and lethal but fragile.",
  },
  [UnitType.REPEATER]: {
    type: UnitType.REPEATER,
    cost: 820,
    hp: 80,
    atk: 15,
    attackSpeed: 2.0,
    speed: 1,
    range: 3,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "repeater",
    description:
      "Rapid-fire crossbow. Low range but shoots very fast in close quarters.",
  },
  [UnitType.ARCHER]: {
    type: UnitType.ARCHER,
    cost: 200,
    hp: 70,
    atk: 20,
    attackSpeed: 0.8,
    speed: 1,
    range: 4,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "archer",
    description:
      "Deadly marksman who rains arrows from afar, picking off enemies before they can strike.",
  },
  [UnitType.LONGBOWMAN]: {
    type: UnitType.LONGBOWMAN,
    cost: 275,
    hp: 65,
    atk: 14,
    attackSpeed: 0.7,
    speed: 0.9,
    range: 6,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "longbowman",
    description:
      "Elite archer with unmatched range, capable of striking enemies from across the battlefield.",
  },
  [UnitType.CROSSBOWMAN]: {
    type: UnitType.CROSSBOWMAN,
    cost: 300,
    hp: 75,
    atk: 30,
    attackSpeed: 0.5,
    speed: 0.9,
    range: 3,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "crossbowman",
    description:
      "Heavy crossbowman who delivers devastating bolts at the cost of slower reload speed.",
  },
  [UnitType.KNIGHT]: {
    type: UnitType.KNIGHT,
    cost: 300,
    hp: 180,
    atk: 25,
    attackSpeed: 0.7,
    speed: 1.5,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "knight",
    description:
      "Armored cavalry unit that charges into battle with devastating force and speed.",
  },
  [UnitType.QUESTING_KNIGHT]: {
    type: UnitType.QUESTING_KNIGHT,
    cost: 300,
    hp: 200,
    atk: 28,
    attackSpeed: 0.7,
    speed: 1.5,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "questing_knight",
    size: {
      width: 1.5,
      height: 1.5,
      healthBarOffset: -0.8,
    },
    description:
      "He does not actually do alot of questing, except for the Queen's favor.",
  },
  [UnitType.FIRE_MAGE]: {
    type: UnitType.FIRE_MAGE,
    cost: 400,
    hp: 60,
    atk: 10,
    attackSpeed: 0.5,
    speed: 0.75,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.FIREBALL],
    spriteKey: "mage",
    description:
      "Pyromancer who hurls explosive fireballs, engulfing enemies in flames.",
  },
  [UnitType.STORM_MAGE]: {
    type: UnitType.STORM_MAGE,
    cost: 400,
    hp: 60,
    atk: 10,
    attackSpeed: 0.5,
    speed: 0.75,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.CHAIN_LIGHTNING],
    spriteKey: "mage",
    description:
      "Storm caller who unleashes devastating lightning bolts from the heavens.",
  },
  [UnitType.PIKEMAN]: {
    type: UnitType.PIKEMAN,
    cost: 175,
    hp: 90,
    atk: 18,
    attackSpeed: 0.9,
    speed: 0.9,
    range: 2,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "pikeman",
  },
  [UnitType.SUMMONED]: {
    type: UnitType.SUMMONED,
    cost: 100,
    hp: 40,
    atk: 10,
    attackSpeed: 1.2,
    speed: 1.25,
    range: 1,
    spawnTime: 0,
    abilityTypes: [],
    spriteKey: "summoned",
  },
  [UnitType.BATTERING_RAM]: {
    type: UnitType.BATTERING_RAM,
    cost: 400,
    hp: 300,
    atk: 60,
    attackSpeed: 0.4,
    speed: 0.5,
    range: 1,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "battering_ram",
    siegeOnly: true,
  },
  [UnitType.MAGE_HUNTER]: {
    type: UnitType.MAGE_HUNTER,
    cost: 250,
    hp: 80,
    atk: 22,
    attackSpeed: 1.1,
    speed: 1.25,
    range: 1,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "mage_hunter",
    huntTargets: [UnitType.FIRE_MAGE, UnitType.STORM_MAGE],
  },
  [UnitType.SIEGE_HUNTER]: {
    type: UnitType.SIEGE_HUNTER,
    cost: 300,
    hp: 120,
    atk: 35,
    attackSpeed: 0.9,
    speed: 1.5,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "siege_hunter",
    huntTargets: [
      UnitType.BATTERING_RAM,
      UnitType.CATAPULT,
      UnitType.SIEGE_CATAPULT,
      UnitType.TREBUCHET,
    ],
  },
  [UnitType.SUMMONER]: {
    type: UnitType.SUMMONER,
    cost: 750,
    hp: 55,
    atk: 5,
    attackSpeed: 0.4,
    speed: 0.75,
    range: 6,
    spawnTime: 8,
    abilityTypes: [AbilityType.SUMMON],
    spriteKey: "golem",
  },
  [UnitType.CONSTRUCTIONIST]: {
    type: UnitType.CONSTRUCTIONIST,
    cost: 1200,
    hp: 55,
    atk: 5,
    attackSpeed: 0.4,
    speed: 0.75,
    range: 6,
    spawnTime: 8,
    abilityTypes: [AbilityType.SUMMON],
    spriteKey: "constructionist",
  },
  [UnitType.COLD_MAGE]: {
    type: UnitType.COLD_MAGE,
    cost: 500,
    hp: 55,
    atk: 5,
    attackSpeed: 0.4,
    speed: 0.75,
    range: 6,
    spawnTime: 7,
    abilityTypes: [AbilityType.ICE_BALL],
    spriteKey: "cold_mage",
  },
  [UnitType.SPIDER]: {
    type: UnitType.SPIDER,
    cost: 300,
    hp: 65,
    atk: 8,
    attackSpeed: 0.7,
    speed: 1.1,
    range: 4,
    spawnTime: 5,
    abilityTypes: [AbilityType.WEB],
    spriteKey: "spider",
  },
  [UnitType.GLADIATOR]: {
    type: UnitType.GLADIATOR,
    cost: 350,
    hp: 140,
    atk: 20,
    attackSpeed: 0.8,
    speed: 1.0,
    range: 4,
    spawnTime: 6,
    abilityTypes: [AbilityType.GLADIATOR_NET],
    spriteKey: "gladiator",
  },
  [UnitType.DIPLOMAT]: {
    type: UnitType.DIPLOMAT,
    cost: 300,
    hp: 80,
    atk: 0,
    attackSpeed: 0,
    speed: 1.25,
    range: 0,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "diplomat",
    diplomatOnly: true,
  },
  [UnitType.DISTORTION_MAGE]: {
    type: UnitType.DISTORTION_MAGE,
    cost: 450,
    hp: 65,
    atk: 10,
    attackSpeed: 0.6,
    speed: 0.8,
    range: 5,
    spawnTime: 6,
    abilityTypes: [AbilityType.DISTORTION_BLAST],
    spriteKey: "mage",
  },
  [UnitType.VOID_SNAIL]: {
    type: UnitType.VOID_SNAIL,
    cost: 250,
    hp: 120,
    atk: 5,
    attackSpeed: 0.4,
    speed: 0.5,
    range: 3,
    spawnTime: 5,
    abilityTypes: [AbilityType.VOID_DISTORTION],
    spriteKey: "spider", // placeholder or snail-like
  },
  [UnitType.FAERY_QUEEN]: {
    type: UnitType.FAERY_QUEEN,
    cost: 750,
    hp: 80,
    atk: 15,
    attackSpeed: 0.7,
    speed: 1.1,
    range: 6,
    spawnTime: 10,
    abilityTypes: [AbilityType.FAERY_DISTORTION],
    spriteKey: "cold_mage", // placeholder or fairy-like
  },
  [UnitType.GIANT_FROG]: {
    type: UnitType.GIANT_FROG,
    cost: 500,
    hp: 200,
    atk: 10,
    attackSpeed: 0.6,
    speed: 0.9,
    range: 7,
    spawnTime: 6,
    abilityTypes: [AbilityType.FROG_TONGUE],
    spriteKey: "spider", // placeholder (spider-like legs/movement)
  },
  [UnitType.DEVOURER]: {
    type: UnitType.DEVOURER,
    cost: 650,
    hp: 350,
    atk: 15,
    attackSpeed: 0.5,
    speed: 0.6,
    range: 3,
    spawnTime: 8,
    abilityTypes: [AbilityType.DEVOUR_PULL],
    spriteKey: "swordsman", // placeholder (tanky humanoid)
  },
  [UnitType.TROLL]: {
    type: UnitType.TROLL,
    cost: 700,
    hp: 400,
    atk: 25,
    attackSpeed: 0.6,
    speed: 0.5,
    range: 1,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "troll",
    description:
      "Massive troll with immense health. Slow but devastating in melee.",
  },
  [UnitType.RHINO]: {
    type: UnitType.RHINO,
    cost: 500,
    hp: 350,
    atk: 15,
    attackSpeed: 0.5,
    speed: 0.6,
    range: 1,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "rhino",
    size: { width: 2.0, height: 1.0 },
    description:
      "Armored rhino with thick skin. Slow but tanky, charges at enemies with its horn.",
  },
  [UnitType.PIXIE]: {
    type: UnitType.PIXIE,
    cost: 150,
    hp: 40,
    atk: 8,
    attackSpeed: 0.8,
    speed: 1.8,
    range: 5,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "pixie",
    description:
      "Small ethereal pixie with magic attacks. Flies quickly and casts spells with its outstretched arms.",
  },
  [UnitType.BAT]: {
    type: UnitType.BAT,
    cost: 150,
    hp: 30,
    atk: 10,
    attackSpeed: 1.2,
    speed: 2.0,
    range: 1,
    spawnTime: 2,
    abilityTypes: [],
    spriteKey: "bat",
    description:
      "Swarm of tiny bats. Very fast but fragile. Overwhelms enemies with numbers.",
  },
  [UnitType.HORSE_ARCHER]: {
    type: UnitType.HORSE_ARCHER,
    cost: 350,
    hp: 100,
    atk: 15,
    attackSpeed: 0.8,
    speed: 1.75,
    range: 4,
    spawnTime: 6,
    abilityTypes: [],
    spriteKey: "knight", // placeholder (mounted)
  },
  [UnitType.SHORTBOW]: {
    type: UnitType.SHORTBOW,
    cost: 150,
    hp: 60,
    atk: 10,
    attackSpeed: 1.2,
    speed: 1.1,
    range: 3,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "archer", // placeholder
  },
  [UnitType.BALLISTA]: {
    type: UnitType.BALLISTA,
    cost: 500,
    hp: 120,
    atk: 50,
    attackSpeed: 0.3,
    speed: 0.5,
    range: 5,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "battering_ram", // placeholder (siege)
  },
  [UnitType.BOLT_THROWER]: {
    type: UnitType.BOLT_THROWER,
    cost: 600,
    hp: 100,
    atk: 30,
    attackSpeed: 0.2, // slow but long range
    speed: 0.5,
    range: 7,
    spawnTime: 10,
    abilityTypes: [],
    spriteKey: "bolt_thrower",
  },
  [UnitType.CATAPULT]: {
    type: UnitType.CATAPULT,
    cost: 900,
    hp: 150,
    atk: 40,
    attackSpeed: 0.15,
    speed: 0.4,
    range: 8,
    spawnTime: 12,
    abilityTypes: [],
    spriteKey: "catapult",
    description:
      "Heavy catapult that launches boulders in a high arc, devastating buildings from extreme range.",
  },
  [UnitType.SIEGE_CATAPULT]: {
    type: UnitType.SIEGE_CATAPULT,
    cost: 400,
    hp: 200,
    atk: 55,
    attackSpeed: 0.1,
    speed: 0.3,
    range: 11,
    spawnTime: 15,
    abilityTypes: [],
    spriteKey: "siege_catapult",
    size: {
      width: 2.0,
      height: 1.0,
      healthBarOffset: -0.5,
    },
    description:
      "Massive siege catapult with extreme range, hurling enormous boulders that crush anything in their path.",
  },
  [UnitType.TREBUCHET]: {
    type: UnitType.TREBUCHET,
    cost: 300,
    hp: 250,
    atk: 70,
    attackSpeed: 0.07,
    speed: 0.2,
    range: 200,
    spawnTime: 18,
    abilityTypes: [],
    spriteKey: "trebuchet",
    siegeOnly: true,
    size: {
      width: 2.0,
      height: 2.0,
      healthBarOffset: -1.0,
    },
    description:
      "Colossal trebuchet capable of bombarding fortifications from incredible distance.",
  },
  [UnitType.SCOUT_CAVALRY]: {
    type: UnitType.SCOUT_CAVALRY,
    cost: 200,
    hp: 60,
    atk: 10,
    attackSpeed: 1.0,
    speed: 1.6,
    range: 1,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "scout_cavalry",
    isChargeUnit: true,
  },
  [UnitType.LANCER]: {
    type: UnitType.LANCER,
    cost: 350,
    hp: 120,
    atk: 20,
    attackSpeed: 0.8,
    speed: 1.5,
    range: 1,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "lancer",
    isChargeUnit: true,
  },
  [UnitType.ROYAL_LANCER]: {
    type: UnitType.ROYAL_LANCER,
    cost: 900,
    hp: 220,
    atk: 40,
    attackSpeed: 0.9,
    speed: 1.5,
    range: 1,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "royal_lancer",
    isChargeUnit: true,
  },
  [UnitType.ELITE_LANCER]: {
    type: UnitType.ELITE_LANCER,
    cost: 500,
    hp: 180,
    atk: 25,
    attackSpeed: 0.8,
    speed: 1.4,
    range: 1,
    spawnTime: 7,
    abilityTypes: [],
    spriteKey: "elite_lancer",
    isChargeUnit: true,
  },
  [UnitType.KNIGHT_LANCER]: {
    type: UnitType.KNIGHT_LANCER,
    cost: 650,
    hp: 250,
    atk: 30,
    attackSpeed: 0.6,
    speed: 1.1,
    range: 1,
    spawnTime: 8,
    abilityTypes: [],
    spriteKey: "knight_lancer",
    isChargeUnit: true,
  },
  [UnitType.MONK]: {
    type: UnitType.MONK,
    cost: 250,
    hp: 80,
    atk: 0,
    attackSpeed: 0.8,
    speed: 1,
    range: 1.5,
    spawnTime: 4,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "diplomat", // placeholder (religious robes)
    isHealer: true,
  },
  [UnitType.CLERIC]: {
    type: UnitType.CLERIC,
    cost: 450,
    hp: 120,
    atk: 0,
    attackSpeed: 0.6,
    speed: 0.9,
    range: 3,
    spawnTime: 7,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "mage", // placeholder
    isHealer: true,
  },
  [UnitType.SAINT]: {
    type: UnitType.SAINT,
    cost: 750,
    hp: 200,
    atk: 0,
    attackSpeed: 0.5,
    speed: 0.75,
    range: 5,
    spawnTime: 10,
    abilityTypes: [AbilityType.HEAL],
    spriteKey: "faery_queen", // placeholder (ethereal/divine)
    isHealer: true,
  },
  [UnitType.RED_DRAGON]: {
    type: UnitType.RED_DRAGON,
    cost: 1250,
    hp: 500,
    atk: 35,
    attackSpeed: 0.8,
    speed: 1.2,
    range: 2,
    spawnTime: 15,
    abilityTypes: [AbilityType.FIRE_BREATH],
    spriteKey: "red_dragon",
    size: {
      width: 1.0, // normal width
      height: 2.0, // 2x taller than normal
      healthBarOffset: -0.8, // health bar positioned higher
    },
    description:
      "Ancient red dragon that breathes devastating fire, scorching all who dare oppose it.",
  },
  [UnitType.FROST_DRAGON]: {
    type: UnitType.FROST_DRAGON,
    cost: 1200,
    hp: 480,
    atk: 30,
    attackSpeed: 0.8,
    speed: 1.2,
    range: 2,
    spawnTime: 15,
    abilityTypes: [AbilityType.FROST_BREATH],
    spriteKey: "frost_dragon",
    size: {
      width: 1.0, // normal width
      height: 2.0, // 2x taller than normal
      healthBarOffset: -0.8, // health bar positioned higher
    },
    description:
      "Mighty ice dragon whose freezing breath slows enemies to a crawl before shattering them.",
  },
  [UnitType.CYCLOPS]: {
    type: UnitType.CYCLOPS,
    cost: 1750, // Very expensive
    hp: 800, // Very high hitpoints
    atk: 60, // Very high attack
    attackSpeed: 0.6, // Slow but devastating attacks
    speed: 0.8, // Slow movement
    range: 1.5, // Melee with slightly extended reach due to club
    spawnTime: 20, // Long training time
    abilityTypes: [], // Basic melee attacks only
    spriteKey: "cyclops",
    size: {
      width: 2.0, // 2 tiles wide
      height: 3.0, // 3 tiles tall
      healthBarOffset: -2.0, // Health bar positioned very high
    },
    description:
      "Massive one-eyed giant wielding a tree trunk, crushing enemies with earth-shattering blows.",
  },
  [UnitType.ANGEL]: {
    type: UnitType.ANGEL,
    cost: 4000,
    hp: 1500,
    atk: 90,
    attackSpeed: 0.7,
    speed: 1.2,
    range: 1,
    spawnTime: 25,
    abilityTypes: [],
    spriteKey: "angel",
    size: {
      width: 2.0,
      height: 3.0,
      healthBarOffset: -2.0,
    },
    description:
      "Divine celestial warrior of the heavens, wielding a blazing sword and radiating holy light.",
  },
  [UnitType.DARK_SAVANT]: {
    type: UnitType.DARK_SAVANT,
    cost: 3300,
    hp: 200,
    atk: 35,
    attackSpeed: 0.5,
    speed: 0.75,
    range: 5,
    spawnTime: 15,
    abilityTypes: [AbilityType.FIREBALL],
    spriteKey: "fire_mage",
    description:
      "Master of dark pyromancy who hurls devastating fireballs with increased destructive power.",
  },
  [UnitType.HALBERDIER]: {
    type: UnitType.HALBERDIER,
    cost: 200,
    hp: 105,
    atk: 22,
    attackSpeed: 1.0,
    speed: 1.0,
    range: 2,
    spawnTime: 3,
    abilityTypes: [],
    spriteKey: "halberdier",
    description:
      "Elite human infantry wielding a halberd. Tougher and harder-hitting than the common pikeman.",
  },
  [UnitType.ELVEN_ARCHER]: {
    type: UnitType.ELVEN_ARCHER,
    cost: 300,
    hp: 70,
    atk: 17,
    attackSpeed: 0.75,
    speed: 1.0,
    range: 7,
    spawnTime: 5,
    abilityTypes: [],
    spriteKey: "elven_archer",
    description:
      "Graceful elven marksman with unparalleled range and precision, striking from positions others cannot reach.",
  },
  [UnitType.HERO]: {
    type: UnitType.HERO,
    cost: 250,
    hp: 120,
    atk: 18,
    attackSpeed: 1.1,
    speed: 1.2,
    range: 1,
    spawnTime: 4,
    abilityTypes: [],
    spriteKey: "hero",
    maxCount: 4,
    description:
      "Legendary warrior whose prowess inspires allies and terrifies foes. Max: 4",
  },
};
