// Upgrade definitions for blacksmith
import { UpgradeType } from "@/types";

export interface UpgradeDef {
  type: UpgradeType;
  cost: number;
  manaCost?: number; // If set, deducts mana instead of gold
  maxLevel: number;
  effect: number; // percentage multiplier (e.g., 0.2 for 20%)
  description: string;
  appliesTo: UnitType[];
  isSpell?: boolean; // If true, this is a repeatable spell (no permanent level)
  summonUnit?: UnitType; // Unit type summoned by spell placement
  spellType?: "summon" | "damage" | "heal"; // Type of spell effect
  spellDamage?: number; // Damage dealt to enemies in radius
  spellHeal?: number; // HP restored to friendlies in radius
  spellRadius?: number; // Area of effect radius in tiles
}

import { UnitType } from "@/types";

export const UPGRADE_DEFINITIONS: Record<UpgradeType, UpgradeDef> = {
  [UpgradeType.MELEE_DAMAGE]: {
    type: UpgradeType.MELEE_DAMAGE,
    cost: 500,
    maxLevel: 3,
    effect: 0.2, // 20% damage increase per level
    description: "Increases melee unit damage by 20%.",
    appliesTo: [
      UnitType.SWORDSMAN,
      UnitType.PIKEMAN,
      UnitType.KNIGHT,
      UnitType.QUESTING_KNIGHT,
      UnitType.MAGE_HUNTER,
      UnitType.GLADIATOR,
      UnitType.HERO,
    ],
  },
  [UpgradeType.MELEE_HEALTH]: {
    type: UpgradeType.MELEE_HEALTH,
    cost: 500,
    maxLevel: 3,
    effect: 0.2, // 20% health increase per level
    description: "Increases melee unit health by 20%.",
    appliesTo: [
      UnitType.SWORDSMAN,
      UnitType.PIKEMAN,
      UnitType.KNIGHT,
      UnitType.QUESTING_KNIGHT,
      UnitType.MAGE_HUNTER,
      UnitType.GLADIATOR,
      UnitType.HERO,
    ],
  },
  [UpgradeType.RANGED_DAMAGE]: {
    type: UpgradeType.RANGED_DAMAGE,
    cost: 500,
    maxLevel: 3,
    effect: 0.2, // 20% damage increase per level
    description: "Increases ranged unit damage by 20%.",
    appliesTo: [
      UnitType.ARCHER,
      UnitType.CROSSBOWMAN,
      UnitType.LONGBOWMAN,
      UnitType.ELVEN_ARCHER,
    ],
  },
  [UpgradeType.RANGED_HEALTH]: {
    type: UpgradeType.RANGED_HEALTH,
    cost: 500,
    maxLevel: 3,
    effect: 0.2, // 20% health increase per level
    description: "Increases ranged unit health by 20%.",
    appliesTo: [
      UnitType.ARCHER,
      UnitType.CROSSBOWMAN,
      UnitType.LONGBOWMAN,
      UnitType.ELVEN_ARCHER,
    ],
  },
  [UpgradeType.SIEGE_DAMAGE]: {
    type: UpgradeType.SIEGE_DAMAGE,
    cost: 500,
    maxLevel: 3,
    effect: 0.2, // 20% damage increase per level
    description: "Increases siege unit damage by 20%.",
    appliesTo: [
      UnitType.BALLISTA,
      UnitType.BATTERING_RAM,
    ],
  },
  [UpgradeType.SIEGE_HEALTH]: {
    type: UpgradeType.SIEGE_HEALTH,
    cost: 500,
    maxLevel: 3,
    effect: 0.2, // 20% health increase per level
    description: "Increases siege unit health by 20%.",
    appliesTo: [
      UnitType.BALLISTA,
      UnitType.BATTERING_RAM,
    ],
  },
  [UpgradeType.CREATURE_DAMAGE]: {
    type: UpgradeType.CREATURE_DAMAGE,
    cost: 500,
    maxLevel: 3,
    effect: 0.2, // 20% damage increase per level
    description: "Increases creature unit damage by 20%.",
    appliesTo: [
      UnitType.CYCLOPS,
      UnitType.RED_DRAGON,
      UnitType.FROST_DRAGON,
    ],
  },
  [UpgradeType.CREATURE_HEALTH]: {
    type: UpgradeType.CREATURE_HEALTH,
    cost: 500,
    maxLevel: 3,
    effect: 0.2, // 20% health increase per level
    description: "Increases creature unit health by 20%.",
    appliesTo: [
      UnitType.CYCLOPS,
      UnitType.RED_DRAGON,
      UnitType.FROST_DRAGON,
    ],
  },
  [UpgradeType.MAGE_RANGE]: {
    type: UpgradeType.MAGE_RANGE,
    cost: 500,
    maxLevel: 3,
    effect: 0.1, // 10% range increase per level
    description: "Increases mage unit range by 10%.",
    appliesTo: [
      UnitType.FIRE_MAGE,
      UnitType.STORM_MAGE,
      UnitType.COLD_MAGE,
      UnitType.DISTORTION_MAGE,
      UnitType.SUMMONER,
    ],
  },
  [UpgradeType.FLAG]: {
    type: UpgradeType.FLAG,
    cost: 500,
    maxLevel: 1,
    effect: 0,
    description: "Unlock rally flag (F key, 100g per use).",
    appliesTo: [],
  },
  [UpgradeType.TOWER_RANGE]: {
    type: UpgradeType.TOWER_RANGE,
    cost: 500,
    maxLevel: 3,
    effect: 1, // +1 tile range per level (additive)
    description: "Increases all tower turret range by 1 tile.",
    appliesTo: [],
  },
  [UpgradeType.TOWER_DAMAGE]: {
    type: UpgradeType.TOWER_DAMAGE,
    cost: 500,
    maxLevel: 3,
    effect: 0.2, // 20% damage increase per level
    description: "Increases all tower turret damage by 20%.",
    appliesTo: [],
  },
  [UpgradeType.TOWER_HEALTH]: {
    type: UpgradeType.TOWER_HEALTH,
    cost: 500,
    maxLevel: 3,
    effect: 0.3, // 30% health increase per level
    description: "Increases all tower building health by 30%.",
    appliesTo: [],
  },
  [UpgradeType.TOWER_COST]: {
    type: UpgradeType.TOWER_COST,
    cost: 500,
    maxLevel: 3,
    effect: 0.15, // 15% cost reduction per level
    description: "Reduces the gold cost of all tower buildings by 15%.",
    appliesTo: [],
  },
  [UpgradeType.SETTLER]: {
    type: UpgradeType.SETTLER,
    cost: 600,
    maxLevel: 5,
    effect: 0,
    description: "Deploy a settler to construct a forward castle on neutral land.",
    appliesTo: [],
  },
  [UpgradeType.ENGINEER]: {
    type: UpgradeType.ENGINEER,
    cost: 350,
    maxLevel: 5,
    effect: 0,
    description: "Deploy an engineer to construct a forward tower on neutral land.",
    appliesTo: [],
  },
  [UpgradeType.SUMMON_UNICORN]: {
    type: UpgradeType.SUMMON_UNICORN,
    cost: 0,
    manaCost: 100,
    maxLevel: 99,
    effect: 0,
    description: "Summon a majestic unicorn at the target location. Costs 100 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.UNICORN,
  },
  [UpgradeType.SUMMON_PIXIE]: {
    type: UpgradeType.SUMMON_PIXIE,
    cost: 0,
    manaCost: 50,
    maxLevel: 99,
    effect: 0,
    description: "Summon a pixie at the target location. Costs 50 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.PIXIE,
  },
  [UpgradeType.SUMMON_FIRE_ELEMENTAL]: {
    type: UpgradeType.SUMMON_FIRE_ELEMENTAL,
    cost: 0,
    manaCost: 150,
    maxLevel: 99,
    effect: 0,
    description: "Conjure a fire elemental from the arcane flames. Costs 150 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.FIRE_ELEMENTAL,
  },
  [UpgradeType.SUMMON_ICE_ELEMENTAL]: {
    type: UpgradeType.SUMMON_ICE_ELEMENTAL,
    cost: 0,
    manaCost: 150,
    maxLevel: 99,
    effect: 0,
    description: "Crystallize an ice elemental from frozen mana. Costs 150 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.ICE_ELEMENTAL,
  },
  [UpgradeType.SUMMON_RED_DRAGON]: {
    type: UpgradeType.SUMMON_RED_DRAGON,
    cost: 0,
    manaCost: 500,
    maxLevel: 99,
    effect: 0,
    description: "Call forth a fearsome red dragon from the arcane depths. Costs 500 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.RED_DRAGON,
  },
  [UpgradeType.SUMMON_FROST_DRAGON]: {
    type: UpgradeType.SUMMON_FROST_DRAGON,
    cost: 0,
    manaCost: 500,
    maxLevel: 99,
    effect: 0,
    description: "Summon an ancient frost dragon wreathed in blizzard. Costs 500 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.FROST_DRAGON,
  },
  [UpgradeType.SUMMON_SPIDER_BROOD]: {
    type: UpgradeType.SUMMON_SPIDER_BROOD,
    cost: 0,
    manaCost: 30,
    maxLevel: 99,
    effect: 0,
    description: "Spawn a venomous spider from shadow webs. Costs 30 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.SPIDER,
  },
  [UpgradeType.SUMMON_TROLL]: {
    type: UpgradeType.SUMMON_TROLL,
    cost: 0,
    manaCost: 120,
    maxLevel: 99,
    effect: 0,
    description: "Summon a regenerating troll warrior. Costs 120 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.TROLL,
  },
  [UpgradeType.SUMMON_ANGEL]: {
    type: UpgradeType.SUMMON_ANGEL,
    cost: 0,
    manaCost: 300,
    maxLevel: 99,
    effect: 0,
    description: "Call down a divine angel from the heavens. Costs 300 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.ANGEL,
  },
  [UpgradeType.SUMMON_CYCLOPS]: {
    type: UpgradeType.SUMMON_CYCLOPS,
    cost: 0,
    manaCost: 400,
    maxLevel: 99,
    effect: 0,
    description: "Awaken a mighty cyclops from its ancient slumber. Costs 400 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.CYCLOPS,
  },
  [UpgradeType.SUMMON_BAT_SWARM]: {
    type: UpgradeType.SUMMON_BAT_SWARM,
    cost: 0,
    manaCost: 25,
    maxLevel: 99,
    effect: 0,
    description: "Release a bat from the archive belfry. Costs 25 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.BAT,
  },
  [UpgradeType.SUMMON_DARK_SAVANT]: {
    type: UpgradeType.SUMMON_DARK_SAVANT,
    cost: 0,
    manaCost: 250,
    maxLevel: 99,
    effect: 0,
    description: "Bind a dark savant from the forbidden tomes. Costs 250 mana.",
    appliesTo: [],
    isSpell: true,
    spellType: "summon",
    summonUnit: UnitType.DARK_SAVANT,
  },

  // ── Damage Spells ───────────────────────────────────────────────
  [UpgradeType.SPELL_ARCANE_MISSILE]: {
    type: UpgradeType.SPELL_ARCANE_MISSILE,
    cost: 0,
    manaCost: 30,
    maxLevel: 99,
    effect: 0,
    description: "Launch an arcane bolt that damages enemies in a small area.",
    appliesTo: [],
    isSpell: true,
    spellType: "damage",
    spellDamage: 20,
    spellRadius: 1.5,
  },
  [UpgradeType.SPELL_FIREBALL]: {
    type: UpgradeType.SPELL_FIREBALL,
    cost: 0,
    manaCost: 60,
    maxLevel: 99,
    effect: 0,
    description: "Hurl a blazing fireball that explodes on impact.",
    appliesTo: [],
    isSpell: true,
    spellType: "damage",
    spellDamage: 35,
    spellRadius: 2,
  },
  [UpgradeType.SPELL_BLIZZARD]: {
    type: UpgradeType.SPELL_BLIZZARD,
    cost: 0,
    manaCost: 80,
    maxLevel: 99,
    effect: 0,
    description: "Unleash a freezing blizzard across a wide area.",
    appliesTo: [],
    isSpell: true,
    spellType: "damage",
    spellDamage: 25,
    spellRadius: 3,
  },
  [UpgradeType.SPELL_LIGHTNING_STRIKE]: {
    type: UpgradeType.SPELL_LIGHTNING_STRIKE,
    cost: 0,
    manaCost: 50,
    maxLevel: 99,
    effect: 0,
    description: "Call down a focused lightning bolt on a single point.",
    appliesTo: [],
    isSpell: true,
    spellType: "damage",
    spellDamage: 45,
    spellRadius: 1,
  },
  [UpgradeType.SPELL_EARTHQUAKE]: {
    type: UpgradeType.SPELL_EARTHQUAKE,
    cost: 0,
    manaCost: 120,
    maxLevel: 99,
    effect: 0,
    description: "Shake the earth beneath your foes across a vast area.",
    appliesTo: [],
    isSpell: true,
    spellType: "damage",
    spellDamage: 30,
    spellRadius: 4,
  },
  [UpgradeType.SPELL_METEOR_STRIKE]: {
    type: UpgradeType.SPELL_METEOR_STRIKE,
    cost: 0,
    manaCost: 200,
    maxLevel: 99,
    effect: 0,
    description: "Summon a devastating meteor from the heavens.",
    appliesTo: [],
    isSpell: true,
    spellType: "damage",
    spellDamage: 60,
    spellRadius: 2.5,
  },
  [UpgradeType.SPELL_VOID_RIFT]: {
    type: UpgradeType.SPELL_VOID_RIFT,
    cost: 0,
    manaCost: 150,
    maxLevel: 99,
    effect: 0,
    description: "Tear a rift in reality that damages all caught within.",
    appliesTo: [],
    isSpell: true,
    spellType: "damage",
    spellDamage: 50,
    spellRadius: 2,
  },
  [UpgradeType.SPELL_HOLY_SMITE]: {
    type: UpgradeType.SPELL_HOLY_SMITE,
    cost: 0,
    manaCost: 70,
    maxLevel: 99,
    effect: 0,
    description: "Strike enemies with divine radiance.",
    appliesTo: [],
    isSpell: true,
    spellType: "damage",
    spellDamage: 30,
    spellRadius: 1.5,
  },
  [UpgradeType.SPELL_POISON_CLOUD]: {
    type: UpgradeType.SPELL_POISON_CLOUD,
    cost: 0,
    manaCost: 40,
    maxLevel: 99,
    effect: 0,
    description: "Release a noxious cloud that weakens enemies in a wide area.",
    appliesTo: [],
    isSpell: true,
    spellType: "damage",
    spellDamage: 15,
    spellRadius: 3,
  },
  [UpgradeType.SPELL_ARCANE_STORM]: {
    type: UpgradeType.SPELL_ARCANE_STORM,
    cost: 0,
    manaCost: 250,
    maxLevel: 99,
    effect: 0,
    description: "Conjure a massive arcane tempest that ravages a huge area.",
    appliesTo: [],
    isSpell: true,
    spellType: "damage",
    spellDamage: 40,
    spellRadius: 3.5,
  },

  // ── Healing Spells ──────────────────────────────────────────────
  [UpgradeType.SPELL_HEALING_WAVE]: {
    type: UpgradeType.SPELL_HEALING_WAVE,
    cost: 0,
    manaCost: 50,
    maxLevel: 99,
    effect: 0,
    description: "Send a wave of restorative energy to heal nearby allies.",
    appliesTo: [],
    isSpell: true,
    spellType: "heal",
    spellHeal: 30,
    spellRadius: 2,
  },
  [UpgradeType.SPELL_DIVINE_RESTORATION]: {
    type: UpgradeType.SPELL_DIVINE_RESTORATION,
    cost: 0,
    manaCost: 120,
    maxLevel: 99,
    effect: 0,
    description: "Call upon divine power to restore health to all allies in a large area.",
    appliesTo: [],
    isSpell: true,
    spellType: "heal",
    spellHeal: 60,
    spellRadius: 3,
  },
};
