// ---------------------------------------------------------------------------
// Plague Doctor RT — balance constants
// ---------------------------------------------------------------------------

export const PLAGUE_RT_BALANCE = {
  // Grid
  GRID_W: Math.max(16, Math.floor((typeof window !== "undefined" ? window.innerWidth - 40 : 800) / 48)),
  GRID_H: Math.max(12, Math.floor((typeof window !== "undefined" ? window.innerHeight - 120 : 600) / 48)),
  TILE_SIZE: 48,

  // Player
  PLAYER_SPEED: 180,
  PLAYER_ACCEL: 12,
  PLAYER_DECEL: 8,
  TREAT_TIME: 1.8,
  CURE_PERCENT: 0.4,
  TREAT_RANGE: 1.5,
  HERB_COLLECT_RANGE: 0.8,
  HERB_MAGNET_RANGE: 1.8,
  HERB_MAGNET_SPEED: 120,
  GARLIC_DURATION: 12,

  // Houses
  HOUSE_COUNT: 14,
  HOUSE_MIN_VILLAGERS: 1,
  HOUSE_MAX_VILLAGERS: 4,

  // Spread
  SPREAD_RATE: 1.8,
  SPREAD_RADIUS: 2,
  NEIGHBOR_SPREAD: 0.6,
  NIGHT_MULT: 1.8,
  CRITICAL_THRESHOLD: 70,
  CRITICAL_SPREAD_MULT: 1.5,
  CRITICAL_TREAT_PENALTY: 0.7,

  // Day/night
  DAY_DURATION: 90,
  NIGHT_START: 0.65,
  NIGHT_END: 0.15,
  NIGHT_WARN: 0.55,
  DAY_TRANSITION_TIME: 2.5,

  // Herbs
  HERB_SPAWN_INTERVAL: 3.5,
  HERB_MAX: 10,
  HERB_SPAWN_FLASH: 0.8,
  HERB_WEIGHT_LAVENDER: 45,
  HERB_WEIGHT_WORMWOOD: 22,
  HERB_WEIGHT_GARLIC: 23,
  HERB_WEIGHT_MANDRAKE: 10,

  // Crafting
  CRAFT_REMEDY_LAVENDER: 1,
  CRAFT_SMOKE_WORMWOOD: 1,
  CRAFT_SMOKE_GARLIC: 1,
  CRAFT_INCENSE_LAVENDER: 1,
  CRAFT_INCENSE_WORMWOOD: 1,
  CRAFT_TRAP_GARLIC: 2,

  // Items
  SMOKE_DURATION: 12,
  SMOKE_RADIUS: 2,
  SMOKE_SLOW: 0.15,
  INCENSE_DURATION: 30,
  TRAP_RADIUS: 2.5,

  // Rats
  RAT_SPAWN_INTERVAL: 10,
  RAT_SPEED: 65,
  RAT_AURA: 1.5,
  RAT_INFECTION_PER_SEC: 3.5,
  RAT_WAVE_INTERVAL: 35,
  RAT_WAVE_BASE: 3,
  RAT_MAX: 15,
  GARLIC_REPEL_RANGE: 3,
  RAT_DEATH_ANIM: 0.5,
  RAT_SWARM_RADIUS: 2,
  RAT_SWARM_SPEED_MULT: 1.3,
  WAVE_PREVIEW_TIME: 4,

  // Difficulty
  DIFFICULTY_RAMP: 0.012,
  DIFFICULTY_MAX: 3.0,
  GRACE_PERIOD: 15,

  // Win/lose
  WIN_PERCENT: 0.5,
  LOSE_PERCENT: 0.8,

  // Scoring
  SCORE_SAVED: 100,
  SCORE_DAY: 50,
  SCORE_CURE: 25,
  SCORE_RAT_KILL: 15,
  SCORE_PCT_BONUS: 5,
  COMBO_STREAK_TIMEOUT: 15,
  COMBO_MULT_PER: 0.15,
  COMBO_MULT_MAX: 3.0,
  STREAK_BONUS: 50,

  // Well
  WELL_RADIUS: 2,
  WELL_HEAL_PER_SEC: 1.2,
  WELL_PROXIMITY: 1.5,

  // Church
  CHURCH_RADIUS: 3,
  CHURCH_SLOW: 0.4,

  // Float text
  FLOAT_TEXT_DURATION: 1.2,
  FLOAT_TEXT_RISE: 30,

  // Shake
  SHAKE_DURATION: 0.35,
  SHAKE_INTENSITY: 7,

  // Heal beam
  HEAL_BEAM_SPEED: 3,
  HEAL_BEAM_PARTICLES: 4,
} as const;
