// Shared type aliases and enums used across sim/ and view/

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/** Integer or fractional tile coordinate pair. */
export interface Vec2 {
  x: number;
  y: number;
}

/** Strict integer tile coordinate (x, y must be whole numbers). */
export interface TileCoord {
  x: number;
  y: number;
}

/** Opaque string identifying a player. */
export type PlayerId = string;

/** Sentinel used for neutral / unowned entities. */
export const NEUTRAL_PLAYER: PlayerId = "__neutral__";

/** Map corner slot for a player's base in multi-player games. */
export type PlayerSlot = "nw" | "ne" | "sw" | "se";

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export enum Direction {
  WEST = "west",
  EAST = "east",
  NORTH = "north",
  SOUTH = "south",
}

export enum UnitType {
  SWORDSMAN = "swordsman",
  TEMPLAR = "templar",
  ARCHER = "archer",
  LONGBOWMAN = "longbowman",
  CROSSBOWMAN = "crossbowman",
  KNIGHT = "knight",
  FIRE_MAGE = "fire_mage",
  STORM_MAGE = "storm_mage",
  PIKEMAN = "pikeman",
  SUMMONED = "summoned",
  BATTERING_RAM = "battering_ram",
  MAGE_HUNTER = "mage_hunter",
  SIEGE_HUNTER = "siege_hunter",
  ASSASSIN = "assassin",
  REPEATER = "repeater",
  SUMMONER = "summoner",
  CONSTRUCTIONIST = "constructionist",
  COLD_MAGE = "cold_mage",
  SPIDER = "spider",
  GLADIATOR = "gladiator",
  DIPLOMAT = "diplomat",
  SETTLER = "settler",
  ENGINEER = "engineer",
  UNICORN = "unicorn",
  DISTORTION_MAGE = "distortion_mage",
  FIRE_ADEPT_MAGE = "fire_adept_mage",
  COLD_ADEPT_MAGE = "cold_adept_mage",
  LIGHTNING_ADEPT_MAGE = "lightning_adept_mage",
  DISTORTION_ADEPT_MAGE = "distortion_adept_mage",
  FIRE_MASTER_MAGE = "fire_master_mage",
  COLD_MASTER_MAGE = "cold_master_mage",
  LIGHTNING_MASTER_MAGE = "lightning_master_mage",
  DISTORTION_MASTER_MAGE = "distortion_master_mage",
  VOID_SNAIL = "void_snail",
  FAERY_QUEEN = "faery_queen",
  GIANT_FROG = "giant_frog",
  DEVOURER = "devourer",
  TROLL = "troll",
  RHINO = "rhino",
  PIXIE = "pixie",
  FIRE_IMP = "fire_imp",
  ICE_IMP = "ice_imp",
  LIGHTNING_IMP = "lightning_imp",
  DISTORTION_IMP = "distortion_imp",
  BAT = "bat",
  VAMPIRE_BAT = "vampire_bat",
  HORSE_ARCHER = "horse_archer",
  SHORTBOW = "shortbow",
  BALLISTA = "ballista",
  BOLT_THROWER = "bolt_thrower",
  CATAPULT = "catapult",
  SIEGE_CATAPULT = "siege_catapult",
  TREBUCHET = "trebuchet",
  WAR_WAGON = "war_wagon",
  BOMBARD = "bombard",
  SIEGE_TOWER = "siege_tower",
  HELLFIRE_MORTAR = "hellfire_mortar",
  SCOUT_CAVALRY = "scout_cavalry",
  LANCER = "lancer",
  ELITE_LANCER = "elite_lancer",
  ROYAL_LANCER = "royal_lancer",
  KNIGHT_LANCER = "knight_lancer",
  MONK = "monk",
  CLERIC = "cleric",
  SAINT = "saint",
  RED_DRAGON = "red_dragon",
  FROST_DRAGON = "frost_dragon",
  CYCLOPS = "cyclops",
  HALBERDIER = "halberdier",
  ELVEN_ARCHER = "elven_archer",
  HERO = "hero",
  QUESTING_KNIGHT = "questing_knight",
  ANGEL = "angel",
  DARK_SAVANT = "dark_savant",
  DEFENDER = "defender",
  PHALANX = "phalanx",
  ROYAL_PHALANX = "royal_phalanx",
  ROYAL_DEFENDER = "royal_defender",
  AXEMAN = "axeman",
  BERSERKER = "berserker",
  ANCIENT_DEFENDER = "ancient_defender",
  ANCIENT_PHALANX = "ancient_phalanx",
  ANCIENT_AXEMAN = "ancient_axeman",
  ELDER_DEFENDER = "elder_defender",
  ELDER_PHALANX = "elder_phalanx",
  ELDER_AXEMAN = "elder_axeman",
  ANCIENT_ARCHER = "ancient_archer",
  ANCIENT_LONGBOWMAN = "ancient_longbowman",
  ANCIENT_CROSSBOWMAN = "ancient_crossbowman",
  ELDER_ARCHER = "elder_archer",
  ELDER_REPEATER = "elder_repeater",
  ELDER_JAVELINEER = "elder_javelineer",
  ELDER_HORSE_ARCHER = "elder_horse_archer",
  JAVELINEER = "javelin",
  ARBALESTIER = "arbelestier",
  ROYAL_ARBALESTIER = "royal_arbelestier",
  WARCHIEF = "warchief",
  ARCHMAGE = "archmage",
  RUFUS = "rufus",
  TROUBADOUR = "troubadour",
  GIANT_COURT_JESTER = "giant_court_jester",
  FISHERMAN = "fisherman",
  FIRE_ELEMENTAL = "fire_elemental",
  ICE_ELEMENTAL = "ice_elemental",
  MINOR_FIRE_ELEMENTAL = "minor_fire_elemental",
  MINOR_ICE_ELEMENTAL = "minor_ice_elemental",
  LIGHTNING_ELEMENTAL = "lightning_elemental",
  DISTORTION_ELEMENTAL = "distortion_elemental",
  MINOR_LIGHTNING_ELEMENTAL = "minor_lightning_elemental",
  MINOR_DISTORTION_ELEMENTAL = "minor_distortion_elemental",
  EARTH_ELEMENTAL = "earth_elemental",
  MINOR_EARTH_ELEMENTAL = "minor_earth_elemental",
  GIANT_WARRIOR = "giant_warrior",
  GIANT_ARCHER = "giant_archer",
  GIANT_SIEGE = "giant_siege",
  GIANT_MAGE = "giant_mage",
  GIANT_CAVALRY = "giant_cavalry",
  ROYAL_GUARD = "royal_guard",
  MARKSMAN = "marksman",
  CANNON = "cannon",
  BATTLEMAGE = "battlemage",
  CATAPHRACT = "cataphract",
}

export enum BuildingType {
  CASTLE = "castle",
  BARRACKS = "barracks",
  STABLES = "stables",
  MAGE_TOWER = "mage_tower",
  ARCHERY_RANGE = "archery_range",
  SIEGE_WORKSHOP = "siege_workshop",
  BLACKSMITH = "blacksmith",
  TOWN = "town",
  CREATURE_DEN = "creature_den",
  TOWER = "tower",
  FARM = "farm",
  HAMLET = "hamlet",
  EMBASSY = "embassy",
  FORWARD_CASTLE = "forward_castle",
  FORWARD_TOWER = "forward_tower",
  ARCHIVE = "archive",
  TEMPLE = "temple",
  WALL = "wall",
  FIREPIT = "firepit",
  MILL = "mill",
  ELITE_HALL = "elite_hall",
  MARKET = "market",
  FACTION_HALL = "faction_hall",
  LIGHTNING_TOWER = "lightning_tower",
  ICE_TOWER = "ice_tower",
  FIRE_TOWER = "fire_tower",
  WARP_TOWER = "warp_tower",
  HEALING_TOWER = "healing_tower",
  BALLISTA_TOWER = "ballista_tower",
  REPEATER_TOWER = "repeater_tower",
  ARCHITECTS_GUILD = "architects_guild",
  HOUSE1 = "house1",
  HOUSE2 = "house2",
  HOUSE3 = "house3",
  ELITE_BARRACKS = "elite_barracks",
  ELITE_ARCHERY_RANGE = "elite_archery_range",
  ELITE_SIEGE_WORKSHOP = "elite_siege_workshop",
  ELITE_MAGE_TOWER = "elite_mage_tower",
  ELITE_STABLES = "elite_stables",
}

export enum AbilityType {
  FIREBALL = "fireball",
  CHAIN_LIGHTNING = "chain_lightning",
  WARP = "warp",
  SUMMON = "summon",
  FIRE_IMP_SUMMON = "fire_imp_summon",
  ICE_IMP_SUMMON = "ice_imp_summon",
  LIGHTNING_IMP_SUMMON = "lightning_imp_summon",
  DISTORTION_IMP_SUMMON = "distortion_imp_summon",
  FIRE_MASTER_IMP_SUMMON = "fire_master_imp_summon",
  ICE_MASTER_IMP_SUMMON = "ice_master_imp_summon",
  LIGHTNING_MASTER_IMP_SUMMON = "lightning_master_imp_summon",
  DISTORTION_MASTER_IMP_SUMMON = "distortion_master_imp_summon",
  ICE_BALL = "ice_ball",
  WEB = "web",
  GLADIATOR_NET = "gladiator_net",
  DISTORTION_BLAST = "distortion_blast",
  VOID_DISTORTION = "void_distortion",
  FAERY_DISTORTION = "faery_distortion",
  FROG_TONGUE = "frog_tongue",
  DEVOUR_PULL = "devour_pull",
  HEAL = "heal",
  FIRE_BREATH = "fire_breath",
  FROST_BREATH = "frost_breath",
  FISHERMAN_NET = "fisherman_net",
  FIRE_AURA = "fire_aura",
  ICE_AURA = "ice_aura",
  MINOR_FIRE_AURA = "minor_fire_aura",
  MINOR_ICE_AURA = "minor_ice_aura",
  LIGHTNING_AURA = "lightning_aura",
  DISTORTION_AURA = "distortion_aura",
  MINOR_LIGHTNING_AURA = "minor_lightning_aura",
  MINOR_DISTORTION_AURA = "minor_distortion_aura",
}

export enum UpgradeType {
  MELEE_DAMAGE = "melee_damage",
  MELEE_HEALTH = "melee_health",
  RANGED_DAMAGE = "ranged_damage",
  RANGED_HEALTH = "ranged_health",
  SIEGE_DAMAGE = "siege_damage",
  SIEGE_HEALTH = "siege_health",
  CREATURE_DAMAGE = "creature_damage",
  CREATURE_HEALTH = "creature_health",
  MAGE_RANGE = "mage_range",
  FLAG = "flag",
  TOWER_RANGE = "tower_range",
  TOWER_DAMAGE = "tower_damage",
  TOWER_HEALTH = "tower_health",
  TOWER_COST = "tower_cost",
  SETTLER = "settler",
  ENGINEER = "engineer",
  SUMMON_UNICORN = "summon_unicorn",
  SUMMON_PIXIE = "summon_pixie",
  SUMMON_FIRE_ELEMENTAL = "summon_fire_elemental",
  SUMMON_ICE_ELEMENTAL = "summon_ice_elemental",
  SUMMON_RED_DRAGON = "summon_red_dragon",
  SUMMON_FROST_DRAGON = "summon_frost_dragon",
  SUMMON_SPIDER_BROOD = "summon_spider_brood",
  SUMMON_TROLL = "summon_troll",
  SUMMON_ANGEL = "summon_angel",
  SUMMON_CYCLOPS = "summon_cyclops",
  SUMMON_BAT_SWARM = "summon_bat_swarm",
  SUMMON_DARK_SAVANT = "summon_dark_savant",
  SPELL_ARCANE_MISSILE = "spell_arcane_missile",
  SPELL_FIREBALL = "spell_fireball",
  SPELL_BLIZZARD = "spell_blizzard",
  SPELL_LIGHTNING_STRIKE = "spell_lightning_strike",
  SPELL_EARTHQUAKE = "spell_earthquake",
  SPELL_METEOR_STRIKE = "spell_meteor_strike",
  SPELL_VOID_RIFT = "spell_void_rift",
  SPELL_HOLY_SMITE = "spell_holy_smite",
  SPELL_POISON_CLOUD = "spell_poison_cloud",
  SPELL_ARCANE_STORM = "spell_arcane_storm",
  SPELL_HEALING_WAVE = "spell_healing_wave",
  SPELL_DIVINE_RESTORATION = "spell_divine_restoration",
}

export enum UnitState {
  IDLE = "idle",
  MOVE = "move",
  ATTACK = "attack",
  CAST = "cast",
  DIE = "die",
}

export enum BuildingState {
  GHOST = "ghost",
  ACTIVE = "active",
  DESTROYED = "destroyed",
}

export enum GamePhase {
  PREP = "prep",
  BATTLE = "battle",
  RESOLVE = "resolve",
}

export enum GameMode {
  STANDARD = "standard",
  DEATHMATCH = "deathmatch",
  BATTLEFIELD = "battlefield",
  CAMPAIGN = "campaign",
  ROGUELIKE = "roguelike",
}

export enum MapType {
  MEADOW = "meadow",
  GRASS = "grass",
  PLAINS = "plains",
  FOREST = "forest",
  FANTASIA = "fantasia",
  TUNDRA = "tundra",
  SWAMP = "swamp",
  VOLCANIC = "volcanic",
  OCEAN = "ocean",
}
